QUERY_TYPES = {
    "user_data": {
        "name": "用户信息",
        "description": "客户或员工基本数据查询",
        "query_service": "warehouse_user_service",
        "service_method": "get_user",
        "required_params": ["crm_user_id"],
        "one_of_params": ["user_id", "username", "user_name", "email"],
        "optional_params": [
            "country",
            "register_time",
            "kyc",
            "limit",
            "page",
            "size",
        ],
    },
    "user_amount_log": {
        "name": "资金信息",
        "description": "用户资金信息查询",
        "query_service": "warehouse_user_service",
        "service_method": "get_user_amount_log",
        "required_params": ["crm_user_id"],
        "one_of_params": ["user_id", "username", "user_name", "email"],
        "optional_params": [
            "start_time",
            "end_time",
            "limit",
            "page",
            "size",
        ],
    },
    "user_login_log": {
        "name": "登录信息",
        "description": "用户登录信息查询",
        "query_service": "warehouse_user_service",
        "service_method": "get_user_login_log",
        "required_params": ["crm_user_id"],
        "one_of_params": ["user_id", "username", "user_name", "email"],
        "optional_params": [
            "start_time",
            "end_time",
            "limit",
            "page",
            "size",
        ],
    },
    "user_forword_log": {
        "name": "转账信息",
        "description": "用户转账信息查询",
        "query_service": "warehouse_user_service",
        "service_method": "get_user_forword_log",
        "required_params": ["crm_user_id"],
        "one_of_params": ["user_id", "username", "user_name", "email"],
        "optional_params": [
            "start_time",
            "end_time",
            "limit",
            "page",
            "size",
        ],
    },
    "user_mtlogin": {
        "name": "mt交易账号信息",
        "description": "用户mt交易账号信息查询",
        "query_service": "warehouse_user_service",
        "service_method": "get_user_mtlogin",
        "required_params": ["crm_user_id"],
        "one_of_params": ["user_id", "username", "user_name"],
        "optional_params": ["range_time", "limit"],
    },
    "user_mt4_trades": {
        "name": "mt4交易信息",
        "description": "用户mt4交易信息查询",
        "query_service": "mt4_service",
        "service_method": "get_mt4_194_trades",
        "required_params": ["crm_user_id"],
        "one_of_params": ["user_id", "username", "user_name"],
        "optional_params": [
            "range_time",
            "start_time",
            "end_time",
            "limit",
        ],
    },
    "user_mt4_user": {
        "name": "mt4用户信息",
        "description": "用户mt4用户信息查询",
        "query_service": "mt4_service",
        "service_method": "get_mt4_194_user",
        "required_params": ["crm_user_id"],
        "one_of_params": ["user_id", "username", "user_name"],
        "optional_params": ["limit"],
    },
    "user_mt5_trades": {
        "name": "mt5交易信息",
        "description": "用户mt5交易信息查询",
        "query_service": "mt5_service",
        "service_method": "get_mt5_1110_trades",
        "required_params": ["crm_user_id"],
        "one_of_params": ["user_id", "username", "user_name"],
        "optional_params": [
            "range_time",
            "start_time",
            "end_time",
            "limit",
        ],
    },
    "user_mt5_user": {
        "name": "mt5用户信息",
        "description": "用户mt5用户信息查询",
        "query_service": "mt5_service",
        "service_method": "get_mt5_1110_user",
        "required_params": ["crm_user_id"],
        "one_of_params": ["user_id", "username", "user_name"],
        "optional_params": ["limit"],
    },
    "user_mt5_positions": {
        "name": "mt5持仓信息",
        "description": "用户mt5持仓信息查询",
        "query_service": "mt5_service",
        "service_method": "get_mt5_1110_positions",
        "required_params": ["crm_user_id"],
        "one_of_params": ["user_id", "username", "user_name"],
        "optional_params": [
            "range_time",
            "start_time",
            "end_time",
            "limit",
        ],
    },
    "user_op_log": {
        "name": "操作日志",
        "description": "用户操作日志查询",
        "query_service": "warehouse_user_service",
        "service_method": "get_user_op_log",
        "required_params": ["crm_user_id"],
        "optional_params": ["start_time", "end_time", "limit", "page", "size"],
    },
    "direct_staff_statistics": {
        "name": "客户或员工用户统计",
        "description": "客户或员工用的入金账号数，出金账号数，入金金额，出金金额, 登录账号数, 登录次数等统计数据",
        "query_service": "statistics_service",
        "service_method": "get_statistics",
        "required_params": ["crm_user_id"],
        "one_of_params": [],
        "optional_params": [
            "statistics_name",
            "user_id",
            "username",
            "start_time",
            "end_time",
        ],
    },
    "agent_statistics": {
        "name": "代理用户的统计",
        "description": "代理用户的客户数统计，入金统计，出金统计，返佣统计，交易统计(百万交易量)，交易统计(利润)，交易统计(交易数量)",
        "query_service": "statistics_service",
        "service_method": "get_ib_statistics",
        "required_params": ["crm_user_id"],
        "one_of_params": [],
        "optional_params": [],
    },
    "tool_foreign_exchange_market_data": {
        "name": "外汇行情数据",
        "description": "调用工具查询外汇行情数据",
        "query_service": "tool_service",
        "service_method": "get_wh_data",
        "required_params": ["code"],
        "one_of_params": [],
        "optional_params": ["days", "period"],
    },
}
