VALID_OPERATORS = (
    "=",
    "<>",
    "!=",
    ">",
    ">=",
    "<",
    "<=",
    "LIKE",
    "NOT LIKE",
    "IN",
    "NOT IN",
    "BETWEEN",
    "IS NULL",
    "IS NOT NULL",
    "EXISTS",
    "NOT EXISTS",
    "IN SUBQUERY",
    "NOT IN SUBQUERY",
)
SQL_TABLES = {
    "t_member": {
        "database_name": "devapi1_mtarde_c",
        "table_name": "t_member",
        "fields": [
            "id",
            "nickname",
            "register_ip",
            "register_group",
            "register_area",
            "email",
            "d_code",
            "country",
            "banned_login",
            "remark",
            "login_error_used",
            "login_error_time",
            "leverage",
            "update_time",
            "mlevel",
            "userType",
            "kyc_status",
            "Iscertified",
            "commission_value",
            "create_time",
        ],
    },
    "t_member_amount_log": {
        "database_name": "devapi1_mtarde_c",
        "table_name": "t_fund_changes_history",
        "fields": [
            "id",
            "member_id",
            "source_account",
            "source_money",
            "source_currency",
            "destination_money",
            "destination_currency",
            "destination_money_usd",
            "payment_method_name",
            "direction",
            "status",
            "created_at",
        ],
    },
    "t_currency_rate": {
        "database_name": "devapi1_mtarde_c",
        "table_name": "t_currency_rate",
        "fields": ["id", "currency", "out_rate", "rate_type"],
    },
    "t_member_login_log": {
        "database_name": "devapi1_mtarde_c",
        "table_name": "t_member_login_log",
        "fields": [
            "id",
            "member_id",
            "ip",
            "agent",
            "type",
            "create_time",
            "version",
            "country",
            "city",
            "ccode",
        ],
    },
    "t_member_forword_log": {
        "database_name": "devapi1_mtarde_c",
        "table_name": "t_member_forword_log",
        "fields": [
            "id",
            "member_id",
            "to_member_id",
            "member_currency",
            "to_member_currency",
            "exchange_rate",
            "member_amount",
            "to_member_amount",
            "status",
            "error_message",
            "create_time",
            "visit_where",
        ],
    },
    "t_member_mtlogin": {
        "database_name": "devapi1_mtarde_c",
        "table_name": "t_member_mtlogin",
        "fields": [
            "id",
            "member_id",
            "loginid",
            "mtserver",
            "status",
            "amount",
            "is_real",
            "create_time",
            "open_account_type",
        ],
        "relation_field": "mtserver",
        "link_table": {
            "table_name": "t_mt_server",
            "fields": ["db_name"],
            "relation_field": "id",
        },
    },
    "t_mt_server": {
        "database_name": "devapi1_mtarde_c",
        "table_name": "t_mt_server",
        "fields": [
            "id",
            "mt_name",
            "mt_server",
            "mt_manager",
            "mt_password",
            "create_time",
            "update_time",
            "real",
            "company_id",
            "status",
            "time_zone",
            "db_name",
            "start_number",
            "end_number",
            "default_open_svr",
            "default_inmoney",
            "ver",
            "win_svr_name",
            "plat_from_id",
            "direct_start_number",
            "direct_end_number",
            "agent_start_number",
            "agent_end_number",
            "member_start_number",
            "member_end_number",
            "client_id",
            "rest_port",
            "exchange_name",
            "sn",
            "kline_url",
            "reset_url",
            "trade_url",
            "price_url",
            "real_mt_name",
        ],
    },
    "mt4_trades_194": {
        "database_name": "mt4_report_194",
        "table_name": "mt4_trades",
        "fields": [
            "LOGIN",
            "SYMBOL",
            "CMD",
            "VOLUME",
            "OPEN_TIME",
            "OPEN_PRICE",
            "PROFIT",
            "CLOSE_TIME",
            "SWAPS",
        ],
    },
    "mt4_users_194": {
        "database_name": "mt4_report_194",
        "table_name": "mt4_users",
        "fields": [
            "LOGIN",
            "GROUP",
            "ENABLE",
            "NAME",
            "COUNTRY",
            "CITY",
            "STATE",
            "BALANCE",
            "PREVMONTHBALANCE",
            "PREVBALANCE",
        ],
    },
    "mt5_trades_1110": {
        "database_name": "mt5_report_1110",
        "table_name": "mt4_trades",
        "fields": [
            "LOGIN",
            "TICKET",
            "SYMBOL",
            "CMD",
            "Time",
            "VOLUME",
            "ORDER",
            "POSITIONID",
            "PRICE",
            "PRICEPOSITION",
            "CONTRACTSIZE",
            "TIME",
            "Entry",
            "COMMISSION",
            "SWAPS",
            "PROFIT",
            "STORAGE",
            "VOLUMECLOSED",
            "ENTRY",
            "MILLIONUSD",
        ],
    },
    "mt5_users_1110": {
        "database_name": "mt5_report_1110",
        "table_name": "mt4_users",
        "fields": [
            "LOGIN",
            "GROUP",
            "ENABLE",
            "NAME",
            "COUNTRY",
            "CITY",
            "STATE",
            "BALANCE",
            "PREVMONTHBALANCE",
            "PREVBALANCE",
        ],
    },
    "mt5_positions_1110": {
        "database_name": "mt5_report_1110",
        "table_name": "mt_positions",
        "fields": [
            "Login",
            "Position",
            "Symbol",
            "Action",
            "PriceOpen",
            "PriceCurrent",
            "Volume",
            "PriceSL",
            "ContractSize",
            "Profit",
            "Storage",
            "TimeCreate",
        ],
    },
    "t_operation_log": {
        "database_name": "devapi1_mtarde_c",
        "table_name": "t_operation_log",
        "fields": [
            "id",
            "member_id",
            "method",
            "nickname",
            "created_at",
            "ip",
            "ip_country",
            "ip_province",
            "device_name",
            "browser_name",
            "client_type",
        ],
    },
    "ib_report_trades": {
        "database_name": "ib_report",
        "table_name": "mt4_trades",
        "fields": [
            "LOGIN",
            "SYMBOL",
            "CMD",
            "VOLUME",
            "OPEN_TIME",
            "OPEN_PRICE",
            "PROFIT",
            "CLOSE_TIME",
            "SWAPS",
        ],
    },
    "ib_report_users": {
        "database_name": "ib_report",
        "table_name": "mt4_users",
        "fields": [
            "LOGIN",
            "GROUP",
            "ENABLE",
            "NAME",
            "COUNTRY",
            "CITY",
            "STATE",
            "BALANCE",
            "PREVMONTHBALANCE",
            "PREVBALANCE",
        ],
    },
    "mt5_report_trades": {
        "database_name": "mt5_report",
        "table_name": "mt4_trades",
        "fields": [
            "LOGIN",
            "TICKET",
            "SYMBOL",
            "CMD",
            "Time",
            "VOLUME",
            "ORDER",
            "POSITIONID",
            "PRICE",
            "PRICEPOSITION",
            "CONTRACTSIZE",
            "TIME",
            "COMMISSION",
            "SWAPS",
            "PROFIT",
            "STORAGE",
            "VOLUMECLOSED",
            "ENTRY",
            "MILLIONUSD",
        ],
    },
    "mt5_report_users": {
        "database_name": "mt5_report",
        "table_name": "mt4_users",
        "fields": [
            "LOGIN",
            "GROUP",
            "ENABLE",
            "NAME",
            "COUNTRY",
            "CITY",
            "STATE",
            "BALANCE",
            "PREVMONTHBALANCE",
            "PREVBALANCE",
        ],
    },
    "mt5_report_positions": {
        "database_name": "mt5_report",
        "table_name": "mt_positions",
        "fields": [
            "Login",
            "Position",
            "Symbol",
            "Action",
            "PriceOpen",
            "PriceCurrent",
            "Volume",
            "PriceSL",
            "ContractSize",
            "Profit",
            "Storage",
            "TimeCreate",
        ],
    },
}
