INTENT_PATTERNS = {
    "user_data": {
        "name": "用户基本信息",
        "description": "客户，员工的用户基本信息。",
        "fields": {
            "id": "用户id",
            "nickname": "用户昵称",
            "register_ip": "注册ip",
            "register_group": "注册所在组",
            "register_area": "注册所在地区",
            "email": "用户邮箱",
            "d_code": "国家代码",
            "country": "国家",
            "banned_login": "是否禁止登录:0=允许登录 1=禁止登录",
            "remark": "备注",
            "login_error_used": "错误登录次数",
            "login_error_time": "错误登录时间",
            "leverage": "注册开户杠杠比例",
            "update_time": "更新时间",
            "mlevel": "用户等级",
            "userType": "用户类型：agent:代理商 direct:直接客户,staff:员工",
            "kyc_status": "KYC状态， 0、未KYC  1、问卷调查 2.基础信息  3、上传证件 4、签署合同 5、上传住址证明 9、KYC成功 -1、KYC失败",
            "Iscertified": "是否认证0未认证 1已认证",
            "commission_value": "返佣比例",
            "create_time": "创建时间",
        },
        "parameters": [
            {
                "name": "user_id",
                "description": "根据客户，员工，代理的用户ID查询用户基本信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户ID",
                    "没有指明用户id默认是空",
                ],
                "example_value": "输入：查询用户ID为123456的用户基本信息。提取:user_id为123456",
            },
            {
                "name": "user_name",
                "description": "根据客户，员工，代理的用户名称查询用户基本信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户名称",
                    "没有指明用户名称默认是空",
                ],
                "example_value": "输入：查询用户名称为123456的用户基本信息。提取:user_name为123456",
            },
            {
                "name": "email",
                "description": "根据客户，员工，代理的邮箱查询用户基本信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的邮箱",
                    "没有指明邮箱默认是空",
                ],
                "example_value": "输入：查询邮箱为123456@gmail.com的用户基本信息。提取:email为123456@gmail.com",
            },
            {
                "name": "user_type",
                "description": "根据客户，员工，代理的用户类型查询用户基本信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["direct", "staff"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "direct: 客户",
                    # "agent: 代理",
                    "staff: 员工",
                ],
                "example_value": "输入：查询员工名称为张三的用户基本信息。提取:user_type为staff",
            },
            {
                "name": "country",
                "description": "根据客户，员工，代理的国家查询用户基本信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "必须是有效的国家名称",
                    "如果非标准国家的英语名称，请转换为标准英语国家名称",
                ],
                "example_value": "输入：查询中国用户的基本信息。提取:country为['china']",
            },
            {
                "name": "kyc",
                "description": "根据客户，员工，代理的kyc查询用户基本信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["0", "1", "2", "3", "4", "5", "9", "-1"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "0: 未KYC",
                    "1: 问卷调查",
                    "2: 基础信息",
                    "3: 上传证件",
                    "4: 签署合同",
                    "5: 上传住址证明",
                    "9: KYC成功",
                    "-1: KYC失败",
                ],
                "example_value": "输入：查询kyc为'问卷调查'的用户基本信息。提取:kyc为1",
            },
            {
                "name": "register_time",
                "description": "根据客户，员工，代理的用户注册时间查询用户基本信息。",
                "required": False,
                "data_type": "dict",
                "validator_rules": [
                    "根据当前时间计算有效的时间格式",
                    "register_start_date: 开始日期",
                    "register_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月前注册的用户基本信息。假设当前时间是2024-02-01 00:00:00，提取:register_time为{'register_start_date': '2024-01-01 00:00:00', 'register_end_date': '2024-02-01 00:00:00'}",
            },
        ],
    },
    "user_amount_log": {
        "name": "用户资金记录",
        "description": "用户资金，出入金变动信息。",
        "fields": {
            "id": "ID",
            "member_id": "会员id",
            "source_account": "来源账户",
            "source_money": "来源金额",
            "source_currency": "来源币种",
            "destination_money": "目标金额",
            "destination_currency": "来源币种",
            "destination_money_usd": "目标币种usd",
            "payment_method_name": "支付方式名称",
            "direction": "方向(1入金--2出金)默认1",
            "status": "状态",
            "created_at": "创建时间",
        },
        "parameters": [
            {
                "name": "range_time",
                "description": "根据时间范围查询资金变动信息。",
                "required": True,
                "data_type": "dict",
                "validator_rules": [
                    "根据当前时间计算有效的时间格式",
                    "data_start_date: 开始日期",
                    "data_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月的出入金信息。假设当前时间是2024-02-01 00:00:00，提取:range_time为{'data_start_date': '2024-01-01 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
            {
                "name": "user_id",
                "description": "根据客户，员工，代理的用户ID查询资金变动信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户ID",
                    "没有指明用户id默认是空",
                ],
                "example_value": "输入：查询用户ID为123456的资金信息。提取:user_id为123456",
            },
            {
                "name": "user_name",
                "description": "根据客户，员工，代理的用户名称查询资金信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户名称",
                    "没有指明用户名称默认是空",
                ],
                "example_value": "输入：查询用户名称为123456的资金变动信息。提取:user_name为123456",
            },
            {
                "name": "email",
                "description": "根据客户，员工，代理的邮箱查询资金信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的邮箱",
                    "没有指明邮箱默认是空",
                ],
                "example_value": "输入：查询邮箱为123456@gmail.com的资金信息。提取:email为123456@gmail.com",
            },
            {
                "name": "user_type",
                "description": "根据客户，员工，代理的用户类型查询资金信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["direct", "agent", "staff"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "direct: 客户",
                    "agent: 代理",
                    "staff: 员工",
                ],
                "example_value": "输入：查询员工名称为张三的资金信息。提取:user_type为staff",
            },
            {
                "name": "country",
                "description": "根据客户，员工，代理的国家查询用户基本信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "必须是有效的国家名称",
                    "如果非标准国家的英语名称，请转换为标准英语国家名称",
                ],
                "example_value": "输入：查询中国用户的基本信息。提取:country为['china']",
            },
            {
                "name": "kyc",
                "description": "根据客户，员工，代理的kyc查询资金信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["0", "1", "2", "3", "4", "5", "9", "-1"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "0: 未KYC",
                    "1: 问卷调查",
                    "2: 基础信息",
                    "3: 上传证件",
                    "4: 签署合同",
                    "5: 上传住址证明",
                    "9: KYC成功",
                    "-1: KYC失败",
                ],
                "example_value": "输入：查询kyc为'问卷调查'的资金信息。提取:kyc为1",
            },
            {
                "name": "register_time",
                "description": "根据客户，员工，代理的用户注册时间查询资金信息。",
                "required": False,
                "data_type": "dict",
                "validator_rules": [
                    "指的是用户的注册时间，包括客户注册时间，员工注册时间，代理注册时间。不要与数据查询时间混淆",
                    "根据当前时间计算有效的时间格式",
                    "register_start_date: 开始日期",
                    "register_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月前注册的客户5天前的资金信息。假设当前时间是2024-02-01 00:00:00，提取:register_time为{'register_start_date': '2024-01-01 00:00:00', 'register_end_date': '2024-02-01 00:00:00'} 。range_time为{'data_start_date': '2024-01-27 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
        ],
    },
    "user_login_log": {
        "name": "用户登录记录",
        "description": "用户的登入，登出信息。",
        "fields": {
            "id": "ID",
            "member_id": "会员ID",
            "ip": "登录ip",
            "agent": "浏览器信息",
            "type": "设备类型",
            "create_time": "创建时间",
            "version": "系统版本",
            "country": "国家",
            "city": "城市",
            "ccode": "国家代码",
        },
        "parameters": [
            {
                "name": "range_time",
                "description": "根据时间范围查询登录，登出信息。",
                "required": True,
                "data_type": "dict",
                "validator_rules": [
                    "根据当前时间计算有效的时间格式",
                    "data_start_date: 开始日期",
                    "data_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月的登录，登出信息。假设当前时间是2024-02-01 00:00:00，提取:range_time为{'data_start_date': '2024-01-01 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
            {
                "name": "user_id",
                "description": "根据客户，员工，代理的用户ID查询登录，登出信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户ID",
                    "没有指明用户id默认是空",
                ],
                "example_value": "输入：查询用户ID为123456的登录，登出信息。提取:user_id为123456",
            },
            {
                "name": "user_name",
                "description": "根据客户，员工，代理的用户名称查询登录，登出信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户名称",
                    "没有指明用户名称默认是空",
                ],
                "example_value": "输入：查询用户名称为123456的登录，登出信息。提取:user_name为123456",
            },
            {
                "name": "email",
                "description": "根据客户，员工，代理的邮箱查询登录，登出信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的邮箱",
                    "没有指明邮箱默认是空",
                ],
                "example_value": "输入：查询邮箱为123456@gmail.com的登录，登出信息。提取:email为123456@gmail.com",
            },
            {
                "name": "user_type",
                "description": "根据客户，员工，代理的用户类型查询登录，登出信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["direct", "agent", "staff"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "direct: 客户",
                    "agent: 代理",
                    "staff: 员工",
                ],
                "example_value": "输入：查询员工名称为张三的登录，登出信息。提取:user_type为staff",
            },
            {
                "name": "country",
                "description": "根据客户，员工，代理的国家查询登录，登出信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "必须是有效的国家名称",
                    "如果非标准国家的英语名称，请转换为标准英语国家名称",
                ],
                "example_value": "输入：查询中国用户的登录，登出信息。提取:country为['china']",
            },
            {
                "name": "kyc",
                "description": "根据客户，员工，代理的kyc查询登录，登出信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["0", "1", "2", "3", "4", "5", "9", "-1"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "0: 未KYC",
                    "1: 问卷调查",
                    "2: 基础信息",
                    "3: 上传证件",
                    "4: 签署合同",
                    "5: 上传住址证明",
                    "9: KYC成功",
                    "-1: KYC失败",
                ],
                "example_value": "输入：查询kyc为'问卷调查'的登录，登出信息。提取:kyc为1",
            },
            {
                "name": "register_time",
                "description": "根据客户，员工，代理的用户注册时间查询登录，登出信息。",
                "required": False,
                "data_type": "dict",
                "validator_rules": [
                    "指的是用户的注册时间，包括客户注册时间，员工注册时间，代理注册时间。不要与数据查询时间混淆",
                    "根据当前时间计算有效的时间格式",
                    "register_start_date: 开始日期",
                    "register_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月前注册的客户5天前的登录，登出信息。假设当前时间是2024-02-01 00:00:00，提取:register_time为{'register_start_date': '2024-01-01 00:00:00', 'register_end_date': '2024-02-01 00:00:00'} 。range_time为{'data_start_date': '2024-01-27 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
        ],
    },
    "user_forword_log": {
        "name": "用户转账记录",
        "description": "用户的转账信息，转账记录。",
        "fields": {
            "id": "ID",
            "member_id": "发起人ID",
            "to_member_id": "接收人ID",
            "member_currency": "发起人货币类型",
            "to_member_currency": "接收人货币类型",
            "exchange_rate": "目标货币对本账号的应用汇率",
            "member_amount": "发起人转账金额",
            "to_member_amount": "接收人实际收到金额",
            "status": "资金划转状态:-2初始化||1下账成功||2下账失败||3上账失败||4已驳回钱已退回||9上账成功",
            "error_message": "错误信息",
            "create_time": "创建时间",
            "visit_where": "触发条件需要审核的原因",
        },
        "parameters": [
            {
                "name": "range_time",
                "description": "根据时间范围查询转账信息。",
                "required": True,
                "data_type": "dict",
                "validator_rules": [
                    "根据当前时间计算有效的时间格式",
                    "data_start_date: 开始日期",
                    "data_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月的转账信息。假设当前时间是2024-02-01 00:00:00，提取:range_time为{'data_start_date': '2024-01-01 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
            {
                "name": "user_id",
                "description": "根据客户，员工，代理的用户ID查询转账信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户ID",
                    "没有指明用户id默认是空",
                ],
                "example_value": "输入：查询用户ID为123456的转账信息。提取:user_id为123456",
            },
            {
                "name": "user_name",
                "description": "根据客户，员工，代理的用户名称查询转账信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户名称",
                    "没有指明用户名称默认是空",
                ],
                "example_value": "输入：查询用户名称为123456的转账信息。提取:user_name为123456",
            },
            {
                "name": "email",
                "description": "根据客户，员工，代理的邮箱查询转账信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的邮箱",
                    "没有指明邮箱默认是空",
                ],
                "example_value": "输入：查询邮箱为123456@gmail.com的转账信息。提取:email为123456@gmail.com",
            },
            {
                "name": "user_type",
                "description": "根据客户，员工，代理的用户类型查询转账信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["direct", "agent", "staff"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "direct: 客户",
                    "agent: 代理",
                    "staff: 员工",
                ],
                "example_value": "输入：查询员工名称为张三的转账信息。提取:user_type为staff",
            },
            {
                "name": "country",
                "description": "根据客户，员工，代理的国家查询转账信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "必须是有效的国家名称",
                    "如果非标准国家的英语名称，请转换为标准英语国家名称",
                ],
                "example_value": "输入：查询中国用户的转账信息。提取:country为['china']",
            },
            {
                "name": "kyc",
                "description": "根据客户，员工，代理的kyc查询转账信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["0", "1", "2", "3", "4", "5", "9", "-1"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "0: 未KYC",
                    "1: 问卷调查",
                    "2: 基础信息",
                    "3: 上传证件",
                    "4: 签署合同",
                    "5: 上传住址证明",
                    "9: KYC成功",
                    "-1: KYC失败",
                ],
                "example_value": "输入：查询kyc为'问卷调查'的转账信息。提取:kyc为1",
            },
            {
                "name": "register_time",
                "description": "根据客户，员工，代理的用户注册时间查询转账信息。",
                "required": False,
                "data_type": "dict",
                "validator_rules": [
                    "指的是用户的注册时间，包括客户注册时间，员工注册时间，代理注册时间。不要与数据查询时间混淆",
                    "根据当前时间计算有效的时间格式",
                    "register_start_date: 开始日期",
                    "register_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月前注册的客户5天前的转账信息。假设当前时间是2024-02-01 00:00:00，提取:register_time为{'register_start_date': '2024-01-01 00:00:00', 'register_end_date': '2024-02-01 00:00:00'} 。range_time为{'data_start_date': '2024-01-27 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
        ],
    },
    "user_mtlogin": {
        "name": "MT交易账号",
        "description": "用户MT交易账号信息。",
        "fields": {
            "id": "ID",
            "member_id": "会员ID",
            "loginid": "登录ID",
            "mtserver": "MT服务器",
            "status": "-1:已删除 1:正常账户 2:归档账户",
            "is_real": "是否真实账号 0:模拟账号 1:真实账号",
            "create_time": "创建时间",
            "open_account_type": "账户类型 例如ECN",
        },
        "parameters": [
            {
                "name": "range_time",
                "description": "根据时间范围查询MT交易账号信息。",
                "required": True,
                "data_type": "dict",
                "validator_rules": [
                    "根据当前时间计算有效的时间格式",
                    "data_start_date: 开始日期",
                    "data_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月的MT交易账号信息。假设当前时间是2024-02-01 00:00:00，提取:range_time为{'data_start_date': '2024-01-01 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
            {
                "name": "user_id",
                "description": "根据客户，员工，代理的用户ID查询MT交易账号信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户ID",
                    "没有指明用户id默认是空",
                ],
                "example_value": "输入：查询用户ID为123456的MT交易账号信息。提取:user_id为123456",
            },
            {
                "name": "user_name",
                "description": "根据客户，员工，代理的用户名称查询MT交易账号信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户名称",
                    "没有指明用户名称默认是空",
                ],
                "example_value": "输入：查询用户名称为123456的MT交易账号信息。提取:user_name为123456",
            },
            {
                "name": "email",
                "description": "根据客户，员工，代理的邮箱查询MT交易账号信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的邮箱",
                    "没有指明邮箱默认是空",
                ],
                "example_value": "输入：查询邮箱为123456@gmail.com的MT交易账号信息。提取:email为123456@gmail.com",
            },
            {
                "name": "user_type",
                "description": "根据客户，员工，代理的用户类型查询MT交易账号信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["direct", "agent", "staff"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "direct: 客户",
                    "agent: 代理",
                    "staff: 员工",
                ],
                "example_value": "输入：查询员工名称为张三的MT交易账号信息。提取:user_type为staff",
            },
            {
                "name": "country",
                "description": "根据客户，员工，代理的国家查询MT交易账号信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "必须是有效的国家名称",
                    "如果非标准国家的英语名称，请转换为标准英语国家名称",
                ],
                "example_value": "输入：查询中国用户的MT交易账号信息。提取:country为['china']",
            },
            {
                "name": "kyc",
                "description": "根据客户，员工，代理的kyc查询MT交易账号信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["0", "1", "2", "3", "4", "5", "9", "-1"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "0: 未KYC",
                    "1: 问卷调查",
                    "2: 基础信息",
                    "3: 上传证件",
                    "4: 签署合同",
                    "5: 上传住址证明",
                    "9: KYC成功",
                    "-1: KYC失败",
                ],
                "example_value": "输入：查询kyc为'问卷调查'的MT交易账号信息。提取:kyc为1",
            },
            {
                "name": "register_time",
                "description": "根据客户，员工，代理的用户注册时间查询MT交易账号信息。",
                "required": False,
                "data_type": "dict",
                "validator_rules": [
                    "指的是用户的注册时间，包括客户注册时间，员工注册时间，代理注册时间。不要与数据查询时间混淆",
                    "根据当前时间计算有效的时间格式",
                    "register_start_date: 开始日期",
                    "register_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月前注册的客户5天前的MT交易账号信息。假设当前时间是2024-02-01 00:00:00，提取:register_time为{'register_start_date': '2024-01-01 00:00:00', 'register_end_date': '2024-02-01 00:00:00'} 。range_time为{'data_start_date': '2024-01-27 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
        ],
    },
    "user_mt4_trades": {
        "name": "MT4交易记录",
        "description": "用户MT4交易信息。",
        "fields": {
            "LOGIN": "登录",
            "SYMBOL": "品种",
            "CMD": "0：买，1：卖",
            "VOLUME": "交易量",
            "OPEN_TIME": "开仓时间",
            "OPEN_PRICE": "开仓价格",
            "PROFIT": "利润",
            "CLOSE_TIME": "平仓时间",
            "SWAPS": "利息",
            "COMMISSION": "佣金",
        },
        "parameters": [
            {
                "name": "range_time",
                "description": "根据时间范围查询MT4交易信息。",
                "required": True,
                "data_type": "dict",
                "validator_rules": [
                    "根据当前时间计算有效的时间格式",
                    "data_start_date: 开始日期",
                    "data_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月的MT4交易信息。假设当前时间是2024-02-01 00:00:00，提取:range_time为{'data_start_date': '2024-01-01 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
            {
                "name": "user_id",
                "description": "根据客户，员工，代理的用户ID查询MT4交易信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户ID",
                    "没有指明用户id默认是空",
                ],
                "example_value": "输入：查询用户ID为123456的MT4交易信息。提取:user_id为123456",
            },
            {
                "name": "user_name",
                "description": "根据客户，员工，代理的用户名称查询MT4交易信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户名称",
                    "没有指明用户名称默认是空",
                ],
                "example_value": "输入：查询用户名称为123456的MT4交易信息。提取:user_name为123456",
            },
            {
                "name": "email",
                "description": "根据客户，员工，代理的邮箱查询MT4交易信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的邮箱",
                    "没有指明邮箱默认是空",
                ],
                "example_value": "输入：查询邮箱为123456@gmail.com的MT4交易信息。提取:email为123456@gmail.com",
            },
            {
                "name": "user_type",
                "description": "根据客户，员工，代理的用户类型查询MT4交易信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["direct", "agent", "staff"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "direct: 客户",
                    "agent: 代理",
                    "staff: 员工",
                ],
                "example_value": "输入：查询员工名称为张三的MT4交易信息。提取:user_type为staff",
            },
            {
                "name": "country",
                "description": "根据客户，员工，代理的国家查询MT4交易信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "必须是有效的国家名称",
                    "如果非标准国家的英语名称，请转换为标准英语国家名称",
                ],
                "example_value": "输入：查询中国用户的MT4交易信息。提取:country为['china']",
            },
            {
                "name": "kyc",
                "description": "根据客户，员工，代理的kyc查询MT4交易信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["0", "1", "2", "3", "4", "5", "9", "-1"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "0: 未KYC",
                    "1: 问卷调查",
                    "2: 基础信息",
                    "3: 上传证件",
                    "4: 签署合同",
                    "5: 上传住址证明",
                    "9: KYC成功",
                    "-1: KYC失败",
                ],
                "example_value": "输入：查询kyc为'问卷调查'的MT4交易信息。提取:kyc为1",
            },
            {
                "name": "register_time",
                "description": "根据客户，员工，代理的用户注册时间查询MT4交易信息。",
                "required": False,
                "data_type": "dict",
                "validator_rules": [
                    "指的是用户的注册时间，包括客户注册时间，员工注册时间，代理注册时间。不要与数据查询时间混淆",
                    "根据当前时间计算有效的时间格式",
                    "register_start_date: 开始日期",
                    "register_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月前注册的客户5天前的MT4交易信息。假设当前时间是2024-02-01 00:00:00，提取:register_time为{'register_start_date': '2024-01-01 00:00:00', 'register_end_date': '2024-02-01 00:00:00'} 。range_time为{'data_start_date': '2024-01-27 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
        ],
    },
    "user_mt4_user": {
        "name": "MT4用户信息",
        "description": "用户MT4用户信息。",
        "fields": {
            "LOGIN": "登录",
            "GROUP": "组",
            "ENABLE": "启用 0: 禁用 1: 启用",
            "NAME": "名称",
            "COUNTRY": "国家",
            "CITY": "城市",
            "STATE": "状态",
            "BALANCE": "余额",
            "PREVMONTHBALANCE": "上个月余额",
            "PREVBALANCE": "上个月余额",
            "REGDATE": "开户时间",
        },
        "parameters": [
            {
                "name": "range_time",
                "description": "根据时间范围查询MT4用户信息。",
                "required": True,
                "data_type": "dict",
                "validator_rules": [
                    "根据当前时间计算有效的时间格式",
                    "data_start_date: 开始日期",
                    "data_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月的MT4用户信息。假设当前时间是2024-02-01 00:00:00，提取:range_time为{'data_start_date': '2024-01-01 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
            {
                "name": "user_id",
                "description": "根据客户，员工，代理的用户ID查询MT4用户信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户ID",
                    "没有指明用户id默认是空",
                ],
                "example_value": "输入：查询用户ID为123456的MT4用户信息。提取:user_id为123456",
            },
            {
                "name": "user_name",
                "description": "根据客户，员工，代理的用户名称查询MT4用户信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户名称",
                    "没有指明用户名称默认是空",
                ],
                "example_value": "输入：查询用户名称为123456的MT4用户信息。提取:user_name为123456",
            },
            {
                "name": "email",
                "description": "根据客户，员工，代理的邮箱查询MT4用户信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的邮箱",
                    "没有指明邮箱默认是空",
                ],
                "example_value": "输入：查询邮箱为123456@gmail.com的MT4用户信息。提取:email为123456@gmail.com",
            },
            {
                "name": "user_type",
                "description": "根据客户，员工，代理的用户类型查询MT4用户信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["direct", "agent", "staff"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "direct: 客户",
                    "agent: 代理",
                    "staff: 员工",
                ],
                "example_value": "输入：查询员工名称为张三的MT4用户信息。提取:user_type为staff",
            },
            {
                "name": "country",
                "description": "根据客户，员工，代理的国家查询MT4用户信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "必须是有效的国家名称",
                    "如果非标准国家的英语名称，请转换为标准英语国家名称",
                ],
                "example_value": "输入：查询中国用户的MT4用户信息。提取:country为['china']",
            },
            {
                "name": "kyc",
                "description": "根据客户，员工，代理的kyc查询MT4用户信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["0", "1", "2", "3", "4", "5", "9", "-1"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "0: 未KYC",
                    "1: 问卷调查",
                    "2: 基础信息",
                    "3: 上传证件",
                    "4: 签署合同",
                    "5: 上传住址证明",
                    "9: KYC成功",
                    "-1: KYC失败",
                ],
                "example_value": "输入：查询kyc为'问卷调查'的MT4用户信息。提取:kyc为1",
            },
            {
                "name": "register_time",
                "description": "根据客户，员工，代理的用户注册时间查询MT4用户信息。",
                "required": False,
                "data_type": "dict",
                "validator_rules": [
                    "指的是用户的注册时间，包括客户注册时间，员工注册时间，代理注册时间。不要与数据查询时间混淆",
                    "根据当前时间计算有效的时间格式",
                    "register_start_date: 开始日期",
                    "register_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月前注册的客户5天前的MT4用户信息。假设当前时间是2024-02-01 00:00:00，提取:register_time为{'register_start_date': '2024-01-01 00:00:00', 'register_end_date': '2024-02-01 00:00:00'} 。range_time为{'data_start_date': '2024-01-27 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
        ],
    },
    "user_mt5_trades": {
        "name": "MT5交易记录",
        "description": "用户MT5交易信息。",
        "fields": {
            "LOGIN": "交易账号",
            "TICKET": "交易订单号",
            "SYMBOL": "品种",
            "CMD": "0：买，1：卖",
            "Time": "交易时间",
            "VOLUME": "交易量",
            "POSITIONID": "持仓编号",
            "PRICE": "交易价格",
            "PRICEPOSITION": "持仓价格",
            "COMMISSION": "佣金",
            "SWAPS": "利息",
            "PROFIT": "利润",
            "Entry": "0:开仓，1:平仓",
        },
        "parameters": [
            {
                "name": "range_time",
                "description": "根据时间范围查询MT5交易信息。",
                "required": True,
                "data_type": "dict",
                "validator_rules": [
                    "根据当前时间计算有效的时间格式",
                    "data_start_date: 开始日期",
                    "data_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月的MT5交易信息。假设当前时间是2024-02-01 00:00:00，提取:range_time为{'data_start_date': '2024-01-01 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
            {
                "name": "user_id",
                "description": "根据客户，员工，代理的用户ID查询MT5交易信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户ID",
                    "没有指明用户id默认是空",
                ],
                "example_value": "输入：查询用户ID为123456的MT5交易信息。提取:user_id为123456",
            },
            {
                "name": "user_name",
                "description": "根据客户，员工，代理的用户名称查询MT5交易信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户名称",
                    "没有指明用户名称默认是空",
                ],
                "example_value": "输入：查询用户名称为123456的MT5交易信息。提取:user_name为123456",
            },
            {
                "name": "email",
                "description": "根据客户，员工，代理的邮箱查询MT5交易信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的邮箱",
                    "没有指明邮箱默认是空",
                ],
                "example_value": "输入：查询邮箱为123456@gmail.com的MT5交易信息。提取:email为123456@gmail.com",
            },
            {
                "name": "user_type",
                "description": "根据客户，员工，代理的用户类型查询MT5交易信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["direct", "agent", "staff"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "direct: 客户",
                    "agent: 代理",
                    "staff: 员工",
                ],
                "example_value": "输入：查询员工名称为张三的MT5交易信息。提取:user_type为staff",
            },
            {
                "name": "country",
                "description": "根据客户，员工，代理的国家查询MT5交易信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "必须是有效的国家名称",
                    "如果非标准国家的英语名称，请转换为标准英语国家名称",
                ],
                "example_value": "输入：查询中国用户的MT5交易信息。提取:country为['china']",
            },
            {
                "name": "kyc",
                "description": "根据客户，员工，代理的kyc查询MT5交易信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["0", "1", "2", "3", "4", "5", "9", "-1"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "0: 未KYC",
                    "1: 问卷调查",
                    "2: 基础信息",
                    "3: 上传证件",
                    "4: 签署合同",
                    "5: 上传住址证明",
                    "9: KYC成功",
                    "-1: KYC失败",
                ],
                "example_value": "输入：查询kyc为'问卷调查'的MT5交易信息。提取:kyc为1",
            },
            {
                "name": "register_time",
                "description": "根据客户，员工，代理的用户注册时间查询MT5交易信息。",
                "required": False,
                "data_type": "dict",
                "validator_rules": [
                    "指的是用户的注册时间，包括客户注册时间，员工注册时间，代理注册时间。不要与数据查询时间混淆",
                    "根据当前时间计算有效的时间格式",
                    "register_start_date: 开始日期",
                    "register_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月前注册的客户5天前的MT5交易信息。假设当前时间是2024-02-01 00:00:00，提取:register_time为{'register_start_date': '2024-01-01 00:00:00', 'register_end_date': '2024-02-01 00:00:00'} 。range_time为{'data_start_date': '2024-01-27 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
        ],
    },
    "user_mt5_user": {
        "name": "MT5用户信息",
        "description": "用户MT5用户信息。包括客户和员工",
        "fields": {
            "LOGIN": "登录",
            "GROUP": "组",
            "ENABLE": "启用",
            "NAME": "名称",
            "COUNTRY": "国家",
            "CITY": "城市",
            "STATE": "状态",
            "BALANCE": "余额",
            "PREVMONTHBALANCE": "上个月余额",
            "PREVBALANCE": "上个月余额",
            "REGDATE": "开户时间",
        },
        "parameters": [
            {
                "name": "range_time",
                "description": "根据时间范围查询MT5持仓信息。",
                "required": True,
                "data_type": "dict",
                "validator_rules": [
                    "根据当前时间计算有效的时间格式",
                    "data_start_date: 开始日期",
                    "data_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月的MT5持仓信息。假设当前时间是2024-02-01 00:00:00，提取:range_time为{'data_start_date': '2024-01-01 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
            {
                "name": "user_id",
                "description": "根据客户，员工，代理的用户ID查询MT5持仓信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户ID",
                    "没有指明用户id默认是空",
                ],
                "example_value": "输入：查询用户ID为123456的MT5持仓信息。提取:user_id为123456",
            },
            {
                "name": "user_name",
                "description": "根据客户，员工，代理的用户名称查询MT5持仓信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户名称",
                    "没有指明用户名称默认是空",
                ],
                "example_value": "输入：查询用户名称为123456的MT5持仓信息。提取:user_name为123456",
            },
            {
                "name": "email",
                "description": "根据客户，员工，代理的邮箱查询MT5持仓信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的邮箱",
                    "没有指明邮箱默认是空",
                ],
                "example_value": "输入：查询邮箱为123456@gmail.com的MT5持仓信息。提取:email为123456@gmail.com",
            },
            {
                "name": "user_type",
                "description": "根据客户，员工，代理的用户类型查询MT5持仓信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["direct", "agent", "staff"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "direct: 客户",
                    "agent: 代理",
                    "staff: 员工",
                ],
                "example_value": "输入：查询员工名称为张三的MT5持仓信息。提取:user_type为staff",
            },
            {
                "name": "country",
                "description": "根据客户，员工，代理的国家查询MT5持仓信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "必须是有效的国家名称",
                    "如果非标准国家的英语名称，请转换为标准英语国家名称",
                ],
                "example_value": "输入：查询中国用户的MT5持仓信息。提取:country为['china']",
            },
            {
                "name": "kyc",
                "description": "根据客户，员工，代理的kyc查询MT5持仓信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["0", "1", "2", "3", "4", "5", "9", "-1"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "0: 未KYC",
                    "1: 问卷调查",
                    "2: 基础信息",
                    "3: 上传证件",
                    "4: 签署合同",
                    "5: 上传住址证明",
                    "9: KYC成功",
                    "-1: KYC失败",
                ],
                "example_value": "输入：查询kyc为'问卷调查'的MT5持仓信息。提取:kyc为1",
            },
            {
                "name": "register_time",
                "description": "根据客户，员工，代理的用户注册时间查询MT5持仓信息。",
                "required": False,
                "data_type": "dict",
                "validator_rules": [
                    "指的是用户的注册时间，包括客户注册时间，员工注册时间，代理注册时间。不要与数据查询时间混淆",
                    "根据当前时间计算有效的时间格式",
                    "register_start_date: 开始日期",
                    "register_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月前注册的客户5天前的MT5持仓信息。假设当前时间是2024-02-01 00:00:00，提取:register_time为{'register_start_date': '2024-01-01 00:00:00', 'register_end_date': '2024-02-01 00:00:00'} 。range_time为{'data_start_date': '2024-01-27 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
        ],
    },
    "user_mt5_positions": {
        "name": "MT5持仓记录",
        "description": "用户MT5持仓信息。",
        "fields": {
            "Login": "登录",
            "Position": "位置",
            "Symbol": "符号",
            "Action": "动作",
            "PriceOpen": "打开价格",
            "PriceCurrent": "当前价格",
            "Volume": "数量",
            "PriceSL": "止损价格",
            "ContractSize": "合约大小",
            "Profit": "利润",
            "Storage": "存储",
            "TimeCreate": "创建时间",
        },
        "parameters": [
            {
                "name": "range_time",
                "description": "根据时间范围查询MT5持仓信息。",
                "required": True,
                "data_type": "dict",
                "validator_rules": [
                    "根据当前时间计算有效的时间格式",
                    "data_start_date: 开始日期",
                    "data_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月的MT5持仓信息。假设当前时间是2024-02-01 00:00:00，提取:range_time为{'data_start_date': '2024-01-01 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
            {
                "name": "email",
                "description": "根据客户，员工，代理的邮箱查询MT5持仓信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的邮箱",
                    "没有指明邮箱默认是空",
                ],
                "example_value": "输入：查询邮箱为123456@gmail.com的MT5持仓信息。提取:email为123456@gmail.com",
            },
            {
                "name": "user_id",
                "description": "根据客户，员工，代理的用户ID查询MT5持仓信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户ID",
                    "没有指明用户id默认是空",
                ],
                "example_value": "输入：查询用户ID为123456的MT5持仓信息。提取:user_id为123456",
            },
            {
                "name": "user_name",
                "description": "根据客户，员工，代理的用户名称查询MT5持仓信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户名称",
                    "没有指明用户名称默认是空",
                ],
                "example_value": "输入：查询用户名称为123456的MT5持仓信息。提取:user_name为123456",
            },
            {
                "name": "user_type",
                "description": "根据客户，员工，代理的用户类型查询MT5持仓信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["direct", "agent", "staff"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "direct: 客户",
                    "agent: 代理",
                    "staff: 员工",
                ],
                "example_value": "输入：查询员工名称为张三的MT5持仓信息。提取:user_type为staff",
            },
            {
                "name": "country",
                "description": "根据客户，员工，代理的国家查询MT5持仓信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "必须是有效的国家名称",
                    "如果非标准国家的英语名称，请转换为标准英语国家名称",
                ],
                "example_value": "输入：查询中国用户的MT5持仓信息。提取:country为['china']",
            },
            {
                "name": "kyc",
                "description": "根据客户，员工，代理的kyc查询MT5持仓信息。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["0", "1", "2", "3", "4", "5", "9", "-1"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "0: 未KYC",
                    "1: 问卷调查",
                    "2: 基础信息",
                    "3: 上传证件",
                    "4: 签署合同",
                    "5: 上传住址证明",
                    "9: KYC成功",
                    "-1: KYC失败",
                ],
                "example_value": "输入：查询kyc为'问卷调查'的MT5持仓信息。提取:kyc为1",
            },
            {
                "name": "register_time",
                "description": "根据客户，员工，代理的用户注册时间查询MT5持仓信息。",
                "required": False,
                "data_type": "dict",
                "validator_rules": [
                    "指的是用户的注册时间，包括客户注册时间，员工注册时间，代理注册时间。不要与数据查询时间混淆",
                    "根据当前时间计算有效的时间格式",
                    "register_start_date: 开始日期",
                    "register_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月前注册的客户5天前的MT5持仓信息。假设当前时间是2024-02-01 00:00:00，提取:register_time为{'register_start_date': '2024-01-01 00:00:00', 'register_end_date': '2024-02-01 00:00:00'} 。range_time为{'data_start_date': '2024-01-27 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
        ],
    },
    "user_op_log": {
        "name": "操作日志",
        "description": "用户操作日志。包括员工和客户操作日志",
        "fields": {
            "id": "ID",
            "member_id": "会员ID",
            "method": "方法",
            "nickname": "昵称",
            "created_at": "创建时间",
            "ip": "IP",
            "ip_country": "IP国家",
            "ip_province": "IP省份",
            "device_name": "设备名称",
            "browser_name": "浏览器名称",
            "client_type": "客户端类型",
        },
        "parameters": [
            {
                "name": "range_time",
                "description": "根据时间范围查询操作日志。",
                "required": True,
                "data_type": "dict",
                "validator_rules": [
                    "根据当前时间计算有效的时间格式",
                    "data_start_date: 开始日期",
                    "data_end_date: 结束日期",
                ],
                "example_value": "输入：查询今天的操作日志。假设当前时间是2024-02-01 00:23:00，提取:range_time为{'data_start_date': '2024-02-01 00:00:00', 'data_end_date': '2024-02-01 00:23:00'}",
            },
            {
                "name": "user_id",
                "description": "根据客户，员工，代理的用户ID查询操作日志。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户ID",
                    "没有指明用户id默认是空",
                ],
                "example_value": "输入：查询用户ID为123456的操作日志。提取:user_id为123456",
            },
            {
                "name": "user_name",
                "description": "根据客户，员工，代理的用户名称查询操作日志。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的用户名称",
                    "没有指明用户名称默认是空",
                ],
                "example_value": "输入：查询用户名称为123456的操作日志。提取:user_name为123456",
            },
            {
                "name": "email",
                "description": "根据客户，员工，代理的邮箱查询操作日志。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "客户，员工，代理的邮箱",
                    "没有指明邮箱默认是空",
                ],
                "example_value": "输入：查询邮箱为123456@gmail.com的操作日志。提取:email为123456@gmail.com",
            },
            {
                "name": "user_type",
                "description": "根据客户，员工，代理的用户类型查询操作日志。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["direct", "agent", "staff"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "direct: 客户",
                    "agent: 代理",
                    "staff: 员工",
                ],
                "example_value": "输入：查询员工名称为张三的操作日志。提取:user_type为staff",
            },
            {
                "name": "country",
                "description": "根据客户，员工，代理的国家查询操作日志。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "必须是有效的国家名称",
                    "如果非标准国家的英语名称，请转换为标准英语国家名称",
                ],
                "example_value": "输入：查询中国用户的操作日志。提取:country为['china']",
            },
            {
                "name": "kyc",
                "description": "根据客户，员工，代理的kyc查询操作日志。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["0", "1", "2", "3", "4", "5", "9", "-1"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "0: 未KYC",
                    "1: 问卷调查",
                    "2: 基础信息",
                    "3: 上传证件",
                    "4: 签署合同",
                    "5: 上传住址证明",
                    "9: KYC成功",
                    "-1: KYC失败",
                ],
                "example_value": "输入：查询kyc为'问卷调查'的操作日志。提取:kyc为1",
            },
            {
                "name": "register_time",
                "description": "根据客户，员工，代理的用户注册时间查询操作日志。",
                "required": False,
                "data_type": "dict",
                "validator_rules": [
                    "指的是用户的注册时间，包括客户注册时间，员工注册时间，代理注册时间。不要与数据查询时间混淆",
                    "根据当前时间计算有效的时间格式",
                    "register_start_date: 开始日期",
                    "register_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月前注册的客户5天前的操作日志。假设当前时间是2024-02-01 00:00:00，提取:register_time为{'register_start_date': '2024-01-01 00:00:00', 'register_end_date': '2024-02-01 00:00:00'} 。range_time为{'data_start_date': '2024-01-27 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
        ],
    },
    "direct_staff_statistics": {
        "name": "客户或员工的用户统计",
        "description": "客户或员工用户的入金用户数，出金用户数，入金金额，出金金额, 登录用户数, 登录次数等统计数据",
        "fields": {
            "deposit_accounts": "入金用户数",
            "withdrawal_accounts": "出金用户数",
            "deposit_amount": "入金金额",
            "withdrawal_amount": "出金金额",
            "login_accounts": "登录用户数",
            "login_count": "登录次数",
        },
        "parameters": [
            {
                "name": "statistics_name",
                "description": "统计类型名称。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "必须是以下预定义值,可以多个",
                    "deposit_accounts: 入金用户数",
                    "withdrawal_accounts: 出金用户数",
                    "deposit_amount: 入金金额",
                    "withdrawal_amount: 出金金额",
                    "login_accounts: 登录用户数",
                    "login_count: 登录次数",
                ],
                "example_value": "输入：查询入金用户数和出金用户数。提取:statistics_name为['deposit_accounts', 'withdrawal_accounts']",
            },
            {
                "name": "range_time",
                "description": "根据时间范围查询统计数据。",
                "required": False,
                "data_type": "dict",
                "validator_rules": [
                    "根据当前时间计算有效的时间格式",
                    "data_start_date: 开始日期",
                    "data_end_date: 结束日期",
                ],
                "example_value": "输入：查询今天的入金金额。假设当前时间是2024-02-01 00:23:00，提取:range_time为{'data_start_date': '2024-02-01 00:00:00', 'data_end_date': '2024-02-01 00:23:00'}",
            },
            {
                "name": "country",
                "description": "根据国家查询统计数据。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "必须是有效的国家名称",
                    "如果非标准国家的英语名称，请转换为标准英语国家名称",
                ],
                "example_value": "输入：查询中国用户的出金金额。提取:country为['china']",
            },
            {
                "name": "kyc",
                "description": "根据kyc查询统计数据。",
                "required": False,
                "data_type": "enum",
                "enum_values": ["0", "1", "2", "3", "4", "5", "9", "-1"],
                "validator_rules": [
                    "必须是以下预定义值之一",
                    "0: 未KYC",
                    "1: 问卷调查",
                    "2: 基础信息",
                    "3: 上传证件",
                    "4: 签署合同",
                    "5: 上传住址证明",
                    "9: KYC成功",
                    "-1: KYC失败",
                ],
                "example_value": "输入：查询kyc为'问卷调查'的出金金额。提取:kyc为1",
            },
            {
                "name": "register_time",
                "description": "根据客户，员工的用户注册时间查询统计数据。",
                "required": False,
                "data_type": "dict",
                "validator_rules": [
                    "指的是用户的注册时间，包括客户注册时间，员工注册时间。不要与数据查询时间混淆",
                    "根据当前时间计算有效的时间格式",
                    "register_start_date: 开始日期",
                    "register_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月前注册的客户5天前的出金金额。假设当前时间是2024-02-01 00:00:00，提取:register_time为{'register_start_date': '2024-01-01 00:00:00', 'register_end_date': '2024-02-01 00:00:00'} 。range_time为{'data_start_date': '2024-01-27 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
        ],
    },
    "agent_statistics": {
        "name": "代理用户的统计",
        "description": "代理用户的客户数统计，入金统计，出金统计，返佣统计，交易统计(百万交易量)，交易统计(利润)，交易统计(交易数量)",
        "fields": {
            "customer_count": "客户数",
            "total_deposit_usd": "入金金额",
            "total_withdrawal_usd": "出金金额",
            "total_rebate_usd": "返佣金额",
            "total_trading_volume_usd": "交易统计(百万交易量)",
            "total_trading_profit_usd": "交易统计(利润)",
            "total_trades": "交易统计(交易数量)",
        },
        "parameters": [
            {
                "name": "statistics_name",
                "description": "统计名称。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "必须是以下预定义值,可以多个",
                    "customer_count: 客户数",
                    "total_deposit_usd: 入金金额",
                    "total_withdrawal_usd: 出金金额",
                    "total_rebate_usd: 返佣金额",
                    "total_trading_volume_usd: 交易统计(百万交易量)",
                    "total_trading_profit_usd: 交易统计(利润)",
                    "total_trades: 交易统计(交易数量)",
                ],
                "example_value": "输入：查询'小王'代理的客户数，入金金额，出金金额。提取:statistics_name为['customer_count', 'total_deposit_usd', 'total_withdrawal_usd', 'total_rebate_usd']",
            },
            {
                "name": "range_time",
                "description": "根据时间范围查询统计数据。",
                "required": False,
                "data_type": "dict",
                "validator_rules": [
                    "根据当前时间计算有效的时间格式",
                    "data_start_date: 开始日期",
                    "data_end_date: 结束日期",
                ],
                "example_value": "输入：查询今天'小王'代理的统计数据。假设当前时间是2024-02-01 00:23:00，提取:range_time为{'data_start_date': '2024-02-01 00:00:00', 'data_end_date': '2024-02-01 00:23:00'}",
            },
            {
                "name": "user_id",
                "description": "根据代理的用户ID查询用户基本信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "代理的用户ID",
                    "没有指明用户id默认是空",
                ],
                "example_value": "输入：查询代理ID为123456的用户基本信息。提取:user_id为123456",
            },
            {
                "name": "user_name",
                "description": "根据代理的用户名称查询用户基本信息。",
                "required": True,
                "data_type": "list",
                "validator_rules": [
                    "代理的用户名称",
                    "没有指明用户名称默认是空",
                ],
                "example_value": "输入：查询代理名称为123456的用户基本信息。提取:user_name为123456",
            },
            {
                "name": "email",
                "description": "根据代理的邮箱查询用户基本信息。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "代理的邮箱",
                    "没有指明邮箱默认是空",
                ],
                "example_value": "输入：查询代理邮箱为123456@gmail.com的用户基本信息。提取:email为123456@gmail.com",
            },
            {
                "name": "country",
                "description": "根据代理的国家查询统计数据。",
                "required": False,
                "data_type": "list",
                "validator_rules": [
                    "必须是有效的国家名称",
                    "如果非标准国家的英语名称，请转换为标准英语国家名称",
                ],
                "example_value": "输入：查询中国用户的出金金额。提取:country为['china']",
            },
            {
                "name": "register_time",
                "description": "根据代理的用户注册时间查询统计数据。",
                "required": False,
                "data_type": "dict",
                "validator_rules": [
                    "指的是代理的用户注册时间，包括不要与数据查询时间混淆",
                    "根据当前时间计算有效的时间格式",
                    "register_start_date: 开始日期",
                    "register_end_date: 结束日期",
                ],
                "example_value": "输入：查询一个月前注册的代理5天前的出金金额。假设当前时间是2024-02-01 00:00:00，提取:register_time为{'register_start_date': '2024-01-01 00:00:00', 'register_end_date': '2024-02-01 00:00:00'} 。range_time为{'data_start_date': '2024-01-27 00:00:00', 'data_end_date': '2024-02-01 00:00:00'}",
            },
        ],
    },
    "tool_foreign_exchange_market_data": {
        "name": "外汇行情数据",
        "description": "查询分析外汇行情数据",
        "fields": {
            "MT_DATE": "MT时间",
            "OPEN": "开盘价",
            "HIGH": "最高价",
            "LOW": "最低价",
            "CLOSE": "收盘价",
            "VOLUME": "成交量",
        },
        "parameters": [
            {
                "name": "code",
                "description": "根据代码查询外汇行情数据。",
                "required": True,
                "data_type": "list",
                "validator_rules": [
                    "必须是有效的代码,下面是预定义值之一",
                    "USDCNY",
                    "USDILS",
                    "USDNOK",
                    "USDPLN",
                    "XAUUSD_LT",
                    "EURUSD",
                    "NZDUSD",
                    "XAGUSD",
                    "BRNUSD",
                    "WTIUSD",
                    "NGCUSD",
                    "USOUSD",
                    "XPTUSD",
                    "ATOMUSDT",
                    "BATUSDT",
                    "BTCUSDT",
                    "DASHUSDT",
                    "DOGEUSDT",
                    "ETHUSDT",
                    "FILUSDT",
                    "TRXUSDT",
                    "XRPUSD",
                    "BCHUSD",
                    "EOSUSD",
                    "ADAUSD",
                    "ATOMUSD",
                    "BATUSD",
                    "DASHUSD",
                    "TRXUSD",
                    "XLMUSD",
                    "XMRUSD",
                    "ZECUSD",
                    "AUDCAD",
                    "CADJPY",
                    "EURUSD_cc",
                    "USDCHF",
                    "USDHKD",
                    "AAL",
                    "ALIBABA",
                    "AUS200c",
                    "COTTONZ4",
                    "GER40c",
                    "CADCHF",
                    "ADS",
                    "FRA40c",
                    "EURCNH",
                    "EURZAR",
                    "USDUSC",
                    "EURCAD",
                    "NZDCHF",
                    "NZDJPY",
                    "AF",
                    "ALV",
                    "AUDDKK",
                    "AUDHUF",
                    "AUDNOK",
                    "AUDSEK",
                    "USOILRoll",
                    "H",
                    "US30c",
                    "USTECHc",
                    "BN",
                    "CS",
                    "FRA40N4",
                    "GER40M4",
                    "GLEN",
                    "GSK",
                    "INTC",
                    "ITALY40U4",
                    "JPMORGAN",
                    "JPN225H24",
                    "MCD",
                    "MSTRCARD",
                    "Makita",
                    "MitsubisUFJ",
                    "NDAQ",
                    "NESN",
                    "NET",
                    "NETFLIX",
                    "NETHM4",
                    "NETHN24",
                    "NVDA",
                    "Nissan",
                    "ORCL",
                    "PEP",
                    "PG",
                    "PLBY",
                    "RIO",
                    "SPA35N4",
                    "SWI20c",
                    "SWITZ20U4",
                    "Softbank",
                    "T",
                    "UK100U4",
                    "UNH",
                    "US2000M24",
                    "US2000U24",
                    "US2000c",
                    "US500M24",
                    "US500U24",
                    "VISA",
                    "EURUSD_xXx",
                    "GBPCZK",
                    "GBPDKK",
                    "GBPMXN",
                    "GBPNOK",
                    "GBPZAR",
                    "HKDJPY",
                    "NOKJPY",
                    "ZARJPY",
                    "NZDSEK",
                    "SEKJPY",
                    "SGDJPY",
                    "BTCUSDT_",
                    "SILVERU24",
                    "APPLE",
                    "UKOILU4",
                    "COFFEEU4",
                    "SILVERN24",
                    "GOLDZ24",
                    "AMAZON",
                    "BOEING",
                    "EURUSD_x",
                    "C",
                    "CAT",
                    "AIA",
                    "BATS",
                    "BAYN",
                    "BMW",
                    "AUS200U4",
                    "CHFJPY",
                    "GBPJPY",
                    "CITIC",
                    "CNOOC",
                    "Canon",
                    "USDMXN",
                    "FNKO",
                    "GOLDMANS",
                    "DISNEY",
                    "F",
                    "WALMART",
                    "EBAY",
                    "GBPCHF",
                    "AUDSGD",
                    "AUDZAR",
                    "CADMXN",
                    "NATGASK4",
                    "UKOILK4",
                    "UKOILM4",
                    "USOILJ24",
                    "USOILM4",
                    "USOILN24",
                    "IT40c",
                    "SILVERK24",
                    "COCOAUKH4",
                    "DKKSEK",
                    "COFFEEN4",
                    "COTTONK4",
                    "DJ30H24",
                    "EURDKK",
                    "EURHKD",
                    "EURHUF",
                    "EURMXN",
                    "EURNOK",
                    "EURPLN",
                    "EURSEK",
                    "USDCZK",
                    "USDDKK",
                    "USDHUF",
                    "USDSEK",
                    "USDSGD",
                    "USDTHB",
                    "USDTRY",
                    "GOLDJ24",
                    "GOLDM24",
                    "GOLDQ24",
                    "AUDUSD",
                    "GBPUSD",
                    "XAUUSD",
                    "ETHUSD",
                    "LTCUSD",
                    "UKOUSD",
                    "CUCUSD",
                    "XPDUSD",
                    "ADAUSDT",
                    "BCHUSDT",
                    "EOSUSDT",
                    "LTCUSDT",
                    "USDUSDT",
                    "XLMUSDT",
                    "XMRUSDT",
                    "XRPUSDT",
                    "ZECUSDT",
                    "TRUMPUSDT",
                    "BTCUSD",
                    "FILUSD",
                    "DOGEUSD",
                    "AUDCHF",
                    "AUDJPY",
                    "BTCUSD_MEX",
                    "EURGBP",
                    "USDCAD",
                    "USDJPY",
                    "3M",
                    "A",
                    "AIG",
                    "CN50c",
                    "COCOAU4",
                    "EU50c",
                    "HK50c",
                    "AUDNZD",
                    "EURAUD",
                    "GBPAUD",
                    "CNHJPY",
                    "USDCNH",
                    "USDZAR",
                    "GBPCAD",
                    "NZDCAD",
                    "AI",
                    "AIR",
                    "AUDUSD_c",
                    "HPQ",
                    "IBM",
                    "ING",
                    "UK100c",
                    "US500c",
                    "BNP",
                    "DGE",
                    "DTE",
                    "GER40U4",
                    "HK50N4",
                    "HKBankChina",
                    "HOME-DEP",
                    "HSBC",
                    "Henderson",
                    "IBE",
                    "ITALY40M4",
                    "Ind&ComBank",
                    "JAPU24",
                    "JNJ",
                    "JpnTobacco",
                    "KDDI",
                    "LHA",
                    "Lenovo",
                    "MAR",
                    "MAT",
                    "MBG",
                    "MC",
                    "MICROSOFT",
                    "MRK",
                    "Mitsui",
                    "Mizuho",
                    "NIKE",
                    "NOVN",
                    "OR",
                    "PAYPAL",
                    "PICC",
                    "ROG",
                    "SAP",
                    "SHEL",
                    "SHK",
                    "SIE",
                    "SPA35M4",
                    "SWITZ20M4",
                    "Seven&I",
                    "ShenhuaEnrg",
                    "Sony",
                    "Sumitomo",
                    "TESLA",
                    "Toyota",
                    "UAL",
                    "UK100M4",
                    "ULVR",
                    "US100M24",
                    "US100U24",
                    "US30M24",
                    "US30U24",
                    "VERIZON",
                    "VOD",
                    "VOW3",
                    "Xiaomi",
                    "EURUSD_xX",
                    "EURUSD_xXxx",
                    "JPN225c",
                    "ChinaMobile",
                    "SPA35c",
                    "EURTRY",
                    "GBPHKD",
                    "GBPHUF",
                    "USWHEATK24",
                    "GBPPLN",
                    "GBPSEK",
                    "GBPSGD",
                    "GBPTRY",
                    "MXNJPY",
                    "NOKSEK",
                    "NZDDKK",
                    "NZDHUF",
                    "USTECH24",
                    "NZDNOK",
                    "NZDSGD",
                    "SGDHKD",
                    "TRYJPY",
                    "EURUSD_",
                    "NATGASQ4",
                    "USOILQ24",
                    "COCOAN4",
                    "COFFEEARBK4",
                    "BAIDU",
                    "BNK-AMER",
                    "Keyence",
                    "Tencent",
                    "CISCO",
                    "COCA-COLA",
                    "CVX",
                    "AUS200M4",
                    "BAS",
                    "EURCHF",
                    "EUR50M4",
                    "EUR50U4",
                    "EURJPY",
                    "CKHutchison",
                    "FACEBOOK",
                    "FDX",
                    "GOOGL",
                    "EXXON",
                    "WFC",
                    "DLPN",
                    "WKHS",
                    "EURNZD",
                    "GBPNZD",
                    "CADDKK",
                    "CADNOK",
                    "CADSEK",
                    "CADSGD",
                    "CHFDKK",
                    "CHFHUF",
                    "CHFNOK",
                    "CHFPLN",
                    "NATGASM4",
                    "NGASJ24",
                    "UKOILN4",
                    "NETH25c",
                    "COCOAK4",
                    "CHFSEK",
                    "CHFSGD",
                    "CHFZAR",
                    "DKKNOK",
                    "COCOAUSH4",
                    "COFFEEK4",
                    "COFFEEROBH4",
                    "DE40H24",
                    "DXH24",
                    "EURCZK",
                    "EURILS",
                    "EURSGD",
                ],
                "example_value": "输入：帮我分析黄金的行情数据。提取:code为['XAUUSD']",
            },
            {
                "name": "days",
                "description": "根据天数查询外汇行情数据。",
                "required": False,
                "data_type": "int",
                "validator_rules": [
                    "必须是有效的天数",
                ],
                "example_value": "输入：帮我分析今天黄金的行情数据。提取:days为1",
            },
            {
                "name": "period",
                "description": "根据周期分钟查询外汇行情数据。",
                "required": False,
                "data_type": "int",
                "validator_rules": [
                    "必须是有效的周期",
                ],
                "example_value": "输入：帮我分析黄金的15分钟行情数据。提取:period为15",
            },
        ],
    },
}


def get_intent_patterns_prompt():
    intent_patterns = ""
    for intent_type, config in INTENT_PATTERNS.items():
        name = config["name"]
        description = config["description"]
        intent_patterns += f"{intent_type}:\n-名称：{name}\n-描述：{description}\n"
    return intent_patterns


def get_data_sources_prompt(data_sources: list = None):
    prompt = ""
    for intent_type, config in INTENT_PATTERNS.items():
        if data_sources:
            if intent_type in data_sources:
                prompt += f"{intent_type}:\n-名称：{config['name']}\n-描述：{config['description']}\n参数：{config['parameters']}\n"
        else:
            prompt += f"{intent_type}:\n-名称：{config['name']}\n-描述：{config['description']}\n"
    return prompt


def get_intent_description():
    description = []
    for intent_type, config in INTENT_PATTERNS.items():
        description.append(f"{intent_type}：{config['description']}")
    return description


def get_intent_names(query_types: list = []):
    name = []
    for intent_type, config in INTENT_PATTERNS.items():
        if query_types:
            if intent_type in query_types:
                name.append(config["name"])
        else:
            name.append(config["name"])
    return name


def get_intent_types():
    types = []
    for intent_type, config in INTENT_PATTERNS.items():
        types.append(intent_type)
    return types


def get_namme_by_key(key: str):
    for intent_type, config in INTENT_PATTERNS.items():
        if intent_type == key:
            return config["name"]
    return key
