"""Change ai_subscription_notification_methods id from string to integer

Revision ID: 8ff9b1f5f820
Revises: 5ba3ec2c0950
Create Date: 2025-09-05 21:07:51.953457

"""

from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = "8ff9b1f5f820"
down_revision = "5ba3ec2c0950"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    conn = op.get_bind()

    # 首先删除外键约束，以便能够修改字段类型
    conn.execute(
        text(
            "ALTER TABLE ai_subscription_notifications DROP CONSTRAINT IF EXISTS ai_subscription_notifications_notification_id_fkey"
        )
    )

    # 先修改主表的id字段类型
    conn.execute(
        text("ALTER TABLE ai_subscription_notification_methods ALTER COLUMN id TYPE INTEGER USING id::integer")
    )

    # 再修改外键表的notification_id字段类型
    conn.execute(
        text(
            "ALTER TABLE ai_subscription_notifications ALTER COLUMN notification_id TYPE INTEGER USING notification_id::integer"
        )
    )

    # 重新创建外键约束
    conn.execute(
        text(
            "ALTER TABLE ai_subscription_notifications ADD CONSTRAINT ai_subscription_notifications_notification_id_fkey "
            "FOREIGN KEY (notification_id) REFERENCES ai_subscription_notification_methods(id) ON DELETE CASCADE"
        )
    )

    # 插入两条初始数据
    conn.execute(
        text("""
        INSERT INTO ai_subscription_notification_methods (id, name, type, config, status, created_time, updated_time)
        VALUES
        (1, '邮件通知', 'email', NULL, true, '2025-09-05T13:01:37.494Z', '2025-09-05T13:01:37.494Z'),
        (2, 'Webhook通知', 'webhook', NULL, true, '2025-09-05T13:01:37.494Z', '2025-09-05T13:01:37.494Z')
        ON CONFLICT (id) DO NOTHING
    """)
    )

    # 修改索引
    with op.batch_alter_table("ai_subscription_notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_subscription_notifications_subscription_id"))
        batch_op.create_index(
            batch_op.f("ix_ai_subscription_notifications_subscription_id"), ["subscription_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    # 删除外键约束
    conn.execute(
        text(
            "ALTER TABLE ai_subscription_notifications DROP CONSTRAINT IF EXISTS ai_subscription_notifications_notification_id_fkey"
        )
    )

    # 恢复字段类型
    conn.execute(
        text(
            "ALTER TABLE ai_subscription_notifications ALTER COLUMN notification_id TYPE VARCHAR(50) USING notification_id::varchar"
        )
    )

    conn.execute(
        text("ALTER TABLE ai_subscription_notification_methods ALTER COLUMN id TYPE VARCHAR(50) USING id::varchar")
    )

    # 重新创建外键约束
    conn.execute(
        text(
            "ALTER TABLE ai_subscription_notifications ADD CONSTRAINT ai_subscription_notifications_notification_id_fkey "
            "FOREIGN KEY (notification_id) REFERENCES ai_subscription_notification_methods(id) ON DELETE CASCADE"
        )
    )

    with op.batch_alter_table("ai_subscription_notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_subscription_notifications_subscription_id"))
        batch_op.create_index(
            batch_op.f("ix_ai_subscription_notifications_subscription_id"), ["subscription_id"], unique=False
        )

    # ### end Alembic commands ###
