"""add_description_field_to_risk_report_log

Revision ID: 4b6a903f1974
Revises: 291f4bc06a93
Create Date: 2025-11-06 15:49:45.329949

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4b6a903f1974"
down_revision = "291f4bc06a93"
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """检查约束是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 检查外键约束
    fks = [fk["name"] for fk in inspector.get_foreign_keys(table_name) if fk["name"]]
    if constraint_name in fks:
        return True

    # 检查唯一约束
    uqs = [uq["name"] for uq in inspector.get_unique_constraints(table_name) if uq["name"]]
    if constraint_name in uqs:
        return True

    # 检查检查约束
    checks = [ck["name"] for ck in inspector.get_check_constraints(table_name) if ck["name"]]
    return constraint_name in checks


def _table_exists(table_name: str) -> bool:
    """检查表是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    if not _table_exists(table_name):
        return False
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查并添加 description 列
    if not _column_exists("risk_report_log", "description"):
        with op.batch_alter_table("risk_report_log", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column("description", sa.Text(), nullable=True, comment="风险描述，支持外部系统展示")
            )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查列是否存在，如果存在才删除
    if _column_exists("risk_report_log", "description"):
        with op.batch_alter_table("risk_report_log", schema=None) as batch_op:
            batch_op.drop_column("description")
    # ### end Alembic commands ###
