"""add_crm_user_id_to_user_table

Revision ID: f5daf82786b4
Revises: a1b235675d4
Create Date: 2025-10-15 10:12:12.319033

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f5daf82786b4"
down_revision = "a1b235675d4"
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """检查约束是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 检查外键约束
    fks = [fk["name"] for fk in inspector.get_foreign_keys(table_name) if fk["name"]]
    if constraint_name in fks:
        return True

    # 检查唯一约束
    uqs = [uq["name"] for uq in inspector.get_unique_constraints(table_name) if uq["name"]]
    if constraint_name in uqs:
        return True

    # 检查检查约束
    checks = [ck["name"] for ck in inspector.get_check_constraints(table_name) if ck["name"]]
    return constraint_name in checks


def _table_exists(table_name: str) -> bool:
    """检查表是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    if not _table_exists(table_name):
        return False
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_chat", schema=None) as batch_op:
        batch_op.alter_column(
            "history_summary",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_comment="历史对话压缩摘要，用于减少token消耗",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "summary_time",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            type_=sa.DateTime(),
            existing_comment="摘要生成时间",
            existing_nullable=True,
        )

    with op.batch_alter_table("sys_user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("crm_user_id", sa.String(length=50), nullable=True, comment="CRM系统用户ID"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sys_user", schema=None) as batch_op:
        batch_op.drop_column("crm_user_id")

    with op.batch_alter_table("ai_chat", schema=None) as batch_op:
        batch_op.alter_column(
            "summary_time",
            existing_type=sa.DateTime(),
            type_=postgresql.TIMESTAMP(timezone=True),
            existing_comment="摘要生成时间",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "history_summary",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_comment="历史对话压缩摘要，用于减少token消耗",
            existing_nullable=True,
        )

    # ### end Alembic commands ###
