"""remove monitor_task_id from task_scheduler_execution

Revision ID: 2a15da5d7955
Revises: d89873657678
Create Date: 2025-09-02 16:41:56.606287

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2a15da5d7955"
down_revision = "d89873657678"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_scheduler_execution", "monitor_task_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_scheduler_execution",
        sa.Column("monitor_task_id", sa.VARCHAR(length=155), autoincrement=False, nullable=True, comment="监控任务ID"),
    )
    # ### end Alembic commands ###
