"""check for model changes

Revision ID: d89873657678
Revises: d50b07ca4a17
Create Date: 2025-09-01 22:08:36.797569

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d89873657678"
down_revision = "d50b07ca4a17"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ai_database_metadata",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    try:
        op.drop_index(op.f("ix_ai_database_metadata_id"), table_name="ai_database_metadata")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_ai_database_metadata_id"), "ai_database_metadata", ["id"], unique=True)
    op.alter_column(
        "ai_subscription",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="订阅ID",
        existing_nullable=False,
        autoincrement=True,
    )
    try:
        op.drop_index(op.f("ix_ai_subscription_id"), table_name="ai_subscription")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_ai_subscription_id"), "ai_subscription", ["id"], unique=True)
    op.alter_column(
        "ai_subscription_notifications",
        "subscription_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="订阅ID",
        existing_nullable=False,
        autoincrement=True,
    )
    try:
        op.drop_index(
            op.f("ix_ai_subscription_notifications_subscription_id"), table_name="ai_subscription_notifications"
        )
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(
        op.f("ix_ai_subscription_notifications_subscription_id"),
        "ai_subscription_notifications",
        ["subscription_id"],
        unique=True,
    )
    op.alter_column(
        "ai_training_logs",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    try:
        op.drop_index(op.f("ix_ai_training_logs_id"), table_name="ai_training_logs")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_ai_training_logs_id"), "ai_training_logs", ["id"], unique=True)
    op.alter_column(
        "gen_business",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('gen_business_id_seq'::regclass)"),
    )
    try:
        op.drop_index(op.f("ix_gen_business_id"), table_name="gen_business")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_gen_business_id"), "gen_business", ["id"], unique=True)
    op.alter_column(
        "gen_column",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "gen_column",
        "gen_business_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="代码生成业务ID",
        existing_nullable=False,
    )
    try:
        op.drop_index(op.f("ix_gen_column_id"), table_name="gen_column")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_gen_column_id"), "gen_column", ["id"], unique=True)
    op.alter_column(
        "sys_config",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    try:
        op.drop_index(op.f("ix_sys_config_id"), table_name="sys_config")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_sys_config_id"), "sys_config", ["id"], unique=True)
    op.alter_column(
        "sys_data_rule",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    try:
        op.drop_index(op.f("ix_sys_data_rule_id"), table_name="sys_data_rule")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_sys_data_rule_id"), "sys_data_rule", ["id"], unique=True)
    op.drop_constraint(op.f("sys_data_rule_scope_id_fkey"), "sys_data_rule", type_="foreignkey")
    op.drop_column("sys_data_rule", "scope_id")
    op.alter_column(
        "sys_data_scope",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('sys_data_scope_id_seq'::regclass)"),
    )
    try:
        op.drop_index(op.f("ix_sys_data_scope_id"), table_name="sys_data_scope")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_sys_data_scope_id"), "sys_data_scope", ["id"], unique=True)
    op.alter_column(
        "sys_dept",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('sys_dept_id_seq'::regclass)"),
    )
    op.alter_column(
        "sys_dept",
        "parent_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="父部门ID",
        existing_nullable=True,
    )
    try:
        op.drop_index(op.f("ix_sys_dept_id"), table_name="sys_dept")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_sys_dept_id"), "sys_dept", ["id"], unique=True)
    op.add_column(
        "sys_dict_data", sa.Column("type_code", sa.String(length=32), nullable=False, comment="对应的字典类型编码")
    )
    op.alter_column(
        "sys_dict_data",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "sys_dict_data",
        "type_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="字典类型关联ID",
        existing_nullable=False,
    )
    op.drop_constraint(op.f("sys_dict_data_label_key"), "sys_dict_data", type_="unique")
    try:
        op.drop_index(op.f("ix_sys_dict_data_id"), table_name="sys_dict_data")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_sys_dict_data_id"), "sys_dict_data", ["id"], unique=True)
    op.alter_column(
        "sys_dict_type",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    try:
        op.drop_index(op.f("ix_sys_dict_type_id"), table_name="sys_dict_type")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_sys_dict_type_id"), "sys_dict_type", ["id"], unique=True)
    op.alter_column(
        "sys_login_log",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    try:
        op.drop_index(op.f("ix_sys_login_log_id"), table_name="sys_login_log")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_sys_login_log_id"), "sys_login_log", ["id"], unique=True)
    op.alter_column(
        "sys_menu",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "sys_menu", "title", existing_type=sa.VARCHAR(length=50), comment="菜单标题", existing_nullable=False
    )
    op.alter_column(
        "sys_menu", "name", existing_type=sa.VARCHAR(length=50), comment="菜单名称", existing_nullable=False
    )
    op.alter_column(
        "sys_menu", "path", existing_type=sa.VARCHAR(length=200), comment="路由地址", existing_nullable=True
    )
    op.alter_column("sys_menu", "sort", existing_type=sa.INTEGER(), comment="排序", existing_nullable=False)
    op.alter_column(
        "sys_menu", "icon", existing_type=sa.VARCHAR(length=100), comment="菜单图标", existing_nullable=True
    )
    op.alter_column(
        "sys_menu",
        "type",
        existing_type=sa.INTEGER(),
        comment="菜单类型（0目录 1菜单 2按钮 3内嵌 4外链）",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_menu", "component", existing_type=sa.VARCHAR(length=255), comment="组件路径", existing_nullable=True
    )
    op.alter_column(
        "sys_menu", "perms", existing_type=sa.VARCHAR(length=100), comment="权限标识", existing_nullable=True
    )
    op.alter_column(
        "sys_menu", "status", existing_type=sa.INTEGER(), comment="菜单状态（0停用 1正常）", existing_nullable=False
    )
    op.alter_column(
        "sys_menu", "display", existing_type=sa.INTEGER(), comment="是否显示（0否 1是）", existing_nullable=False
    )
    op.alter_column(
        "sys_menu", "cache", existing_type=sa.INTEGER(), comment="是否缓存（0否 1是）", existing_nullable=False
    )
    op.alter_column("sys_menu", "link", existing_type=sa.TEXT(), comment="外链地址", existing_nullable=True)
    op.alter_column("sys_menu", "remark", existing_type=sa.TEXT(), comment="备注", existing_nullable=True)
    op.alter_column(
        "sys_menu",
        "parent_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        comment="父菜单ID",
        existing_nullable=True,
    )
    op.alter_column(
        "sys_menu",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_menu",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="更新时间",
        existing_nullable=True,
    )
    # 先删除可能存在的索引，然后重新创建
    try:
        op.drop_index(op.f("ix_sys_menu_id"), table_name="sys_menu")
    except Exception:
        pass  # 索引不存在时忽略错误
    try:
        op.drop_index(op.f("ix_sys_menu_parent_id"), table_name="sys_menu")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_sys_menu_id"), "sys_menu", ["id"], unique=True)
    op.create_index(op.f("ix_sys_menu_parent_id"), "sys_menu", ["parent_id"], unique=False)
    op.create_foreign_key(None, "sys_menu", "sys_menu", ["parent_id"], ["id"], ondelete="SET NULL")
    op.create_table_comment("sys_menu", "菜单表", existing_comment=None, schema=None)
    op.alter_column(
        "sys_notice",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    try:
        op.drop_index(op.f("ix_sys_notice_id"), table_name="sys_notice")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_sys_notice_id"), "sys_notice", ["id"], unique=True)
    op.alter_column(
        "sys_opera_log",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    try:
        op.drop_index(op.f("ix_sys_opera_log_id"), table_name="sys_opera_log")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_sys_opera_log_id"), "sys_opera_log", ["id"], unique=True)
    op.alter_column(
        "sys_role",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('sys_role_id_seq'::regclass)"),
    )
    try:
        op.drop_index(op.f("ix_sys_role_id"), table_name="sys_role")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_sys_role_id"), "sys_role", ["id"], unique=True)
    op.alter_column(
        "sys_role_data_scope",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "sys_role_data_scope",
        "role_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="角色 ID",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_role_data_scope",
        "data_scope_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="数据范围 ID",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_role_menu",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "sys_role_menu",
        "role_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="角色ID",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_role_menu",
        "menu_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="菜单ID",
        existing_nullable=False,
    )
    op.create_foreign_key(None, "sys_role_menu", "sys_menu", ["menu_id"], ["id"], ondelete="CASCADE")
    op.alter_column(
        "sys_user",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('sys_user_id_seq'::regclass)"),
    )
    op.alter_column("sys_user", "email", existing_type=sa.VARCHAR(length=50), nullable=True, existing_comment="邮箱")
    op.alter_column(
        "sys_user",
        "dept_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="部门关联ID",
        existing_nullable=True,
    )
    op.drop_constraint(op.f("sys_user_nickname_key"), "sys_user", type_="unique")
    try:
        op.drop_index(op.f("ix_sys_user_id"), table_name="sys_user")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_sys_user_id"), "sys_user", ["id"], unique=True)
    op.alter_column(
        "sys_user_role",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "sys_user_role",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="用户ID",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_user_role",
        "role_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="角色ID",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_user_social",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "sys_user_social",
        "sid",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=255),
        nullable=False,
        existing_comment="第三方用户 ID",
    )
    op.alter_column(
        "sys_user_social",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=False,
        existing_comment="用户关联ID",
    )
    try:
        op.drop_index(op.f("ix_sys_user_social_id"), table_name="sys_user_social")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_sys_user_social_id"), "sys_user_social", ["id"], unique=True)
    op.drop_constraint(op.f("sys_user_social_user_id_fkey"), "sys_user_social", type_="foreignkey")
    op.create_foreign_key(None, "sys_user_social", "sys_user", ["user_id"], ["id"], ondelete="CASCADE")
    op.drop_column("sys_user_social", "code")
    op.drop_column("sys_user_social", "open_id")
    op.drop_column("sys_user_social", "union_id")
    op.drop_column("sys_user_social", "scope")
    op.alter_column(
        "task_scheduler",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "task_scheduler",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="用户ID",
        existing_nullable=True,
    )
    op.alter_column(
        "task_scheduler",
        "subscription_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="订阅ID",
        existing_nullable=True,
    )
    try:
        op.drop_index(op.f("ix_task_scheduler_id"), table_name="task_scheduler")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_task_scheduler_id"), "task_scheduler", ["id"], unique=True)
    op.alter_column(
        "task_scheduler_execution",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "task_scheduler_execution",
        "scheduler_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="任务调度ID",
        existing_nullable=False,
    )
    op.alter_column(
        "task_scheduler_execution",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="执行用户ID",
        existing_nullable=True,
    )
    op.alter_column(
        "task_scheduler_execution",
        "subscription_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="订阅ID",
        existing_nullable=True,
    )
    try:
        op.drop_index(op.f("ix_task_scheduler_execution_id"), table_name="task_scheduler_execution")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.create_index(op.f("ix_task_scheduler_execution_id"), "task_scheduler_execution", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task_scheduler_execution",
        "subscription_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="订阅ID",
        existing_nullable=True,
    )
    op.alter_column(
        "task_scheduler_execution",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="执行用户ID",
        existing_nullable=True,
    )
    op.alter_column(
        "task_scheduler_execution",
        "scheduler_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="任务调度ID",
        existing_nullable=False,
    )
    op.alter_column(
        "task_scheduler_execution",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_task_scheduler_id"), table_name="task_scheduler")
    op.create_index(op.f("ix_task_scheduler_id"), "task_scheduler", ["id"], unique=False)
    op.alter_column(
        "task_scheduler",
        "subscription_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="订阅ID",
        existing_nullable=True,
    )
    op.alter_column(
        "task_scheduler",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="用户ID",
        existing_nullable=True,
    )
    op.alter_column(
        "task_scheduler",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.add_column(
        "sys_user_social",
        sa.Column("scope", sa.VARCHAR(length=120), autoincrement=False, nullable=True, comment="第三方用户授予的权限"),
    )
    op.add_column(
        "sys_user_social",
        sa.Column("union_id", sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment="第三方用户 union id"),
    )
    op.add_column(
        "sys_user_social",
        sa.Column("open_id", sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment="第三方用户 open id"),
    )
    op.add_column(
        "sys_user_social",
        sa.Column("code", sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment="用户的授权 code"),
    )
    op.drop_constraint(None, "sys_user_social", type_="foreignkey")
    op.create_foreign_key(
        op.f("sys_user_social_user_id_fkey"), "sys_user_social", "sys_user", ["user_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_index(op.f("ix_sys_user_social_id"), table_name="sys_user_social")
    op.create_index(op.f("ix_sys_user_social_id"), "sys_user_social", ["id"], unique=False)
    op.alter_column(
        "sys_user_social",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=True,
        existing_comment="用户关联ID",
    )
    op.alter_column(
        "sys_user_social",
        "sid",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=20),
        nullable=True,
        existing_comment="第三方用户 ID",
    )
    op.alter_column(
        "sys_user_social",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "sys_user_role",
        "role_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="角色ID",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_user_role",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="用户ID",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_user_role",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_sys_user_id"), table_name="sys_user")
    op.create_index(op.f("ix_sys_user_id"), "sys_user", ["id"], unique=False)
    op.create_unique_constraint(
        op.f("sys_user_nickname_key"), "sys_user", ["nickname"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "sys_user",
        "dept_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="部门关联ID",
        existing_nullable=True,
    )
    op.alter_column("sys_user", "email", existing_type=sa.VARCHAR(length=50), nullable=False, existing_comment="邮箱")
    op.alter_column(
        "sys_user",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('sys_user_id_seq'::regclass)"),
    )
    op.drop_constraint(None, "sys_role_menu", type_="foreignkey")
    op.alter_column(
        "sys_role_menu",
        "menu_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="菜单ID",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_role_menu",
        "role_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="角色ID",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_role_menu",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "sys_role_data_scope",
        "data_scope_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="数据范围 ID",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_role_data_scope",
        "role_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="角色 ID",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_role_data_scope",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_sys_role_id"), table_name="sys_role")
    op.create_index(op.f("ix_sys_role_id"), "sys_role", ["id"], unique=False)
    op.alter_column(
        "sys_role",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('sys_role_id_seq'::regclass)"),
    )
    op.drop_index(op.f("ix_sys_opera_log_id"), table_name="sys_opera_log")
    op.create_index(op.f("ix_sys_opera_log_id"), "sys_opera_log", ["id"], unique=False)
    op.alter_column(
        "sys_opera_log",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_sys_notice_id"), table_name="sys_notice")
    op.create_index(op.f("ix_sys_notice_id"), "sys_notice", ["id"], unique=False)
    op.alter_column(
        "sys_notice",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_table_comment("sys_menu", existing_comment="菜单表", schema=None)
    op.drop_constraint(None, "sys_menu", type_="foreignkey")
    try:
        op.drop_index(op.f("ix_sys_menu_parent_id"), table_name="sys_menu")
    except Exception:
        pass  # 索引不存在时忽略错误
    try:
        op.drop_index(op.f("ix_sys_menu_id"), table_name="sys_menu")
    except Exception:
        pass  # 索引不存在时忽略错误
    op.alter_column(
        "sys_menu",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "sys_menu",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_menu",
        "parent_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        comment=None,
        existing_comment="父菜单ID",
        existing_nullable=True,
    )
    op.alter_column(
        "sys_menu", "remark", existing_type=sa.TEXT(), comment=None, existing_comment="备注", existing_nullable=True
    )
    op.alter_column(
        "sys_menu", "link", existing_type=sa.TEXT(), comment=None, existing_comment="外链地址", existing_nullable=True
    )
    op.alter_column(
        "sys_menu",
        "cache",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="是否缓存（0否 1是）",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_menu",
        "display",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="是否显示（0否 1是）",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_menu",
        "status",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="菜单状态（0停用 1正常）",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_menu",
        "perms",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="权限标识",
        existing_nullable=True,
    )
    op.alter_column(
        "sys_menu",
        "component",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="组件路径",
        existing_nullable=True,
    )
    op.alter_column(
        "sys_menu",
        "type",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="菜单类型（0目录 1菜单 2按钮 3内嵌 4外链）",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_menu",
        "icon",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="菜单图标",
        existing_nullable=True,
    )
    op.alter_column(
        "sys_menu", "sort", existing_type=sa.INTEGER(), comment=None, existing_comment="排序", existing_nullable=False
    )
    op.alter_column(
        "sys_menu",
        "path",
        existing_type=sa.VARCHAR(length=200),
        comment=None,
        existing_comment="路由地址",
        existing_nullable=True,
    )
    op.alter_column(
        "sys_menu",
        "name",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="菜单名称",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_menu",
        "title",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="菜单标题",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_menu",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        comment=None,
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_sys_login_log_id"), table_name="sys_login_log")
    op.create_index(op.f("ix_sys_login_log_id"), "sys_login_log", ["id"], unique=False)
    op.alter_column(
        "sys_login_log",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_sys_dict_type_id"), table_name="sys_dict_type")
    op.create_index(op.f("ix_sys_dict_type_id"), "sys_dict_type", ["id"], unique=False)
    op.alter_column(
        "sys_dict_type",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_sys_dict_data_id"), table_name="sys_dict_data")
    op.create_index(op.f("ix_sys_dict_data_id"), "sys_dict_data", ["id"], unique=False)
    op.create_unique_constraint(
        op.f("sys_dict_data_label_key"), "sys_dict_data", ["label"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "sys_dict_data",
        "type_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="字典类型关联ID",
        existing_nullable=False,
    )
    op.alter_column(
        "sys_dict_data",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("sys_dict_data", "type_code")
    op.drop_index(op.f("ix_sys_dept_id"), table_name="sys_dept")
    op.create_index(op.f("ix_sys_dept_id"), "sys_dept", ["id"], unique=False)
    op.alter_column(
        "sys_dept",
        "parent_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="父部门ID",
        existing_nullable=True,
    )
    op.alter_column(
        "sys_dept",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('sys_dept_id_seq'::regclass)"),
    )
    op.drop_index(op.f("ix_sys_data_scope_id"), table_name="sys_data_scope")
    op.create_index(op.f("ix_sys_data_scope_id"), "sys_data_scope", ["id"], unique=False)
    op.alter_column(
        "sys_data_scope",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('sys_data_scope_id_seq'::regclass)"),
    )
    op.add_column(
        "sys_data_rule",
        sa.Column("scope_id", sa.INTEGER(), autoincrement=False, nullable=True, comment="数据范围关联 ID"),
    )
    op.create_foreign_key(
        op.f("sys_data_rule_scope_id_fkey"),
        "sys_data_rule",
        "sys_data_scope",
        ["scope_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(op.f("ix_sys_data_rule_id"), table_name="sys_data_rule")
    op.create_index(op.f("ix_sys_data_rule_id"), "sys_data_rule", ["id"], unique=False)
    op.alter_column(
        "sys_data_rule",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_sys_config_id"), table_name="sys_config")
    op.create_index(op.f("ix_sys_config_id"), "sys_config", ["id"], unique=False)
    op.alter_column(
        "sys_config",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_gen_column_id"), table_name="gen_column")
    op.create_index(op.f("ix_gen_column_id"), "gen_column", ["id"], unique=False)
    op.alter_column(
        "gen_column",
        "gen_business_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="代码生成业务ID",
        existing_nullable=False,
    )
    op.alter_column(
        "gen_column",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_gen_business_id"), table_name="gen_business")
    op.create_index(op.f("ix_gen_business_id"), "gen_business", ["id"], unique=False)
    op.alter_column(
        "gen_business",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('gen_business_id_seq'::regclass)"),
    )
    op.drop_index(op.f("ix_ai_training_logs_id"), table_name="ai_training_logs")
    op.create_index(op.f("ix_ai_training_logs_id"), "ai_training_logs", ["id"], unique=False)
    op.alter_column(
        "ai_training_logs",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_ai_subscription_notifications_subscription_id"), table_name="ai_subscription_notifications")
    op.create_index(
        op.f("ix_ai_subscription_notifications_subscription_id"),
        "ai_subscription_notifications",
        ["subscription_id"],
        unique=False,
    )
    op.alter_column(
        "ai_subscription_notifications",
        "subscription_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="订阅ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_ai_subscription_id"), table_name="ai_subscription")
    op.create_index(op.f("ix_ai_subscription_id"), "ai_subscription", ["id"], unique=False)
    op.alter_column(
        "ai_subscription",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="订阅ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_ai_database_metadata_id"), table_name="ai_database_metadata")
    op.create_index(op.f("ix_ai_database_metadata_id"), "ai_database_metadata", ["id"], unique=False)
    op.alter_column(
        "ai_database_metadata",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
