"""Use setting field for data source limit configuration

Revision ID: c6333b261a5d
Revises: 2351485a6e6c
Create Date: 2025-09-06 10:13:45.977058

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c6333b261a5d"
down_revision = "2351485a6e6c"
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """检查约束是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 检查外键约束
    fks = [fk["name"] for fk in inspector.get_foreign_keys(table_name) if fk["name"]]
    if constraint_name in fks:
        return True

    # 检查唯一约束
    uqs = [uq["name"] for uq in inspector.get_unique_constraints(table_name) if uq["name"]]
    if constraint_name in uqs:
        return True

    # 检查检查约束
    checks = [ck["name"] for ck in inspector.get_check_constraints(table_name) if ck["name"]]
    return constraint_name in checks


def _table_exists(table_name: str) -> bool:
    """检查表是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    if not _table_exists(table_name):
        return False
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_subscription", schema=None) as batch_op:
        batch_op.alter_column(
            "setting",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            comment="其他设置（包含数据范围限制配置）",
            existing_comment="其他设置",
            existing_nullable=True,
        )

        # 只删除存在的列
        columns_to_drop = [
            "agent_limit",
            "country_limit",
            "tag_limit",
            "registration_time_limit",
            "data_source_limit_type",
            "kyc_status_limit",
            "customer_limit",
        ]

        for column_name in columns_to_drop:
            if _column_exists("ai_subscription", column_name):
                batch_op.drop_column(column_name)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_subscription", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "customer_limit",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
                comment="客户限制",
            )
        )
        batch_op.add_column(
            sa.Column(
                "kyc_status_limit",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
                comment="KYC状态限制",
            )
        )
        batch_op.add_column(
            sa.Column(
                "data_source_limit_type",
                sa.VARCHAR(length=20),
                autoincrement=False,
                nullable=True,
                comment="数据范围限制类型",
            )
        )
        batch_op.add_column(
            sa.Column(
                "registration_time_limit",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
                comment="注册时间限制",
            )
        )
        batch_op.add_column(
            sa.Column(
                "tag_limit",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
                comment="标签限制",
            )
        )
        batch_op.add_column(
            sa.Column(
                "country_limit",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
                comment="国家限制",
            )
        )
        batch_op.add_column(
            sa.Column(
                "agent_limit",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
                comment="代理限制",
            )
        )
        batch_op.alter_column(
            "setting",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            comment="其他设置",
            existing_comment="其他设置（包含数据范围限制配置）",
            existing_nullable=True,
        )

    # ### end Alembic commands ###
