"""描述你的变更

Revision ID: 7d836b48dabb
Revises: 497de9d282c2
Create Date: 2025-09-10 17:36:26.872732

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7d836b48dabb"
down_revision = "497de9d282c2"
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """检查约束是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 检查外键约束
    fks = [fk["name"] for fk in inspector.get_foreign_keys(table_name) if fk["name"]]
    if constraint_name in fks:
        return True

    # 检查唯一约束
    uqs = [uq["name"] for uq in inspector.get_unique_constraints(table_name) if uq["name"]]
    if constraint_name in uqs:
        return True

    # 检查检查约束
    checks = [ck["name"] for ck in inspector.get_check_constraints(table_name) if ck["name"]]
    return constraint_name in checks


def _table_exists(table_name: str) -> bool:
    """检查表是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    if not _table_exists(table_name):
        return False
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_assistant_report_user_read", schema=None) as batch_op:
        constraint_name = "ai_assistant_report_user_read_report_id_fkey"
        if _constraint_exists("ai_assistant_report_user_read", constraint_name):
            batch_op.drop_constraint(constraint_name, type_="foreignkey")

    with op.batch_alter_table("ai_subscription", schema=None) as batch_op:
        batch_op.alter_column(
            "responsible_persons",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            comment="通知对象列表",
            existing_comment="指定人员列表",
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_subscription", schema=None) as batch_op:
        batch_op.alter_column(
            "responsible_persons",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            comment="指定人员列表",
            existing_comment="通知对象列表",
            existing_nullable=True,
        )

    with op.batch_alter_table("ai_assistant_report_user_read", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("ai_assistant_report_user_read_report_id_fkey"),
            "ai_assistant_report_log",
            ["report_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###
