"""统一软删除字段为deleted_at

Revision ID: 81ced769d4b9
Revises: 829a9bd6f5a9
Create Date: 2025-09-08 18:02:01.175776

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "81ced769d4b9"
down_revision = "829a9bd6f5a9"
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """检查约束是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 检查外键约束
    fks = [fk["name"] for fk in inspector.get_foreign_keys(table_name) if fk["name"]]
    if constraint_name in fks:
        return True

    # 检查唯一约束
    uqs = [uq["name"] for uq in inspector.get_unique_constraints(table_name) if uq["name"]]
    if constraint_name in uqs:
        return True

    # 检查检查约束
    checks = [ck["name"] for ck in inspector.get_check_constraints(table_name) if ck["name"]]
    return constraint_name in checks


def _table_exists(table_name: str) -> bool:
    """检查表是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    if not _table_exists(table_name):
        return False
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("risk_tag", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, comment="软删除时间，NULL表示未删除")
        )
        batch_op.drop_index(batch_op.f("ix_risk_tag_is_deleted"))
        batch_op.create_index(batch_op.f("ix_risk_tag_deleted_at"), ["deleted_at"], unique=False)
        batch_op.drop_column("is_deleted")
        batch_op.drop_column("deleted_time")

    with op.batch_alter_table("sys_dept", schema=None) as batch_op:
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间，NULL表示未删除"))
        batch_op.create_index(batch_op.f("ix_sys_dept_deleted_at"), ["deleted_at"], unique=False)
        batch_op.drop_column("del_flag")

    with op.batch_alter_table("sys_menu", schema=None) as batch_op:
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间，NULL表示未删除"))
        batch_op.create_index(batch_op.f("ix_sys_menu_deleted_at"), ["deleted_at"], unique=False)

    with op.batch_alter_table("sys_role", schema=None) as batch_op:
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间，NULL表示未删除"))
        batch_op.create_index(batch_op.f("ix_sys_role_deleted_at"), ["deleted_at"], unique=False)

    with op.batch_alter_table("sys_user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, comment="软删除时间，NULL表示未删除")
        )
        batch_op.create_index(batch_op.f("ix_sys_user_deleted_at"), ["deleted_at"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sys_user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_user_deleted_at"))
        batch_op.drop_column("deleted_at")

    with op.batch_alter_table("sys_role", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_role_deleted_at"))
        batch_op.drop_column("deleted_at")

    with op.batch_alter_table("sys_menu", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_menu_deleted_at"))
        batch_op.drop_column("deleted_at")

    with op.batch_alter_table("sys_dept", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("del_flag", sa.INTEGER(), autoincrement=False, nullable=False, comment="删除标志（0删除 1存在）")
        )
        batch_op.drop_index(batch_op.f("ix_sys_dept_deleted_at"))
        batch_op.drop_column("deleted_at")

    with op.batch_alter_table("risk_tag", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "deleted_time",
                postgresql.TIMESTAMP(timezone=True),
                autoincrement=False,
                nullable=True,
                comment="删除时间",
            )
        )
        batch_op.add_column(
            sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False, comment="是否已删除")
        )
        batch_op.drop_index(batch_op.f("ix_risk_tag_deleted_at"))
        batch_op.create_index(batch_op.f("ix_risk_tag_is_deleted"), ["is_deleted"], unique=False)
        batch_op.drop_column("deleted_at")

    # ### end Alembic commands ###
