"""Add soft delete fields to risk_tag

Revision ID: 373c6e45bf35
Revises: fe750118611a
Create Date: 2025-08-27 12:34:55.009128

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "373c6e45bf35"
down_revision = "fe750118611a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可空字段
    op.add_column("risk_tag", sa.Column("is_deleted", sa.Boolean(), nullable=True, comment="是否已删除"))
    op.add_column("risk_tag", sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True, comment="删除时间"))

    # 为现有数据设置默认值
    op.execute("UPDATE risk_tag SET is_deleted = false WHERE is_deleted IS NULL")

    # 将字段设为非空
    op.alter_column("risk_tag", "is_deleted", nullable=False)

    # 创建索引
    op.create_index(op.f("ix_risk_tag_is_deleted"), "risk_tag", ["is_deleted"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_risk_tag_is_deleted"), table_name="risk_tag")
    op.drop_column("risk_tag", "deleted_time")
    op.drop_column("risk_tag", "is_deleted")
    # ### end Alembic commands ###
