"""Add task models

Revision ID: 4032fc0f911f
Revises: 6b275f964adb
Create Date: 2025-08-19 12:05:11.131585

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql, postgresql

# revision identifiers, used by Alembic.
revision = "4032fc0f911f"
down_revision = "6b275f964adb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_scheduler",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("name", sa.String(length=50), nullable=False, comment="任务名称"),
        sa.Column("task", sa.String(length=255), nullable=False, comment="要运行的 Celery 任务"),
        sa.Column("args", sa.JSON(), nullable=True, comment="任务可接收的位置参数"),
        sa.Column("kwargs", sa.JSON(), nullable=True, comment="任务可接收的关键字参数"),
        sa.Column("queue", sa.String(length=255), nullable=True, comment="CELERY_TASK_QUEUES 中定义的队列"),
        sa.Column("exchange", sa.String(length=255), nullable=True, comment="低级别 AMQP 路由的交换机"),
        sa.Column("routing_key", sa.String(length=255), nullable=True, comment="低级别 AMQP 路由的路由密钥"),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True, comment="任务开始触发的时间"),
        sa.Column("expire_time", sa.DateTime(timezone=True), nullable=True, comment="任务不再触发的截止时间"),
        sa.Column("expire_seconds", sa.Integer(), nullable=True, comment="任务不再触发的秒数时间差"),
        sa.Column("type", sa.Integer(), nullable=False, comment="调度类型（0间隔 1定时）"),
        sa.Column("interval_every", sa.Integer(), nullable=True, comment="任务再次运行前的间隔周期数"),
        sa.Column("interval_period", sa.String(length=255), nullable=True, comment="任务运行之间的周期类型"),
        sa.Column("crontab", sa.String(length=50), nullable=True, comment="任务运行的 Crontab 计划"),
        sa.Column(
            "one_off", sa.Boolean().with_variant(sa.INTEGER(), "postgresql"), nullable=False, comment="是否仅运行一次"
        ),
        sa.Column(
            "enabled", sa.Boolean().with_variant(sa.INTEGER(), "postgresql"), nullable=False, comment="是否启用任务"
        ),
        sa.Column("total_run_count", sa.Integer(), nullable=False, comment="任务触发的总次数"),
        sa.Column("last_run_time", sa.DateTime(timezone=True), nullable=True, comment="任务最后触发的时间"),
        sa.Column("remark", mysql.LONGTEXT().with_variant(sa.TEXT(), "postgresql"), nullable=True, comment="备注"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        comment="任务调度表",
    )
    op.create_index(op.f("ix_task_scheduler_id"), "task_scheduler", ["id"], unique=False)

    # 检查并删除 task_result 表（如果存在）
    inspector = op.get_bind().dialect.inspector(op.get_bind())
    if "task_result" in inspector.get_table_names():
        op.drop_table("task_result")

    # 检查并删除 task_group_result 表（如果存在）
    if "task_group_result" in inspector.get_table_names():
        op.drop_table("task_group_result")
    op.alter_column(
        "ai_subscription", "id", existing_type=sa.VARCHAR(length=50), comment="助手ID", existing_nullable=False
    )
    op.alter_column(
        "ai_subscription",
        "execution_frequency",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_comment="执行频率",
    )
    op.alter_column(
        "ai_subscription", "is_view_myself", existing_type=sa.BOOLEAN(), nullable=False, existing_comment="本人查看"
    )
    op.alter_column(
        "ai_subscription", "ai_analysis_count", existing_type=sa.INTEGER(), nullable=False, existing_comment="分析次数"
    )
    op.alter_column(
        "ai_subscription",
        "created_time",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
        comment="创建时间",
    )
    op.alter_column(
        "ai_subscription",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        comment="更新时间",
        existing_nullable=True,
    )
    op.create_table_comment("ai_subscription", "AI订阅模型", existing_comment=None, schema=None)
    op.alter_column(
        "ai_subscription_notification_methods",
        "id",
        existing_type=sa.VARCHAR(length=50),
        comment="通知方式ID",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_subscription_notification_methods",
        "status",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_comment="状态",
    )
    op.alter_column(
        "ai_subscription_notification_methods",
        "created_time",
        existing_type=postgresql.TIMESTAMP(),
        comment="创建时间",
        existing_nullable=True,
    )
    op.alter_column(
        "ai_subscription_notification_methods",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(),
        comment="更新时间",
        existing_nullable=True,
    )
    op.create_table_comment(
        "ai_subscription_notification_methods", "AI订阅通知方式表", existing_comment=None, schema=None
    )
    op.add_column(
        "ai_subscription_notifications",
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
    )
    op.alter_column(
        "ai_subscription_notifications",
        "id",
        existing_type=sa.VARCHAR(length=50),
        comment="关联ID",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_subscription_notifications",
        "created_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        comment="创建时间",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ai_subscription_notifications",
        "created_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        comment=None,
        existing_comment="创建时间",
    )
    op.alter_column(
        "ai_subscription_notifications",
        "id",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="关联ID",
        existing_nullable=False,
    )
    op.drop_column("ai_subscription_notifications", "updated_time")
    op.drop_table_comment("ai_subscription_notification_methods", existing_comment="AI订阅通知方式表", schema=None)
    op.alter_column(
        "ai_subscription_notification_methods",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "ai_subscription_notification_methods",
        "created_time",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="创建时间",
        existing_nullable=True,
    )
    op.alter_column(
        "ai_subscription_notification_methods",
        "status",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_comment="状态",
    )
    op.alter_column(
        "ai_subscription_notification_methods",
        "id",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="通知方式ID",
        existing_nullable=False,
    )
    op.drop_table_comment("ai_subscription", existing_comment="AI订阅模型", schema=None)
    op.alter_column(
        "ai_subscription",
        "updated_time",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "ai_subscription",
        "created_time",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
        comment=None,
        existing_comment="创建时间",
    )
    op.alter_column(
        "ai_subscription", "ai_analysis_count", existing_type=sa.INTEGER(), nullable=True, existing_comment="分析次数"
    )
    op.alter_column(
        "ai_subscription", "is_view_myself", existing_type=sa.BOOLEAN(), nullable=True, existing_comment="本人查看"
    )
    op.alter_column(
        "ai_subscription",
        "execution_frequency",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_comment="执行频率",
    )
    op.alter_column(
        "ai_subscription",
        "id",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="助手ID",
        existing_nullable=False,
    )
    op.create_table(
        "task_group_result",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("taskset_id", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
        sa.Column("result", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column("date_done", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("task_group_result_pkey")),
        sa.UniqueConstraint(
            "taskset_id",
            name=op.f("task_group_result_taskset_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "task_result",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("result", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column("date_done", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("traceback", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
        sa.Column("args", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column("kwargs", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column("worker", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
        sa.Column("retries", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("queue", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("task_result_pkey")),
        sa.UniqueConstraint(
            "task_id", name=op.f("task_result_task_id_key"), postgresql_include=[], postgresql_nulls_not_distinct=False
        ),
    )
    op.drop_index(op.f("ix_task_scheduler_id"), table_name="task_scheduler")
    op.drop_table("task_scheduler")

    # 检查并创建 task_group_result 表（如果不存在）
    inspector = op.get_bind().dialect.inspector(op.get_bind())
    if "task_group_result" not in inspector.get_table_names():
        op.create_table(
            "task_group_result",
            sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column("taskset_id", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
            sa.Column("result", postgresql.BYTEA(), autoincrement=False, nullable=True),
            sa.Column("date_done", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
            sa.PrimaryKeyConstraint("id", name=op.f("task_group_result_pkey")),
            sa.UniqueConstraint(
                "taskset_id",
                name=op.f("task_group_result_taskset_id_key"),
                postgresql_include=[],
                postgresql_nulls_not_distinct=False,
            ),
        )

    # 检查并创建 task_result 表（如果不存在）
    if "task_result" not in inspector.get_table_names():
        op.create_table(
            "task_result",
            sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column("task_id", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
            sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
            sa.Column("result", postgresql.BYTEA(), autoincrement=False, nullable=True),
            sa.Column("date_done", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
            sa.Column("traceback", sa.TEXT(), autoincrement=False, nullable=True),
            sa.Column("name", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
            sa.Column("args", postgresql.BYTEA(), autoincrement=False, nullable=True),
            sa.Column("kwargs", postgresql.BYTEA(), autoincrement=False, nullable=True),
            sa.Column("worker", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
            sa.Column("retries", sa.INTEGER(), autoincrement=False, nullable=True),
            sa.Column("queue", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
            sa.PrimaryKeyConstraint("id", name=op.f("task_result_pkey")),
            sa.UniqueConstraint(
                "task_id",
                name=op.f("task_result_task_id_key"),
                postgresql_include=[],
                postgresql_nulls_not_distinct=False,
            ),
        )
    # ### end Alembic commands ###
