"""同步模型变更

Revision ID: d8f1a1633bbc
Revises: 57072d08ed7a
Create Date: 2025-09-05 15:22:43.802792

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d8f1a1633bbc"
down_revision = "57072d08ed7a"
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """检查约束是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 检查外键约束
    fks = [fk["name"] for fk in inspector.get_foreign_keys(table_name) if fk["name"]]
    if constraint_name in fks:
        return True

    # 检查唯一约束
    uqs = [uq["name"] for uq in inspector.get_unique_constraints(table_name) if uq["name"]]
    if constraint_name in uqs:
        return True

    # 检查检查约束
    checks = [ck["name"] for ck in inspector.get_check_constraints(table_name) if ck["name"]]
    return constraint_name in checks


def _table_exists(table_name: str) -> bool:
    """检查表是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    if not _table_exists(table_name):
        return False
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_subscription", schema=None) as batch_op:
        batch_op.add_column(sa.Column("scheduler_id", sa.BigInteger(), nullable=True, comment="关联的调度任务ID"))
        batch_op.add_column(sa.Column("status", sa.Boolean(), nullable=False, comment="订阅状态"))
        batch_op.create_foreign_key(None, "task_scheduler", ["scheduler_id"], ["id"], ondelete="SET NULL")
        batch_op.create_foreign_key(None, "ai_assistants", ["assistant_id"], ["id"])

    with op.batch_alter_table("task_scheduler_execution", schema=None) as batch_op:
        batch_op.add_column(sa.Column("report_id", sa.String(length=50), nullable=True, comment="生成的报告ID"))
        batch_op.add_column(
            sa.Column("status", sa.String(length=20), nullable=True, comment="执行状态：running, completed, failed")
        )
        batch_op.add_column(sa.Column("error_message", sa.Text(), nullable=True, comment="错误信息"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_scheduler_execution", schema=None) as batch_op:
        batch_op.drop_column("error_message")
        batch_op.drop_column("status")
        batch_op.drop_column("report_id")

    with op.batch_alter_table("ai_subscription", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("status")
        batch_op.drop_column("scheduler_id")

    # ### end Alembic commands ###
