"""Change report_tags field type to Text

Revision ID: e0d982c6e77e
Revises: 373c6e45bf35
Create Date: 2025-08-27 12:42:19.463556

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e0d982c6e77e"
down_revision = "373c6e45bf35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "risk_report_log",
        "report_tags",
        existing_type=sa.VARCHAR(length=1000),
        type_=sa.Text(),
        comment="报告标签，JSON格式字符串",
        existing_comment="报告标签",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "risk_report_log",
        "report_tags",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=1000),
        comment="报告标签",
        existing_comment="报告标签，JSON格式字符串",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
