"""remove duration_seconds field from task_scheduler_execution

Revision ID: fe750118611a
Revises: d6c0fd3a9507
Create Date: 2025-08-26 22:38:06.071918

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fe750118611a"
down_revision = "d6c0fd3a9507"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_scheduler_execution", "duration_seconds")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_scheduler_execution",
        sa.Column(
            "duration_seconds",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="执行时长（秒）",
        ),
    )
    # ### end Alembic commands ###
