"""add_username_email_to_ai_assistant_personnel

Revision ID: 1a39f6e9212d
Revises: ba7f32ab369c
Create Date: 2025-08-14 20:28:49.478641

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql, postgresql

# revision identifiers, used by Alembic.
revision = "1a39f6e9212d"
down_revision = "ba7f32ab369c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_assistant_personnel", sa.Column("username", sa.String(length=50), nullable=False, comment="用户名")
    )
    op.add_column("ai_assistant_personnel", sa.Column("email", sa.String(length=100), nullable=False, comment="邮箱"))
    op.alter_column(
        "ai_assistant_report_log",
        "report_status",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_comment="报告状态",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_assistant_report_log",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=None,
        existing_comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_assistant_report_log",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=None,
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_ai_assistant_report_log_member_id"), table_name="ai_assistant_report_log")
    op.create_index(
        op.f("ix_ai_assistant_report_log_member_ids"), "ai_assistant_report_log", ["member_ids"], unique=False
    )
    op.create_index(op.f("ix_ai_assistant_report_log_model_id"), "ai_assistant_report_log", ["model_id"], unique=False)
    op.create_foreign_key(None, "ai_assistant_report_log", "ai_assistants", ["assistant_id"], ["id"])
    op.alter_column(
        "ai_assistants",
        "ai_model_id",
        existing_type=sa.VARCHAR(length=50),
        comment="AI模型ID",
        existing_comment="模型类型",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_assistants",
        "data_permission",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_comment="数据权限",
    )
    op.alter_column(
        "ai_assistants",
        "data_permission_values",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_comment="数据权限具体值",
        existing_nullable=True,
    )
    op.alter_column(
        "ai_assistants",
        "data_time_range_type",
        existing_type=postgresql.ENUM("day", "month", "quarter", "year", name="data_time_range_enum"),
        server_default=None,
        existing_comment="数据时间范围类型",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_assistants",
        "data_time_value",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_comment="数据时间范围值",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_assistants", "ai_analysis_count", existing_type=sa.INTEGER(), nullable=False, existing_comment="AI分析次数"
    )
    op.alter_column(
        "ai_assistants",
        "last_analysis_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        type_=sa.DateTime(),
        existing_comment="最后一次分析时间",
        existing_nullable=True,
    )
    op.alter_column(
        "ai_chat",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        nullable=True,
        comment=None,
        existing_comment="创建时间",
    )
    op.alter_column(
        "ai_chat",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        comment=None,
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.create_index(op.f("ix_ai_chat_message_chat_id"), "ai_chat_message", ["chat_id"], unique=False)
    op.create_foreign_key(None, "ai_chat_message", "ai_chat", ["chat_id"], ["id"])
    op.create_table_comment(
        "ai_chat_message",
        "AI Chat Message model for storing individual messages in a chat session",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "ai_models",
        "model",
        existing_type=sa.VARCHAR(length=100),
        comment="模型名称/标识符，如gpt-4-turbo",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_models",
        "temperature",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=None,
        comment="温度参数，值范围0-1",
        existing_nullable=False,
    )
    # 手动处理 prompt_template 列类型转换
    op.execute("ALTER TABLE ai_training_logs ALTER COLUMN prompt_template TYPE JSON USING prompt_template::json")
    op.alter_column(
        "ai_training_logs",
        "prompt_template",
        existing_type=sa.TEXT(),
        type_=sa.JSON(),
        existing_comment="使用的提示词模板",
        existing_nullable=True,
    )
    op.alter_column(
        "client_user",
        "id",
        existing_type=sa.INTEGER(),
        comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('client_user_id_seq'::regclass)"),
    )
    op.alter_column("client_user", "created_at", existing_type=postgresql.TIMESTAMP(precision=6), nullable=False)
    op.alter_column("client_user", "updated_at", existing_type=postgresql.TIMESTAMP(precision=6), nullable=False)
    op.alter_column(
        "client_user",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "client_user",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        comment="更新时间",
        existing_nullable=True,
    )
    op.create_index(op.f("ix_client_user_email"), "client_user", ["email"], unique=True)
    op.create_index(op.f("ix_client_user_id"), "client_user", ["id"], unique=False)
    op.create_index(op.f("ix_client_user_username"), "client_user", ["username"], unique=True)
    op.create_table_comment("client_user", "客户端用户模型", existing_comment=None, schema=None)
    op.alter_column("mcp_query", "status", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "mcp_query",
        "created_time",
        existing_type=postgresql.TIMESTAMP(precision=6),
        type_=sa.DateTime(timezone=True),
        nullable=False,
        comment="创建时间",
    )
    op.alter_column(
        "mcp_query",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        comment="更新时间",
        existing_nullable=True,
    )
    op.create_index(op.f("ix_mcp_query_chat_message_id"), "mcp_query", ["chat_message_id"], unique=False)
    op.create_table_comment(
        "mcp_query",
        "MCP Query model for tracking data queries made through the MCP service",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "risk_assistant", "risk_type", existing_type=sa.VARCHAR(length=100), nullable=True, existing_comment="风险类型"
    )
    op.alter_column(
        "risk_assistant",
        "ai_analysis_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        nullable=False,
        existing_comment="AI分析次数",
    )
    op.alter_column(
        "risk_assistant",
        "last_analysis_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        type_=sa.DateTime(),
        existing_comment="最后一次分析时间",
        existing_nullable=True,
    )
    op.alter_column(
        "risk_report_log",
        "id",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="报告ID",
        autoincrement=True,
    )
    op.alter_column(
        "risk_report_log",
        "handle_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        type_=sa.DateTime(),
        existing_comment="处理时间",
        existing_nullable=True,
    )
    op.alter_column(
        "risk_report_log",
        "member_name",
        existing_type=sa.VARCHAR(length=50),
        comment="用户名称",
        existing_comment="用户名",
        existing_nullable=True,
    )
    op.alter_column(
        "risk_report_log",
        "report_status",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_comment="报告状态",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_report_log",
        "is_processed",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_comment="是否需要处理",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_report_log",
        "ai_response",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
        existing_comment="AI响应",
    )
    op.alter_column(
        "risk_report_log",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=None,
        existing_comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_report_log",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=None,
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.create_index(op.f("ix_risk_report_log_model_id"), "risk_report_log", ["model_id"], unique=False)
    op.create_foreign_key(None, "risk_report_log", "risk_assistant", ["assistant_id"], ["id"])
    op.alter_column(
        "risk_tag", "id", existing_type=sa.VARCHAR(length=36), comment="标签ID，使用UUID", existing_nullable=False
    )
    op.alter_column(
        "risk_tag", "category_id", existing_type=sa.VARCHAR(length=36), comment="标签分类ID", existing_nullable=False
    )
    op.alter_column(
        "risk_tag", "name", existing_type=sa.VARCHAR(length=100), comment="标签名称", existing_nullable=False
    )
    op.alter_column("risk_tag", "description", existing_type=sa.TEXT(), comment="标签描述", existing_nullable=True)
    op.alter_column(
        "risk_tag",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=None,
        comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_tag",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        comment="更新时间",
        existing_nullable=True,
    )
    # Skip creating index as it already exists with different name (ix_risk_tag_category_id_fk)
    # op.create_index(op.f('ix_risk_tag_category_id'), 'risk_tag', ['category_id'], unique=False)
    op.create_index(op.f("ix_risk_tag_name"), "risk_tag", ["name"], unique=False)
    op.create_table_comment("risk_tag", "风控标签表", existing_comment=None, schema=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("risk_tag", existing_comment="风控标签表", schema=None)
    op.drop_index(op.f("ix_risk_tag_name"), table_name="risk_tag")
    # Skip dropping index as it was not created in upgrade
    # op.drop_index(op.f('ix_risk_tag_category_id'), table_name='risk_tag')
    op.alter_column(
        "risk_tag",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        comment=None,
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "risk_tag",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=sa.text("now()"),
        comment=None,
        existing_comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_tag",
        "description",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="标签描述",
        existing_nullable=True,
    )
    op.alter_column(
        "risk_tag",
        "name",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="标签名称",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_tag",
        "category_id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="标签分类ID",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_tag",
        "id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="标签ID，使用UUID",
        existing_nullable=False,
    )
    op.drop_constraint(None, "risk_report_log", type_="foreignkey")
    op.drop_index(op.f("ix_risk_report_log_model_id"), table_name="risk_report_log")
    op.alter_column(
        "risk_report_log",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=sa.text("now()"),
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "risk_report_log",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=sa.text("NULL::timestamp with time zone"),
        existing_comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_report_log",
        "ai_response",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
        existing_comment="AI响应",
    )
    op.alter_column(
        "risk_report_log",
        "is_processed",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_comment="是否需要处理",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_report_log",
        "report_status",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_comment="报告状态",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_report_log",
        "member_name",
        existing_type=sa.VARCHAR(length=50),
        comment="用户名",
        existing_comment="用户名称",
        existing_nullable=True,
    )
    op.alter_column(
        "risk_report_log",
        "handle_time",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True, precision=6),
        existing_comment="处理时间",
        existing_nullable=True,
    )
    op.alter_column(
        "risk_report_log",
        "id",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="报告ID",
        autoincrement=True,
    )
    op.alter_column(
        "risk_assistant",
        "last_analysis_time",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True, precision=6),
        existing_comment="最后一次分析时间",
        existing_nullable=True,
    )
    op.alter_column(
        "risk_assistant",
        "ai_analysis_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=True,
        existing_comment="AI分析次数",
    )
    op.alter_column(
        "risk_assistant", "risk_type", existing_type=sa.VARCHAR(length=100), nullable=False, existing_comment="风险类型"
    )
    op.drop_table_comment(
        "mcp_query",
        existing_comment="MCP Query model for tracking data queries made through the MCP service",
        schema=None,
    )
    op.drop_index(op.f("ix_mcp_query_chat_message_id"), table_name="mcp_query")
    op.alter_column(
        "mcp_query",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        comment=None,
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "mcp_query",
        "created_time",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(precision=6),
        nullable=True,
        comment=None,
        existing_comment="创建时间",
    )
    op.alter_column("mcp_query", "status", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_table_comment("client_user", existing_comment="客户端用户模型", schema=None)
    op.drop_index(op.f("ix_client_user_username"), table_name="client_user")
    op.drop_index(op.f("ix_client_user_id"), table_name="client_user")
    op.drop_index(op.f("ix_client_user_email"), table_name="client_user")
    op.alter_column(
        "client_user",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        comment=None,
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "client_user",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        comment=None,
        existing_comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column("client_user", "updated_at", existing_type=postgresql.TIMESTAMP(precision=6), nullable=True)
    op.alter_column("client_user", "created_at", existing_type=postgresql.TIMESTAMP(precision=6), nullable=True)
    op.alter_column(
        "client_user",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('client_user_id_seq'::regclass)"),
    )
    op.alter_column(
        "ai_training_logs",
        "prompt_template",
        existing_type=mysql.JSON(),
        type_=sa.TEXT(),
        existing_comment="使用的提示词模板",
        existing_nullable=True,
    )
    op.alter_column(
        "ai_models",
        "temperature",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text("'0.75'::double precision"),
        comment=None,
        existing_comment="温度参数，值范围0-1",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_models",
        "model",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="模型名称/标识符，如gpt-4-turbo",
        existing_nullable=False,
    )
    op.drop_table_comment(
        "ai_chat_message",
        existing_comment="AI Chat Message model for storing individual messages in a chat session",
        schema=None,
    )
    op.drop_constraint(None, "ai_chat_message", type_="foreignkey")
    op.drop_index(op.f("ix_ai_chat_message_chat_id"), table_name="ai_chat_message")
    op.alter_column(
        "ai_chat",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "ai_chat",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        nullable=False,
        comment="创建时间",
    )
    op.alter_column(
        "ai_assistants",
        "last_analysis_time",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True, precision=6),
        existing_comment="最后一次分析时间",
        existing_nullable=True,
    )
    op.alter_column(
        "ai_assistants", "ai_analysis_count", existing_type=sa.INTEGER(), nullable=True, existing_comment="AI分析次数"
    )
    op.alter_column(
        "ai_assistants",
        "data_time_value",
        existing_type=sa.INTEGER(),
        server_default=sa.text("1"),
        existing_comment="数据时间范围值",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_assistants",
        "data_time_range_type",
        existing_type=postgresql.ENUM("day", "month", "quarter", "year", name="data_time_range_enum"),
        server_default=sa.text("'month'::data_time_range_enum"),
        existing_comment="数据时间范围类型",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_assistants",
        "data_permission_values",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_comment="数据权限具体值",
        existing_nullable=True,
    )
    op.alter_column(
        "ai_assistants",
        "data_permission",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_comment="数据权限",
    )
    op.alter_column(
        "ai_assistants",
        "ai_model_id",
        existing_type=sa.VARCHAR(length=50),
        comment="模型类型",
        existing_comment="AI模型ID",
        existing_nullable=False,
    )
    op.drop_constraint(None, "ai_assistant_report_log", type_="foreignkey")
    op.drop_index(op.f("ix_ai_assistant_report_log_model_id"), table_name="ai_assistant_report_log")
    op.drop_index(op.f("ix_ai_assistant_report_log_member_ids"), table_name="ai_assistant_report_log")
    op.create_index(
        op.f("ix_ai_assistant_report_log_member_id"), "ai_assistant_report_log", ["member_ids"], unique=False
    )
    op.alter_column(
        "ai_assistant_report_log",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=sa.text("now()"),
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "ai_assistant_report_log",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=sa.text("now()"),
        existing_comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_assistant_report_log",
        "report_status",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_comment="报告状态",
        existing_nullable=False,
    )
    op.drop_column("ai_assistant_personnel", "email")
    op.drop_column("ai_assistant_personnel", "username")
    # ### end Alembic commands ###
