"""add_recommended_questions_table

Revision ID: edd6636a4f4f
Revises: ddc9d7dbe100
Create Date: 2025-10-21 16:50:05.141929

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "edd6636a4f4f"
down_revision = "ddc9d7dbe100"
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """检查约束是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 检查外键约束
    fks = [fk["name"] for fk in inspector.get_foreign_keys(table_name) if fk["name"]]
    if constraint_name in fks:
        return True

    # 检查唯一约束
    uqs = [uq["name"] for uq in inspector.get_unique_constraints(table_name) if uq["name"]]
    if constraint_name in uqs:
        return True

    # 检查检查约束
    checks = [ck["name"] for ck in inspector.get_check_constraints(table_name) if ck["name"]]
    return constraint_name in checks


def _table_exists(table_name: str) -> bool:
    """检查表是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    if not _table_exists(table_name):
        return False
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sys_recommended_questions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("title", sa.String(length=100), nullable=False, comment="问法标题"),
        sa.Column("content", sa.Text(), nullable=False, comment="问法内容"),
        sa.Column("role_ids", sa.JSON(), nullable=True, comment="关联角色ID列表"),
        sa.Column("sort_order", sa.Integer(), nullable=False, comment="排序"),
        sa.Column("status", sa.Integer(), nullable=False, comment="状态(0停用 1正常)"),
        sa.Column("is_default", sa.Boolean(), nullable=False, comment="是否默认问法"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, comment="软删除时间，NULL表示未删除"),
        sa.PrimaryKeyConstraint("id"),
        comment="推荐问法表",
    )
    with op.batch_alter_table("sys_recommended_questions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sys_recommended_questions_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_sys_recommended_questions_id"), ["id"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sys_recommended_questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_recommended_questions_id"))
        batch_op.drop_index(batch_op.f("ix_sys_recommended_questions_deleted_at"))

    op.drop_table("sys_recommended_questions")
    # ### end Alembic commands ###
