"""Fix user_id field types to BigInteger and add subscription features

Revision ID: b148ba90f0bc
Revises: 809b8929a56a
Create Date: 2025-09-08 16:31:59.929176

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b148ba90f0bc"
down_revision = "809b8929a56a"
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """检查约束是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 检查外键约束
    fks = [fk["name"] for fk in inspector.get_foreign_keys(table_name) if fk["name"]]
    if constraint_name in fks:
        return True

    # 检查唯一约束
    uqs = [uq["name"] for uq in inspector.get_unique_constraints(table_name) if uq["name"]]
    if constraint_name in uqs:
        return True

    # 检查检查约束
    checks = [ck["name"] for ck in inspector.get_check_constraints(table_name) if ck["name"]]
    return constraint_name in checks


def _table_exists(table_name: str) -> bool:
    """检查表是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    if not _table_exists(table_name):
        return False
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_subscription", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.BigInteger(), nullable=True, comment="创建用户ID"))
        batch_op.create_foreign_key(None, "sys_user", ["user_id"], ["id"])

    with op.batch_alter_table("ai_subscription_notifications", schema=None) as batch_op:
        batch_op.add_column(sa.Column("report_id", sa.Integer(), nullable=True, comment="关联报告ID"))
        batch_op.add_column(
            sa.Column(
                "send_status",
                sa.String(length=20),
                nullable=False,
                server_default="pending",
                comment="发送状态: pending-待发送, sending-发送中, sent-已发送, failed-发送失败",
            )
        )
        batch_op.add_column(sa.Column("send_time", sa.DateTime(), nullable=True, comment="发送时间"))
        batch_op.add_column(
            sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0", comment="重试次数")
        )
        batch_op.add_column(sa.Column("error_message", sa.Text(), nullable=True, comment="错误信息"))
        batch_op.alter_column(
            "updated_time",
            existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
            type_=sa.DateTime(),
            existing_comment="更新时间",
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_subscription_notifications", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_time",
            existing_type=sa.DateTime(),
            type_=postgresql.TIMESTAMP(timezone=True, precision=6),
            existing_comment="更新时间",
            existing_nullable=True,
        )
        batch_op.drop_column("error_message")
        batch_op.drop_column("retry_count")
        batch_op.drop_column("send_time")
        batch_op.drop_column("send_status")
        batch_op.drop_column("report_id")

    with op.batch_alter_table("ai_subscription", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
