"""fix_ai_chat_message_field_mapping

Revision ID: bfbe1aac0618
Revises: 163f08062417
Create Date: 2025-08-20 17:21:49.690431

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "bfbe1aac0618"
down_revision = "163f08062417"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ai_chat_message_chat_id_fkey"), "ai_chat_message", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f("ai_chat_message_chat_id_fkey"), "ai_chat_message", "ai_chat", ["chat_id"], ["id"])
    # ### end Alembic commands ###
