"""create_tables

Revision ID: ba7f32ab369c
Revises: 001620589d9d
Create Date: 2025-08-13 08:54:16.830772

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql, postgresql

# revision identifiers, used by Alembic.
revision = "ba7f32ab369c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_assistant_data_analysis",
        sa.Column("id", sa.String(length=36), nullable=False, comment="记录ID，使用UUID"),
        sa.Column("assistant_id", sa.String(length=36), nullable=False, comment="AI助手ID"),
        sa.Column("database_name", sa.String(length=100), nullable=False, comment="数据库名"),
        sa.Column("table_name", sa.String(length=100), nullable=False, comment="表名"),
        sa.Column("field_id", sa.String(length=100), nullable=False, comment="字段ID"),
        sa.Column("result_summary", sa.Text(), nullable=True, comment="分析结果摘要"),
        sa.Column("analysis_time", sa.DateTime(), nullable=False, comment="分析时间"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        comment="AI助手分析数据记录表",
    )
    op.create_index(
        op.f("ix_ai_assistant_data_analysis_assistant_id"), "ai_assistant_data_analysis", ["assistant_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_assistant_data_analysis_database_name"),
        "ai_assistant_data_analysis",
        ["database_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_assistant_data_analysis_field_id"), "ai_assistant_data_analysis", ["field_id"], unique=False
    )
    op.create_index(op.f("ix_ai_assistant_data_analysis_id"), "ai_assistant_data_analysis", ["id"], unique=False)
    op.create_index(
        op.f("ix_ai_assistant_data_analysis_table_name"), "ai_assistant_data_analysis", ["table_name"], unique=False
    )
    op.create_table(
        "ai_assistant_type",
        sa.Column("id", sa.String(length=36), nullable=False, comment="助手类型ID，使用UUID"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="助手类型名称"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        comment="助手类型表",
    )
    op.create_index(op.f("ix_ai_assistant_type_id"), "ai_assistant_type", ["id"], unique=False)
    op.create_index(op.f("ix_ai_assistant_type_name"), "ai_assistant_type", ["name"], unique=True)
    op.create_table(
        "ai_assistants",
        sa.Column("id", sa.String(length=50), nullable=False, comment="助手ID"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="助手名称"),
        sa.Column("type", sa.String(length=50), nullable=False, comment="助手类型"),
        sa.Column("ai_model_id", sa.String(length=50), nullable=False, comment="AI模型ID"),
        sa.Column("assistant_type_id", sa.String(length=50), nullable=False, comment="助手类型ID"),
        sa.Column("avatar", sa.Text(), nullable=True, comment="助手头像URL"),
        sa.Column("description", sa.Text(), nullable=True, comment="助手描述"),
        sa.Column("model_definition", sa.Text(), nullable=True, comment="模型定义"),
        sa.Column(
            "execution_frequency",
            sa.Enum("minutes", "hours", "daily", "weekly", "monthly", name="execution_frequency_enum"),
            nullable=False,
            comment="执行频率",
        ),
        sa.Column("execution_time", sa.String(length=10), nullable=True, comment="执行时间"),
        sa.Column("execution_minutes", sa.Integer(), nullable=True, comment="分钟间隔"),
        sa.Column("execution_hours", sa.Integer(), nullable=True, comment="小时间隔"),
        sa.Column("execution_weekday", sa.String(length=10), nullable=True, comment="执行星期"),
        sa.Column("execution_weekly_time", sa.String(length=10), nullable=True, comment="每周执行时间"),
        sa.Column("execution_day", sa.String(length=10), nullable=True, comment="执行日期"),
        sa.Column("execution_monthly_time", sa.String(length=10), nullable=True, comment="每月执行时间"),
        sa.Column("is_template", sa.Boolean(), nullable=False, comment="是否为模板"),
        sa.Column("is_view_myself", sa.Boolean(), nullable=False, comment="本人查看"),
        sa.Column("data_limit", sa.Integer(), nullable=False, comment="数据限制条数"),
        sa.Column("data_permission", sa.String(length=50), nullable=False, comment="数据权限"),
        sa.Column("data_permission_values", sa.JSON(), nullable=True, comment="数据权限具体值"),
        sa.Column(
            "data_time_range_type",
            sa.Enum("day", "month", "quarter", "year", name="data_time_range_enum"),
            nullable=False,
            comment="数据时间范围类型",
        ),
        sa.Column("data_time_value", sa.Integer(), nullable=False, comment="数据时间范围值"),
        sa.Column(
            "output_format",
            sa.Enum("table", "document", "both", name="output_format_enum"),
            nullable=False,
            comment="输出格式",
        ),
        sa.Column(
            "output_data",
            sa.Text(),
            nullable=True,
            comment="输出数据：table格式时存储JSON字符串，document格式时存储Markdown文本",
        ),
        sa.Column("include_charts", sa.Boolean(), nullable=False, comment="包含图表"),
        sa.Column("auto_export", sa.Boolean(), nullable=False, comment="自动导出"),
        sa.Column("export_formats", sa.JSON(), nullable=True, comment="导出格式"),
        sa.Column("document_template", sa.String(length=50), nullable=True, comment="文档模板"),
        sa.Column("custom_template", sa.Text(), nullable=True, comment="自定义模板"),
        sa.Column("settings", sa.JSON(), nullable=True, comment="其他设置"),
        sa.Column("ai_analysis_count", sa.Integer(), nullable=False, comment="AI分析次数"),
        sa.Column("last_analysis_time", sa.DateTime(), nullable=True, comment="最后一次分析时间"),
        sa.Column("status", sa.Boolean(), nullable=False, comment="状态"),
        sa.Column("created_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        comment="AI助手模型",
    )
    op.create_index(op.f("ix_ai_assistants_id"), "ai_assistants", ["id"], unique=False)
    op.create_table(
        "ai_data_permissions",
        sa.Column("id", sa.String(length=50), nullable=False, comment="权限ID"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="权限名称"),
        sa.Column(
            "permission_type",
            sa.Enum(
                "time_range",
                "user_scope",
                "ip_range",
                "data_scope",
                "field_level",
                "custom",
                name="permission_type_enum",
            ),
            nullable=False,
            comment="权限类型",
        ),
        sa.Column("permission_config", sa.JSON(), nullable=False, comment="权限配置"),
        sa.Column("description", sa.Text(), nullable=True, comment="权限描述"),
        sa.Column("status", sa.Boolean(), nullable=False, comment="状态"),
        sa.Column("created_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        comment="AI数据权限表",
    )
    op.create_index(op.f("ix_ai_data_permissions_id"), "ai_data_permissions", ["id"], unique=False)
    op.create_table(
        "ai_database_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("metadata_id", sa.String(length=100), nullable=False, comment="元数据唯一标识"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="名称（数据库名、表名、字段名）"),
        sa.Column("type", sa.String(length=20), nullable=False, comment="类型：database/table/field"),
        sa.Column("description", sa.Text(), nullable=True, comment="描述信息"),
        sa.Column("parent_id", sa.String(length=100), nullable=True, comment="父节点ID"),
        sa.Column("field_type", sa.String(length=100), nullable=True, comment="字段类型"),
        sa.Column(
            "is_nullable", sa.Boolean().with_variant(sa.INTEGER(), "postgresql"), nullable=True, comment="是否可为空"
        ),
        sa.Column("default_value", sa.Text(), nullable=True, comment="默认值"),
        sa.Column("table_rows", sa.BigInteger(), nullable=True, comment="表数据行数"),
        sa.Column("table_size", sa.String(length=20), nullable=True, comment="表大小"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, comment="更新时间"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        comment="数据库元数据表",
    )
    op.create_index(op.f("ix_ai_database_metadata_id"), "ai_database_metadata", ["id"], unique=False)
    op.create_index(op.f("ix_ai_database_metadata_metadata_id"), "ai_database_metadata", ["metadata_id"], unique=True)
    op.create_index(op.f("ix_ai_database_metadata_name"), "ai_database_metadata", ["name"], unique=False)
    op.create_index(op.f("ix_ai_database_metadata_parent_id"), "ai_database_metadata", ["parent_id"], unique=False)
    op.create_index(op.f("ix_ai_database_metadata_type"), "ai_database_metadata", ["type"], unique=False)
    op.create_table(
        "ai_datasource_collection",
        sa.Column("id", sa.String(length=50), nullable=False, comment="集合ID"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="集合名称"),
        sa.Column("query_name", sa.String(length=255), nullable=True, comment="查询名称"),
        sa.Column("description", sa.String(length=500), nullable=True, comment="集合描述"),
        sa.Column("status", sa.Boolean(), nullable=False, comment="启用状态"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        comment="数据源集合模型",
    )
    op.create_index(op.f("ix_ai_datasource_collection_id"), "ai_datasource_collection", ["id"], unique=False)
    op.create_table(
        "ai_models",
        sa.Column("id", sa.String(length=36), nullable=False, comment="模型ID，使用UUID"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="模型名称"),
        sa.Column("api_key", sa.Text(), nullable=False, comment="API密钥，加密存储"),
        sa.Column("model_type", sa.String(length=50), nullable=False, comment="模型类型"),
        sa.Column("model", sa.String(length=100), nullable=False, comment="模型名称/标识符，如gpt-4-turbo"),
        sa.Column("temperature", sa.Float(), nullable=False, comment="温度参数，值范围0-1"),
        sa.Column("base_url", sa.String(length=500), nullable=True, comment="API基础URL"),
        sa.Column("status", sa.Boolean(), nullable=False, comment="状态：1=启用，0=禁用"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        comment="AI模型配置表",
    )
    op.create_index(op.f("ix_ai_models_id"), "ai_models", ["id"], unique=False)
    op.create_index(op.f("ix_ai_models_model_type"), "ai_models", ["model_type"], unique=False)
    op.create_index(op.f("ix_ai_models_name"), "ai_models", ["name"], unique=False)
    op.create_index(op.f("ix_ai_models_status"), "ai_models", ["status"], unique=False)
    op.create_table(
        "ai_notification_methods",
        sa.Column("id", sa.String(length=50), nullable=False, comment="通知方式ID"),
        sa.Column("name", sa.String(length=50), nullable=False, comment="通知方式名称"),
        sa.Column(
            "type",
            sa.Enum("email", "sms", "dingtalk", "wechat_work", "feishu", name="notification_type_enum"),
            nullable=False,
            comment="通知类型",
        ),
        sa.Column("config", sa.JSON(), nullable=True, comment="配置信息"),
        sa.Column("status", sa.Boolean(), nullable=False, comment="状态"),
        sa.Column("created_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        comment="AI通知方式表",
    )
    op.create_index(op.f("ix_ai_notification_methods_id"), "ai_notification_methods", ["id"], unique=False)
    op.create_table(
        "ai_personnel",
        sa.Column("id", sa.String(length=50), nullable=False, comment="人员ID"),
        sa.Column("name", sa.String(length=50), nullable=False, comment="姓名"),
        sa.Column("email", sa.String(length=100), nullable=True, comment="邮箱"),
        sa.Column("phone", sa.String(length=20), nullable=True, comment="电话"),
        sa.Column("department", sa.String(length=100), nullable=True, comment="部门"),
        sa.Column("position", sa.String(length=100), nullable=True, comment="职位"),
        sa.Column("status", sa.Boolean(), nullable=False, comment="状态"),
        sa.Column("created_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        comment="AI人员表",
    )
    op.create_index(op.f("ix_ai_personnel_id"), "ai_personnel", ["id"], unique=False)
    op.create_table(
        "ai_training_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("model_id", sa.String(length=36), nullable=False, comment="关联的AI模型ID"),
        sa.Column("model_name", sa.String(length=100), nullable=False, comment="模型名称"),
        sa.Column(
            "log_type",
            sa.String(length=50),
            nullable=False,
            comment="日志类型（如：ai_assistant，risk_control_assistant）",
        ),
        sa.Column("prompt_template", mysql.JSON(), nullable=True, comment="使用的提示词模板"),
        sa.Column("base_info", mysql.JSON(), nullable=True, comment="基础信息"),
        sa.Column("data", mysql.JSON(), nullable=True, comment="数据"),
        sa.Column("assistant_id", sa.String(length=36), nullable=True, comment="AI助手ID"),
        sa.Column("success", sa.Boolean(), nullable=False, comment="是否成功"),
        sa.Column("score", sa.Float(), nullable=True, comment="评分/准确率"),
        sa.Column("content", sa.Text(), nullable=True, comment="内容"),
        sa.Column("ai_response", mysql.JSON(), nullable=True, comment="AI响应"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="记录创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=False, comment="记录更新时间"),
        sa.PrimaryKeyConstraint("id"),
        comment="AI模型训练操作记录表",
    )
    op.create_index(op.f("ix_ai_training_logs_id"), "ai_training_logs", ["id"], unique=False)
    op.create_index(op.f("ix_ai_training_logs_model_id"), "ai_training_logs", ["model_id"], unique=False)
    op.create_table(
        "client_user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("uuid", sa.String(length=50), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("avatar", sa.String(length=255), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
        comment="客户端用户模型",
    )
    op.create_index(op.f("ix_client_user_email"), "client_user", ["email"], unique=True)
    op.create_index(op.f("ix_client_user_id"), "client_user", ["id"], unique=False)
    op.create_index(op.f("ix_client_user_username"), "client_user", ["username"], unique=True)
    op.create_table(
        "gen_business",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("app_name", sa.String(length=50), nullable=False, comment="应用名称（英文）"),
        sa.Column("table_name", sa.String(length=255), nullable=False, comment="表名称（英文）"),
        sa.Column("doc_comment", sa.String(length=255), nullable=False, comment="文档注释（用于函数/参数文档）"),
        sa.Column("table_comment", sa.String(length=255), nullable=True, comment="表描述"),
        sa.Column("class_name", sa.String(length=50), nullable=True, comment="基础类名（默认为英文表名称）"),
        sa.Column("schema_name", sa.String(length=50), nullable=True, comment="Schema 名称 (默认为英文表名称)"),
        sa.Column("filename", sa.String(length=50), nullable=True, comment="基础文件名（默认为英文表名称）"),
        sa.Column("default_datetime_column", sa.Boolean(), nullable=False, comment="是否存在默认时间列"),
        sa.Column("api_version", sa.String(length=20), nullable=False, comment="代码生成 api 版本，默认为 v1"),
        sa.Column("gen_path", sa.String(length=255), nullable=True, comment="代码生成路径（默认为 app 根路径）"),
        sa.Column("remark", mysql.LONGTEXT().with_variant(sa.TEXT(), "postgresql"), nullable=True, comment="备注"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("table_name"),
        comment="代码生成业务表",
    )
    op.create_index(op.f("ix_gen_business_id"), "gen_business", ["id"], unique=False)
    op.create_table(
        "risk_assistant",
        sa.Column("id", sa.String(length=36), nullable=False, comment="风控助手ID，使用UUID"),
        sa.Column("risk_type", sa.String(length=100), nullable=True, comment="风险类型"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="风控助手名称"),
        sa.Column("ai_model_id", sa.String(length=36), nullable=False, comment="使用的AI模型ID，关联ai_model表"),
        sa.Column("role", sa.String(length=200), nullable=False, comment="角色定义"),
        sa.Column("background", sa.Text(), nullable=True, comment="背景描述"),
        sa.Column("task_prompt", sa.Text(), nullable=False, comment="任务提示词"),
        sa.Column("variable_config", sa.Text(), nullable=True, comment="变量配置，JSON格式存储"),
        sa.Column("report_config", sa.Text(), nullable=True, comment="报告配置，JSON格式存储"),
        sa.Column("status", sa.Boolean(), nullable=False, comment="状态：True-启用，False-禁用"),
        sa.Column("ai_analysis_count", sa.Integer(), nullable=False, comment="AI分析次数"),
        sa.Column("last_analysis_time", sa.DateTime(), nullable=True, comment="最后一次分析时间"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        comment="风控助手表",
    )
    op.create_index(op.f("ix_risk_assistant_id"), "risk_assistant", ["id"], unique=False)
    op.create_index(op.f("ix_risk_assistant_name"), "risk_assistant", ["name"], unique=True)
    op.create_table(
        "risk_level",
        sa.Column("id", sa.String(length=36), nullable=False, comment="风控等级ID，使用UUID"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="风控等级名称"),
        sa.Column("start_score", sa.Integer(), nullable=False, comment="评分范围开始分"),
        sa.Column("end_score", sa.Integer(), nullable=False, comment="评分范围结束分"),
        sa.Column("description", sa.Text(), nullable=True, comment="风控等级描述"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        comment="风控等级表",
    )
    op.create_index(op.f("ix_risk_level_id"), "risk_level", ["id"], unique=False)
    op.create_index(op.f("ix_risk_level_name"), "risk_level", ["name"], unique=True)
    op.create_table(
        "risk_member_analysis",
        sa.Column("id", sa.String(length=36), nullable=False, comment="记录ID，使用UUID"),
        sa.Column("member_id", sa.String(length=36), nullable=False, comment="员工ID"),
        sa.Column("risk_type", sa.String(length=50), nullable=False, comment="风险类型"),
        sa.Column("analysis_time", sa.DateTime(), nullable=False, comment="分析时间"),
        sa.Column("remark", sa.Text(), nullable=True, comment="备注"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        comment="风控员工分析记录表",
    )
    op.create_index(op.f("ix_risk_member_analysis_id"), "risk_member_analysis", ["id"], unique=False)
    op.create_index(op.f("ix_risk_member_analysis_member_id"), "risk_member_analysis", ["member_id"], unique=False)
    op.create_index(op.f("ix_risk_member_analysis_risk_type"), "risk_member_analysis", ["risk_type"], unique=False)
    op.create_table(
        "risk_tag_category",
        sa.Column("id", sa.String(length=36), nullable=False, comment="标签分类ID，使用UUID"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="分类名称"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        comment="风控标签分类表",
    )
    op.create_index(op.f("ix_risk_tag_category_id"), "risk_tag_category", ["id"], unique=False)
    op.create_index(op.f("ix_risk_tag_category_name"), "risk_tag_category", ["name"], unique=True)
    op.create_table(
        "sys_config",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("name", sa.String(length=20), nullable=False, comment="名称"),
        sa.Column("type", sa.String(length=20), nullable=True, comment="类型"),
        sa.Column("key", sa.String(length=50), nullable=False, comment="键名"),
        sa.Column("value", mysql.LONGTEXT().with_variant(sa.TEXT(), "postgresql"), nullable=False, comment="键值"),
        sa.Column(
            "is_frontend", sa.Boolean().with_variant(sa.INTEGER(), "postgresql"), nullable=False, comment="是否前端"
        ),
        sa.Column("remark", mysql.LONGTEXT().with_variant(sa.TEXT(), "postgresql"), nullable=True, comment="备注"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
        comment="参数配置表",
    )
    op.create_index(op.f("ix_sys_config_id"), "sys_config", ["id"], unique=False)
    op.create_table(
        "sys_data_scope",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("name", sa.String(length=50), nullable=False, comment="名称"),
        sa.Column("status", sa.Integer(), nullable=False, comment="状态（0停用 1正常）"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        comment="数据范围表",
    )
    op.create_index(op.f("ix_sys_data_scope_id"), "sys_data_scope", ["id"], unique=False)
    op.create_table(
        "sys_dept",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("name", sa.String(length=50), nullable=False, comment="部门名称"),
        sa.Column("sort", sa.Integer(), nullable=False, comment="排序"),
        sa.Column("leader", sa.String(length=20), nullable=True, comment="负责人"),
        sa.Column("phone", sa.String(length=11), nullable=True, comment="手机"),
        sa.Column("email", sa.String(length=50), nullable=True, comment="邮箱"),
        sa.Column("status", sa.Integer(), nullable=False, comment="部门状态(0停用 1正常)"),
        sa.Column(
            "del_flag",
            sa.Boolean().with_variant(sa.INTEGER(), "postgresql"),
            nullable=False,
            comment="删除标志（0删除 1存在）",
        ),
        sa.Column("parent_id", sa.Integer(), nullable=True, comment="父部门ID"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(["parent_id"], ["sys_dept.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        comment="部门表",
    )
    op.create_index(op.f("ix_sys_dept_id"), "sys_dept", ["id"], unique=False)
    op.create_index(op.f("ix_sys_dept_parent_id"), "sys_dept", ["parent_id"], unique=False)
    op.create_table(
        "sys_dict_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("name", sa.String(length=32), nullable=False, comment="字典类型名称"),
        sa.Column("code", sa.String(length=32), nullable=False, comment="字典类型编码"),
        sa.Column("status", sa.Integer(), nullable=False, comment="状态（0停用 1正常）"),
        sa.Column("remark", mysql.LONGTEXT().with_variant(sa.TEXT(), "postgresql"), nullable=True, comment="备注"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        comment="字典类型表",
    )
    op.create_index(op.f("ix_sys_dict_type_id"), "sys_dict_type", ["id"], unique=False)
    op.create_table(
        "sys_login_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("user_uuid", sa.String(length=50), nullable=False, comment="用户UUID"),
        sa.Column("username", sa.String(length=20), nullable=False, comment="用户名"),
        sa.Column("status", sa.Integer(), nullable=False, comment="登录状态(0失败 1成功)"),
        sa.Column("ip", sa.String(length=50), nullable=False, comment="登录IP地址"),
        sa.Column("country", sa.String(length=50), nullable=True, comment="国家"),
        sa.Column("region", sa.String(length=50), nullable=True, comment="地区"),
        sa.Column("city", sa.String(length=50), nullable=True, comment="城市"),
        sa.Column("user_agent", sa.String(length=255), nullable=False, comment="请求头"),
        sa.Column("os", sa.String(length=50), nullable=True, comment="操作系统"),
        sa.Column("browser", sa.String(length=50), nullable=True, comment="浏览器"),
        sa.Column("device", sa.String(length=50), nullable=True, comment="设备"),
        sa.Column("msg", mysql.LONGTEXT().with_variant(sa.TEXT(), "postgresql"), nullable=False, comment="提示消息"),
        sa.Column("login_time", sa.DateTime(timezone=True), nullable=False, comment="登录时间"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.PrimaryKeyConstraint("id"),
        comment="登录日志表",
    )
    op.create_index(op.f("ix_sys_login_log_id"), "sys_login_log", ["id"], unique=False)
    op.create_table(
        "sys_menu",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("title", sa.String(length=50), nullable=False, comment="菜单标题"),
        sa.Column("name", sa.String(length=50), nullable=False, comment="菜单名称"),
        sa.Column("path", sa.String(length=200), nullable=True, comment="路由地址"),
        sa.Column("sort", sa.Integer(), nullable=False, comment="排序"),
        sa.Column("icon", sa.String(length=100), nullable=True, comment="菜单图标"),
        sa.Column("type", sa.Integer(), nullable=False, comment="菜单类型（0目录 1菜单 2按钮 3内嵌 4外链）"),
        sa.Column("component", sa.String(length=255), nullable=True, comment="组件路径"),
        sa.Column("perms", sa.String(length=100), nullable=True, comment="权限标识"),
        sa.Column("status", sa.Integer(), nullable=False, comment="菜单状态（0停用 1正常）"),
        sa.Column("display", sa.Integer(), nullable=False, comment="是否显示（0否 1是）"),
        sa.Column("cache", sa.Integer(), nullable=False, comment="是否缓存（0否 1是）"),
        sa.Column("link", mysql.LONGTEXT().with_variant(sa.TEXT(), "postgresql"), nullable=True, comment="外链地址"),
        sa.Column("remark", mysql.LONGTEXT().with_variant(sa.TEXT(), "postgresql"), nullable=True, comment="备注"),
        sa.Column("parent_id", sa.Integer(), nullable=True, comment="父菜单ID"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(["parent_id"], ["sys_menu.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        comment="菜单表",
    )
    op.create_index(op.f("ix_sys_menu_id"), "sys_menu", ["id"], unique=False)
    op.create_index(op.f("ix_sys_menu_parent_id"), "sys_menu", ["parent_id"], unique=False)
    op.create_table(
        "sys_notice",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("title", sa.String(length=50), nullable=False, comment="标题"),
        sa.Column("type", sa.Integer(), nullable=False, comment="类型（0：通知、1：公告）"),
        sa.Column("author", sa.String(length=16), nullable=False, comment="作者"),
        sa.Column("source", sa.String(length=50), nullable=False, comment="信息来源"),
        sa.Column("status", sa.Integer(), nullable=False, comment="状态（0：隐藏、1：显示）"),
        sa.Column("content", mysql.LONGTEXT().with_variant(sa.TEXT(), "postgresql"), nullable=False, comment="内容"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        comment="系统通知公告表",
    )
    op.create_index(op.f("ix_sys_notice_id"), "sys_notice", ["id"], unique=False)
    op.create_table(
        "sys_opera_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("trace_id", sa.String(length=32), nullable=False, comment="请求跟踪 ID"),
        sa.Column("username", sa.String(length=20), nullable=True, comment="用户名"),
        sa.Column("method", sa.String(length=20), nullable=False, comment="请求类型"),
        sa.Column("title", sa.String(length=255), nullable=False, comment="操作模块"),
        sa.Column("path", sa.String(length=500), nullable=False, comment="请求路径"),
        sa.Column("ip", sa.String(length=50), nullable=False, comment="IP地址"),
        sa.Column("country", sa.String(length=50), nullable=True, comment="国家"),
        sa.Column("region", sa.String(length=50), nullable=True, comment="地区"),
        sa.Column("city", sa.String(length=50), nullable=True, comment="城市"),
        sa.Column("user_agent", sa.String(length=255), nullable=False, comment="请求头"),
        sa.Column("os", sa.String(length=50), nullable=True, comment="操作系统"),
        sa.Column("browser", sa.String(length=50), nullable=True, comment="浏览器"),
        sa.Column("device", sa.String(length=50), nullable=True, comment="设备"),
        sa.Column("args", mysql.JSON(), nullable=True, comment="请求参数"),
        sa.Column("status", sa.Integer(), nullable=False, comment="操作状态（0异常 1正常）"),
        sa.Column("code", sa.String(length=20), nullable=False, comment="操作状态码"),
        sa.Column("msg", mysql.LONGTEXT().with_variant(sa.TEXT(), "postgresql"), nullable=True, comment="提示消息"),
        sa.Column("cost_time", sa.Float(), nullable=False, comment="请求耗时（ms）"),
        sa.Column("opera_time", sa.DateTime(timezone=True), nullable=False, comment="操作时间"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.PrimaryKeyConstraint("id"),
        comment="操作日志表",
    )
    op.create_index(op.f("ix_sys_opera_log_id"), "sys_opera_log", ["id"], unique=False)
    op.create_table(
        "sys_role",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("name", sa.String(length=20), nullable=False, comment="角色名称"),
        sa.Column("status", sa.Integer(), nullable=False, comment="角色状态（0停用 1正常）"),
        sa.Column(
            "is_filter_scopes",
            sa.Boolean().with_variant(sa.INTEGER(), "postgresql"),
            nullable=False,
            comment="过滤数据权限(0否 1是)",
        ),
        sa.Column("remark", mysql.LONGTEXT().with_variant(sa.TEXT(), "postgresql"), nullable=True, comment="备注"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        comment="角色表",
    )
    op.create_index(op.f("ix_sys_role_id"), "sys_role", ["id"], unique=False)
    op.create_table(
        "ai_assistant_data_sources",
        sa.Column("id", sa.String(length=50), nullable=False, comment="关联ID"),
        sa.Column("assistant_id", sa.String(length=50), nullable=False, comment="助手ID"),
        sa.Column("collection_id", sa.String(length=50), nullable=False, comment="数据源集合ID"),
        sa.Column("query_name", sa.String(length=255), nullable=True, comment="查询名称"),
        sa.Column("tables", sa.JSON(), nullable=True, comment="数据表配置"),
        sa.Column("created_time", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(["assistant_id"], ["ai_assistants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assistant_id", "collection_id", name="uk_assistant_collection"),
    )
    op.create_index(op.f("ix_ai_assistant_data_sources_id"), "ai_assistant_data_sources", ["id"], unique=False)
    op.create_table(
        "ai_assistant_notifications",
        sa.Column("id", sa.String(length=50), nullable=False, comment="关联ID"),
        sa.Column("assistant_id", sa.String(length=50), nullable=False, comment="助手ID"),
        sa.Column("notification_id", sa.String(length=50), nullable=False, comment="通知方式ID"),
        sa.Column("created_time", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(["assistant_id"], ["ai_assistants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["notification_id"], ["ai_notification_methods.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assistant_id", "notification_id", name="uk_assistant_notification"),
    )
    op.create_index(op.f("ix_ai_assistant_notifications_id"), "ai_assistant_notifications", ["id"], unique=False)
    op.create_table(
        "ai_assistant_permissions",
        sa.Column("id", sa.String(length=50), nullable=False, comment="关联ID"),
        sa.Column("assistant_id", sa.String(length=50), nullable=False, comment="助手ID"),
        sa.Column("permission_id", sa.String(length=50), nullable=False, comment="数据权限ID"),
        sa.Column("created_time", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(["assistant_id"], ["ai_assistants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["permission_id"], ["ai_data_permissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assistant_id", "permission_id", name="uk_assistant_permission"),
    )
    op.create_index(op.f("ix_ai_assistant_permissions_id"), "ai_assistant_permissions", ["id"], unique=False)
    op.create_table(
        "ai_assistant_personnel",
        sa.Column("id", sa.String(length=50), nullable=False, comment="关联ID"),
        sa.Column("assistant_id", sa.String(length=50), nullable=False, comment="助手ID"),
        sa.Column("personnel_id", sa.String(length=50), nullable=False, comment="人员ID"),
        sa.Column("created_time", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(["assistant_id"], ["ai_assistants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["personnel_id"], ["ai_personnel.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assistant_id", "personnel_id", name="uk_assistant_personnel"),
    )
    op.create_index(op.f("ix_ai_assistant_personnel_id"), "ai_assistant_personnel", ["id"], unique=False)
    op.create_table(
        "ai_assistant_report_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="报告ID"),
        sa.Column("assistant_id", sa.String(length=36), nullable=False, comment="AI助手ID"),
        sa.Column("model_id", sa.String(length=36), nullable=False, comment="AI模型ID"),
        sa.Column("member_ids", sa.String(length=1500), nullable=False, comment="用户ID列表"),
        sa.Column("sql_data", sa.Text(), nullable=True, comment="SQL查询数据，JSON格式"),
        sa.Column("prompt_data", sa.Text(), nullable=True, comment="提示词数据，JSON格式"),
        sa.Column("input_prompt", sa.Text(), nullable=True, comment="输入提示词"),
        sa.Column("report_score", sa.Float(), nullable=False, comment="报告评分"),
        sa.Column("report_result", sa.Text(), nullable=True, comment="报告结果"),
        sa.Column("report_table", sa.Text(), nullable=True, comment="报告表格数据，JSON格式"),
        sa.Column("report_document", sa.Text(), nullable=True, comment="报告文档"),
        sa.Column("ai_response", sa.JSON(), nullable=True, comment="AI响应"),
        sa.Column("report_status", sa.Boolean(), nullable=False, comment="报告状态"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["ai_assistants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="AI助手报告记录表",
    )
    op.create_index(op.f("ix_ai_assistant_report_log_id"), "ai_assistant_report_log", ["id"], unique=False)
    op.create_index(
        op.f("ix_ai_assistant_report_log_member_ids"), "ai_assistant_report_log", ["member_ids"], unique=False
    )
    op.create_index(op.f("ix_ai_assistant_report_log_model_id"), "ai_assistant_report_log", ["model_id"], unique=False)
    op.create_table(
        "ai_assistant_templates",
        sa.Column("id", sa.String(length=50), nullable=False, comment="模板ID"),
        sa.Column("assistant_id", sa.String(length=50), nullable=False, comment="助手ID"),
        sa.Column("is_open", sa.Boolean(), nullable=False, comment="是否开启"),
        sa.Column("created_time", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(["assistant_id"], ["ai_assistants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assistant_id"),
        sa.UniqueConstraint("assistant_id", name="uk_assistant_template"),
    )
    op.create_index(op.f("ix_ai_assistant_templates_id"), "ai_assistant_templates", ["id"], unique=False)
    op.create_table(
        "ai_chat",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("model_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["ai_models.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["client_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="AI Chat model for storing chat sessions",
    )
    op.create_index(op.f("ix_ai_chat_user_id"), "ai_chat", ["user_id"], unique=False)
    op.create_table(
        "ai_datasource",
        sa.Column("id", sa.String(length=50), nullable=False, comment="数据源ID"),
        sa.Column("collection_id", sa.String(length=50), nullable=False, comment="所属集合ID"),
        sa.Column("database_name", sa.String(length=100), nullable=False, comment="数据库名称"),
        sa.Column("table_name", sa.String(length=100), nullable=False, comment="表名"),
        sa.Column("description", sa.String(length=500), nullable=True, comment="数据源描述"),
        sa.Column("data_count", sa.Integer(), nullable=True, comment="数据量"),
        sa.Column("relation_field", sa.String(length=100), nullable=True, comment="关联字段名"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(["collection_id"], ["ai_datasource_collection.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        comment="数据源模型",
    )
    op.create_index(op.f("ix_ai_datasource_id"), "ai_datasource", ["id"], unique=False)
    op.create_table(
        "gen_column",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("name", sa.String(length=50), nullable=False, comment="列名称"),
        sa.Column("comment", sa.String(length=255), nullable=True, comment="列描述"),
        sa.Column("type", sa.String(length=20), nullable=False, comment="SQLA 模型列类型"),
        sa.Column("pd_type", sa.String(length=20), nullable=False, comment="列类型对应的 pydantic 类型"),
        sa.Column("default", mysql.LONGTEXT().with_variant(sa.TEXT(), "postgresql"), nullable=True, comment="列默认值"),
        sa.Column("sort", sa.Integer(), nullable=True, comment="列排序"),
        sa.Column("length", sa.Integer(), nullable=False, comment="列长度"),
        sa.Column("is_pk", sa.Boolean(), nullable=False, comment="是否主键"),
        sa.Column("is_nullable", sa.Boolean(), nullable=False, comment="是否可为空"),
        sa.Column("gen_business_id", sa.Integer(), nullable=False, comment="代码生成业务ID"),
        sa.ForeignKeyConstraint(["gen_business_id"], ["gen_business.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        comment="代码生成模型列表",
    )
    op.create_index(op.f("ix_gen_column_id"), "gen_column", ["id"], unique=False)
    op.create_table(
        "risk_report_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="报告ID"),
        sa.Column("assistant_id", sa.String(length=36), nullable=False, comment="风控助手ID"),
        sa.Column("model_id", sa.String(length=36), nullable=False, comment="AI模型ID"),
        sa.Column("risk_type", sa.String(length=50), nullable=False, comment="风险类型"),
        sa.Column("member_id", sa.String(length=36), nullable=False, comment="用户ID"),
        sa.Column("report_score", sa.Float(precision=53), nullable=False, comment="报告评分"),
        sa.Column("sql_data", sa.Text(), nullable=True, comment="SQL查询数据，JSON格式"),
        sa.Column("prompt_data", sa.Text(), nullable=True, comment="提示词数据，JSON格式"),
        sa.Column("input_prompt", sa.Text(), nullable=True, comment="输入提示词"),
        sa.Column("score", sa.Float(precision=53), nullable=True, comment="风险评分"),
        sa.Column("report_tags", sa.String(length=1000), nullable=True, comment="报告标签"),
        sa.Column("report_result", sa.Text(), nullable=True, comment="报告结果"),
        sa.Column("report_table", sa.Text(), nullable=True, comment="报告表格数据，JSON格式"),
        sa.Column("report_document", sa.Text(), nullable=True, comment="报告文档"),
        sa.Column("handle_suggestion", sa.Text(), nullable=True, comment="处理建议"),
        sa.Column("handle_result", sa.Text(), nullable=True, comment="处理结果"),
        sa.Column("handle_user", sa.String(length=50), nullable=True, comment="处理人"),
        sa.Column("handle_time", sa.DateTime(), nullable=True, comment="处理时间"),
        sa.Column("member_name", sa.String(length=50), nullable=True, comment="用户名称"),
        sa.Column("report_status", sa.Boolean(), nullable=False, comment="报告状态"),
        sa.Column("is_processed", sa.Boolean(), nullable=False, comment="是否需要处理"),
        sa.Column("ai_response", sa.JSON(), nullable=True, comment="AI响应"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["risk_assistant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="风控报告记录表",
    )
    op.create_index(op.f("ix_risk_report_log_id"), "risk_report_log", ["id"], unique=False)
    op.create_index(op.f("ix_risk_report_log_member_id"), "risk_report_log", ["member_id"], unique=False)
    op.create_index(op.f("ix_risk_report_log_model_id"), "risk_report_log", ["model_id"], unique=False)
    op.create_index(op.f("ix_risk_report_log_risk_type"), "risk_report_log", ["risk_type"], unique=False)
    op.create_table(
        "risk_tag",
        sa.Column("id", sa.String(length=36), nullable=False, comment="标签ID，使用UUID"),
        sa.Column("category_id", sa.String(length=36), nullable=False, comment="标签分类ID"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="标签名称"),
        sa.Column("description", sa.Text(), nullable=True, comment="标签描述"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["risk_tag_category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="风控标签表",
    )
    op.create_index(op.f("ix_risk_tag_category_id_fk"), "risk_tag", ["category_id"], unique=False)
    op.create_index(op.f("ix_risk_tag_id"), "risk_tag", ["id"], unique=False)
    op.create_index(op.f("ix_risk_tag_name"), "risk_tag", ["name"], unique=False)
    op.create_table(
        "sys_data_rule",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("name", sa.String(length=500), nullable=False, comment="名称"),
        sa.Column(
            "model", sa.String(length=50), nullable=False, comment="SQLA 模型名，对应 DATA_PERMISSION_MODELS 键名"
        ),
        sa.Column("column", sa.String(length=20), nullable=False, comment="模型字段名"),
        sa.Column("operator", sa.Integer(), nullable=False, comment="运算符（0：and、1：or）"),
        sa.Column(
            "expression",
            sa.Integer(),
            nullable=False,
            comment="表达式（0：==、1：!=、2：>、3：>=、4：<、5：<=、6：in、7：not_in）",
        ),
        sa.Column("value", sa.String(length=255), nullable=False, comment="规则值"),
        sa.Column("scope_id", sa.Integer(), nullable=True, comment="数据范围关联 ID"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(["scope_id"], ["sys_data_scope.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        comment="数据规则表",
    )
    op.create_index(op.f("ix_sys_data_rule_id"), "sys_data_rule", ["id"], unique=False)
    op.create_table(
        "sys_dict_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("label", sa.String(length=32), nullable=False, comment="字典标签"),
        sa.Column("value", sa.String(length=32), nullable=False, comment="字典值"),
        sa.Column("sort", sa.Integer(), nullable=False, comment="排序"),
        sa.Column("status", sa.Integer(), nullable=False, comment="状态（0停用 1正常）"),
        sa.Column("remark", mysql.LONGTEXT().with_variant(sa.TEXT(), "postgresql"), nullable=True, comment="备注"),
        sa.Column("type_id", sa.Integer(), nullable=False, comment="字典类型关联ID"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(["type_id"], ["sys_dict_type.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
        comment="字典数据表",
    )
    op.create_index(op.f("ix_sys_dict_data_id"), "sys_dict_data", ["id"], unique=False)
    op.create_table(
        "sys_role_data_scope",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("role_id", sa.Integer(), nullable=False, comment="角色 ID"),
        sa.Column("data_scope_id", sa.Integer(), nullable=False, comment="数据范围 ID"),
        sa.ForeignKeyConstraint(["data_scope_id"], ["sys_data_scope.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["sys_role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "role_id", "data_scope_id"),
    )
    op.create_index(op.f("ix_sys_role_data_scope_id"), "sys_role_data_scope", ["id"], unique=True)
    op.create_table(
        "sys_role_menu",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False, comment="主键ID"),
        sa.Column("role_id", sa.Integer(), nullable=False, comment="角色ID"),
        sa.Column("menu_id", sa.Integer(), nullable=False, comment="菜单ID"),
        sa.ForeignKeyConstraint(["menu_id"], ["sys_menu.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["sys_role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "role_id", "menu_id"),
    )
    op.create_index(op.f("ix_sys_role_menu_id"), "sys_role_menu", ["id"], unique=True)
    op.create_table(
        "sys_user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("uuid", sa.String(length=50), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=False, comment="用户名"),
        sa.Column("nickname", sa.String(length=20), nullable=False, comment="昵称"),
        sa.Column("password", sa.String(length=255), nullable=True, comment="密码"),
        sa.Column(
            "salt",
            sa.VARBINARY(length=255).with_variant(postgresql.BYTEA(length=255), "postgresql"),
            nullable=True,
            comment="加密盐",
        ),
        sa.Column("email", sa.String(length=50), nullable=False, comment="邮箱"),
        sa.Column(
            "is_superuser",
            sa.Boolean().with_variant(sa.INTEGER(), "postgresql"),
            nullable=False,
            comment="超级权限(0否 1是)",
        ),
        sa.Column(
            "is_staff",
            sa.Boolean().with_variant(sa.INTEGER(), "postgresql"),
            nullable=False,
            comment="后台管理登陆(0否 1是)",
        ),
        sa.Column("status", sa.Integer(), nullable=False, comment="用户账号状态(0停用 1正常)"),
        sa.Column(
            "is_multi_login",
            sa.Boolean().with_variant(sa.INTEGER(), "postgresql"),
            nullable=False,
            comment="是否重复登陆(0否 1是)",
        ),
        sa.Column("avatar", sa.String(length=255), nullable=True, comment="头像"),
        sa.Column("phone", sa.String(length=11), nullable=True, comment="手机号"),
        sa.Column("join_time", sa.DateTime(timezone=True), nullable=False, comment="注册时间"),
        sa.Column("last_login_time", sa.DateTime(timezone=True), nullable=True, comment="上次登录"),
        sa.Column("dept_id", sa.Integer(), nullable=True, comment="部门关联ID"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(["dept_id"], ["sys_dept.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nickname"),
        sa.UniqueConstraint("uuid"),
        comment="用户表",
    )
    op.create_index(op.f("ix_sys_user_email"), "sys_user", ["email"], unique=True)
    op.create_index(op.f("ix_sys_user_id"), "sys_user", ["id"], unique=False)
    op.create_index(op.f("ix_sys_user_status"), "sys_user", ["status"], unique=False)
    op.create_index(op.f("ix_sys_user_username"), "sys_user", ["username"], unique=True)
    op.create_table(
        "ai_chat_message",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("chat_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("query_data", sa.JSON(), nullable=True),
        sa.Column("response_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["ai_chat.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="AI Chat Message model for storing individual messages in a chat session",
    )
    op.create_index(op.f("ix_ai_chat_message_chat_id"), "ai_chat_message", ["chat_id"], unique=False)
    op.create_table(
        "sys_user_role",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False, comment="主键ID"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="用户ID"),
        sa.Column("role_id", sa.Integer(), nullable=False, comment="角色ID"),
        sa.ForeignKeyConstraint(["role_id"], ["sys_role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["sys_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "user_id", "role_id"),
    )
    op.create_index(op.f("ix_sys_user_role_id"), "sys_user_role", ["id"], unique=True)
    op.create_table(
        "sys_user_social",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("source", sa.String(length=20), nullable=False, comment="第三方用户来源"),
        sa.Column("open_id", sa.String(length=20), nullable=True, comment="第三方用户 open id"),
        sa.Column("sid", sa.String(length=20), nullable=True, comment="第三方用户 ID"),
        sa.Column("union_id", sa.String(length=20), nullable=True, comment="第三方用户 union id"),
        sa.Column("scope", sa.String(length=120), nullable=True, comment="第三方用户授予的权限"),
        sa.Column("code", sa.String(length=50), nullable=True, comment="用户的授权 code"),
        sa.Column("user_id", sa.Integer(), nullable=True, comment="用户关联ID"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(["user_id"], ["sys_user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        comment="用户社交表（OAuth2）",
    )
    op.create_index(op.f("ix_sys_user_social_id"), "sys_user_social", ["id"], unique=False)
    op.create_table(
        "mcp_query",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("chat_message_id", sa.String(length=36), nullable=False),
        sa.Column("query_type", sa.String(length=50), nullable=False),
        sa.Column("query_params", sa.JSON(), nullable=False),
        sa.Column("response_data", sa.JSON(), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["chat_message_id"],
            ["ai_chat_message.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="MCP Query model for tracking data queries made through the MCP service",
    )
    op.create_index(op.f("ix_mcp_query_chat_message_id"), "mcp_query", ["chat_message_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mcp_query_chat_message_id"), table_name="mcp_query")
    op.drop_table("mcp_query")
    op.drop_index(op.f("ix_sys_user_social_id"), table_name="sys_user_social")
    op.drop_table("sys_user_social")
    op.drop_index(op.f("ix_sys_user_role_id"), table_name="sys_user_role")
    op.drop_table("sys_user_role")
    op.drop_index(op.f("ix_ai_chat_message_chat_id"), table_name="ai_chat_message")
    op.drop_table("ai_chat_message")
    op.drop_index(op.f("ix_sys_user_username"), table_name="sys_user")
    op.drop_index(op.f("ix_sys_user_status"), table_name="sys_user")
    op.drop_index(op.f("ix_sys_user_id"), table_name="sys_user")
    op.drop_index(op.f("ix_sys_user_email"), table_name="sys_user")
    op.drop_table("sys_user")
    op.drop_index(op.f("ix_sys_role_menu_id"), table_name="sys_role_menu")
    op.drop_table("sys_role_menu")
    op.drop_index(op.f("ix_sys_role_data_scope_id"), table_name="sys_role_data_scope")
    op.drop_table("sys_role_data_scope")
    op.drop_index(op.f("ix_sys_dict_data_id"), table_name="sys_dict_data")
    op.drop_table("sys_dict_data")
    op.drop_index(op.f("ix_sys_data_rule_id"), table_name="sys_data_rule")
    op.drop_table("sys_data_rule")
    op.drop_index(op.f("ix_risk_tag_name"), table_name="risk_tag")
    op.drop_index(op.f("ix_risk_tag_id"), table_name="risk_tag")
    op.drop_index(op.f("ix_risk_tag_category_id_fk"), table_name="risk_tag")
    op.drop_table("risk_tag")
    op.drop_index(op.f("ix_risk_report_log_risk_type"), table_name="risk_report_log")
    op.drop_index(op.f("ix_risk_report_log_model_id"), table_name="risk_report_log")
    op.drop_index(op.f("ix_risk_report_log_member_id"), table_name="risk_report_log")
    op.drop_index(op.f("ix_risk_report_log_id"), table_name="risk_report_log")
    op.drop_table("risk_report_log")
    op.drop_index(op.f("ix_gen_column_id"), table_name="gen_column")
    op.drop_table("gen_column")
    op.drop_index(op.f("ix_ai_datasource_id"), table_name="ai_datasource")
    op.drop_table("ai_datasource")
    op.drop_index(op.f("ix_ai_chat_user_id"), table_name="ai_chat")
    op.drop_table("ai_chat")
    op.drop_index(op.f("ix_ai_assistant_templates_id"), table_name="ai_assistant_templates")
    op.drop_table("ai_assistant_templates")
    op.drop_index(op.f("ix_ai_assistant_report_log_model_id"), table_name="ai_assistant_report_log")
    op.drop_index(op.f("ix_ai_assistant_report_log_member_ids"), table_name="ai_assistant_report_log")
    op.drop_index(op.f("ix_ai_assistant_report_log_id"), table_name="ai_assistant_report_log")
    op.drop_table("ai_assistant_report_log")
    op.drop_index(op.f("ix_ai_assistant_personnel_id"), table_name="ai_assistant_personnel")
    op.drop_table("ai_assistant_personnel")
    op.drop_index(op.f("ix_ai_assistant_permissions_id"), table_name="ai_assistant_permissions")
    op.drop_table("ai_assistant_permissions")
    op.drop_index(op.f("ix_ai_assistant_notifications_id"), table_name="ai_assistant_notifications")
    op.drop_table("ai_assistant_notifications")
    op.drop_index(op.f("ix_ai_assistant_data_sources_id"), table_name="ai_assistant_data_sources")
    op.drop_table("ai_assistant_data_sources")
    op.drop_index(op.f("ix_sys_role_id"), table_name="sys_role")
    op.drop_table("sys_role")
    op.drop_index(op.f("ix_sys_opera_log_id"), table_name="sys_opera_log")
    op.drop_table("sys_opera_log")
    op.drop_index(op.f("ix_sys_notice_id"), table_name="sys_notice")
    op.drop_table("sys_notice")
    op.drop_index(op.f("ix_sys_menu_parent_id"), table_name="sys_menu")
    op.drop_index(op.f("ix_sys_menu_id"), table_name="sys_menu")
    op.drop_table("sys_menu")
    op.drop_index(op.f("ix_sys_login_log_id"), table_name="sys_login_log")
    op.drop_table("sys_login_log")
    op.drop_index(op.f("ix_sys_dict_type_id"), table_name="sys_dict_type")
    op.drop_table("sys_dict_type")
    op.drop_index(op.f("ix_sys_dept_parent_id"), table_name="sys_dept")
    op.drop_index(op.f("ix_sys_dept_id"), table_name="sys_dept")
    op.drop_table("sys_dept")
    op.drop_index(op.f("ix_sys_data_scope_id"), table_name="sys_data_scope")
    op.drop_table("sys_data_scope")
    op.drop_index(op.f("ix_sys_config_id"), table_name="sys_config")
    op.drop_table("sys_config")
    op.drop_index(op.f("ix_risk_tag_category_name"), table_name="risk_tag_category")
    op.drop_index(op.f("ix_risk_tag_category_id"), table_name="risk_tag_category")
    op.drop_table("risk_tag_category")
    op.drop_index(op.f("ix_risk_member_analysis_risk_type"), table_name="risk_member_analysis")
    op.drop_index(op.f("ix_risk_member_analysis_member_id"), table_name="risk_member_analysis")
    op.drop_index(op.f("ix_risk_member_analysis_id"), table_name="risk_member_analysis")
    op.drop_table("risk_member_analysis")
    op.drop_index(op.f("ix_risk_level_name"), table_name="risk_level")
    op.drop_index(op.f("ix_risk_level_id"), table_name="risk_level")
    op.drop_table("risk_level")
    op.drop_index(op.f("ix_risk_assistant_name"), table_name="risk_assistant")
    op.drop_index(op.f("ix_risk_assistant_id"), table_name="risk_assistant")
    op.drop_table("risk_assistant")
    op.drop_index(op.f("ix_gen_business_id"), table_name="gen_business")
    op.drop_table("gen_business")
    op.drop_index(op.f("ix_client_user_username"), table_name="client_user")
    op.drop_index(op.f("ix_client_user_id"), table_name="client_user")
    op.drop_index(op.f("ix_client_user_email"), table_name="client_user")
    op.drop_table("client_user")
    op.drop_index(op.f("ix_ai_training_logs_model_id"), table_name="ai_training_logs")
    op.drop_index(op.f("ix_ai_training_logs_id"), table_name="ai_training_logs")
    op.drop_table("ai_training_logs")
    op.drop_index(op.f("ix_ai_personnel_id"), table_name="ai_personnel")
    op.drop_table("ai_personnel")
    op.drop_index(op.f("ix_ai_notification_methods_id"), table_name="ai_notification_methods")
    op.drop_table("ai_notification_methods")
    op.drop_index(op.f("ix_ai_models_status"), table_name="ai_models")
    op.drop_index(op.f("ix_ai_models_name"), table_name="ai_models")
    op.drop_index(op.f("ix_ai_models_model_type"), table_name="ai_models")
    op.drop_index(op.f("ix_ai_models_id"), table_name="ai_models")
    op.drop_table("ai_models")
    op.drop_index(op.f("ix_ai_datasource_collection_id"), table_name="ai_datasource_collection")
    op.drop_table("ai_datasource_collection")
    op.drop_index(op.f("ix_ai_database_metadata_type"), table_name="ai_database_metadata")
    op.drop_index(op.f("ix_ai_database_metadata_parent_id"), table_name="ai_database_metadata")
    op.drop_index(op.f("ix_ai_database_metadata_name"), table_name="ai_database_metadata")
    op.drop_index(op.f("ix_ai_database_metadata_metadata_id"), table_name="ai_database_metadata")
    op.drop_index(op.f("ix_ai_database_metadata_id"), table_name="ai_database_metadata")
    op.drop_table("ai_database_metadata")
    op.drop_index(op.f("ix_ai_data_permissions_id"), table_name="ai_data_permissions")
    op.drop_table("ai_data_permissions")
    op.drop_index(op.f("ix_ai_assistants_id"), table_name="ai_assistants")
    op.drop_table("ai_assistants")
    op.drop_index(op.f("ix_ai_assistant_type_name"), table_name="ai_assistant_type")
    op.drop_index(op.f("ix_ai_assistant_type_id"), table_name="ai_assistant_type")
    op.drop_table("ai_assistant_type")
    op.drop_index(op.f("ix_ai_assistant_data_analysis_table_name"), table_name="ai_assistant_data_analysis")
    op.drop_index(op.f("ix_ai_assistant_data_analysis_id"), table_name="ai_assistant_data_analysis")
    op.drop_index(op.f("ix_ai_assistant_data_analysis_field_id"), table_name="ai_assistant_data_analysis")
    op.drop_index(op.f("ix_ai_assistant_data_analysis_database_name"), table_name="ai_assistant_data_analysis")
    op.drop_index(op.f("ix_ai_assistant_data_analysis_assistant_id"), table_name="ai_assistant_data_analysis")
    op.drop_table("ai_assistant_data_analysis")
    # ### end Alembic commands ###
