"""add monitor_task_id to task_scheduler_execution

Revision ID: d6c0fd3a9507
Revises: 085797683a64
Create Date: 2025-08-26 22:06:10.717082

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d6c0fd3a9507"
down_revision = "085797683a64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_scheduler_execution",
        sa.Column("monitor_task_id", sa.String(length=155), nullable=True, comment="监控任务ID"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_scheduler_execution", "monitor_task_id")
    # ### end Alembic commands ###
