"""create_ai_assistant_report_user_read_table

Revision ID: create_ai_assistant_report_user_read_table
Revises: d50b07ca4a17
Create Date: 2025-09-01 12:30:00.000000

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f6"
down_revision = "d50b07ca4a17"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if not inspector.has_table("ai_assistant_report_user_read"):
        op.create_table(
            "ai_assistant_report_user_read",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="关系ID"),
            sa.Column("report_id", sa.Integer(), nullable=False, comment="报告ID"),
            sa.Column("user_id", sa.BigInteger(), nullable=False, comment="用户ID"),
            sa.Column("is_read", sa.Boolean(), nullable=False, default=False, comment="是否已读(0: 未读, 1: 已读)"),
            sa.Column("read_time", sa.DateTime(timezone=True), nullable=True, comment="阅读时间"),
            sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
            sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
            sa.ForeignKeyConstraint(["report_id"], ["ai_assistant_report_log.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["user_id"], ["sys_user.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("report_id", "user_id", name="uk_report_user_read"),
            comment="AI助手报告用户阅读关系表",
        )
        # 创建索引以提高查询性能
        op.create_index(
            "ix_ai_assistant_report_user_read_report_id", "ai_assistant_report_user_read", ["report_id"], unique=False
        )
        op.create_index(
            "ix_ai_assistant_report_user_read_user_id", "ai_assistant_report_user_read", ["user_id"], unique=False
        )
        op.create_index(
            "ix_ai_assistant_report_user_read_is_read", "ai_assistant_report_user_read", ["is_read"], unique=False
        )
        op.create_index(
            "ix_ai_assistant_report_user_read_created_time",
            "ai_assistant_report_user_read",
            ["created_time"],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ai_assistant_report_user_read_created_time", table_name="ai_assistant_report_user_read")
    op.drop_index("ix_ai_assistant_report_user_read_is_read", table_name="ai_assistant_report_user_read")
    op.drop_index("ix_ai_assistant_report_user_read_user_id", table_name="ai_assistant_report_user_read")
    op.drop_index("ix_ai_assistant_report_user_read_report_id", table_name="ai_assistant_report_user_read")
    op.drop_table("ai_assistant_report_user_read")
    # ### end Alembic commands ###
