"""修复deleted_at字段定义统一性问题

Revision ID: 7b0a9242d431
Revises: 1e06096dac58
Create Date: 2025-09-08 20:28:48.880625

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7b0a9242d431"
down_revision = "1e06096dac58"
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """检查约束是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 检查外键约束
    fks = [fk["name"] for fk in inspector.get_foreign_keys(table_name) if fk["name"]]
    if constraint_name in fks:
        return True

    # 检查唯一约束
    uqs = [uq["name"] for uq in inspector.get_unique_constraints(table_name) if uq["name"]]
    if constraint_name in uqs:
        return True

    # 检查检查约束
    checks = [ck["name"] for ck in inspector.get_check_constraints(table_name) if ck["name"]]
    return constraint_name in checks


def _table_exists(table_name: str) -> bool:
    """检查表是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    if not _table_exists(table_name):
        return False
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_datasource", schema=None) as batch_op:
        batch_op.alter_column(
            "deleted_at",
            existing_type=postgresql.TIMESTAMP(),
            comment="软删除时间，NULL表示未删除",
            existing_comment="删除时间",
            existing_nullable=True,
        )
        batch_op.create_index(batch_op.f("ix_ai_datasource_deleted_at"), ["deleted_at"], unique=False)

    with op.batch_alter_table("ai_datasource_collection", schema=None) as batch_op:
        batch_op.alter_column(
            "deleted_at",
            existing_type=postgresql.TIMESTAMP(),
            comment="软删除时间，NULL表示未删除",
            existing_comment="删除时间",
            existing_nullable=True,
        )
        batch_op.create_index(batch_op.f("ix_ai_datasource_collection_deleted_at"), ["deleted_at"], unique=False)

    with op.batch_alter_table("risk_level", schema=None) as batch_op:
        batch_op.alter_column(
            "deleted_at",
            existing_type=postgresql.TIMESTAMP(),
            comment="软删除时间，NULL表示未删除",
            existing_comment="删除时间",
            existing_nullable=True,
        )
        batch_op.create_index(batch_op.f("ix_risk_level_deleted_at"), ["deleted_at"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("risk_level", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risk_level_deleted_at"))
        batch_op.alter_column(
            "deleted_at",
            existing_type=postgresql.TIMESTAMP(),
            comment="删除时间",
            existing_comment="软删除时间，NULL表示未删除",
            existing_nullable=True,
        )

    with op.batch_alter_table("ai_datasource_collection", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_datasource_collection_deleted_at"))
        batch_op.alter_column(
            "deleted_at",
            existing_type=postgresql.TIMESTAMP(),
            comment="删除时间",
            existing_comment="软删除时间，NULL表示未删除",
            existing_nullable=True,
        )

    with op.batch_alter_table("ai_datasource", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_datasource_deleted_at"))
        batch_op.alter_column(
            "deleted_at",
            existing_type=postgresql.TIMESTAMP(),
            comment="删除时间",
            existing_comment="软删除时间，NULL表示未删除",
            existing_nullable=True,
        )

    # ### end Alembic commands ###
