"""fix api_key_auth user password salt fields

Revision ID: 712183087d1a
Revises: 8ee6e90ec007
Create Date: 2025-11-04 17:37:05.962510

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "712183087d1a"
down_revision = "8ee6e90ec007"
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """检查约束是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 检查外键约束
    fks = [fk["name"] for fk in inspector.get_foreign_keys(table_name) if fk["name"]]
    if constraint_name in fks:
        return True

    # 检查唯一约束
    uqs = [uq["name"] for uq in inspector.get_unique_constraints(table_name) if uq["name"]]
    if constraint_name in uqs:
        return True

    # 检查检查约束
    checks = [ck["name"] for ck in inspector.get_check_constraints(table_name) if ck["name"]]
    return constraint_name in checks


def _table_exists(table_name: str) -> bool:
    """检查表是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    if not _table_exists(table_name):
        return False
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sys_api_key", schema=None) as batch_op:
        # 将唯一约束转换为唯一索引（模型定义使用 unique=True, index=True）
        if _constraint_exists("sys_api_key", "sys_api_key_api_key_key"):
            batch_op.drop_constraint("sys_api_key_api_key_key", type_="unique")
        if _index_exists("sys_api_key", "ix_sys_api_key_api_key"):
            batch_op.drop_index("ix_sys_api_key_api_key")
        batch_op.create_index("ix_sys_api_key_api_key", ["api_key"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sys_api_key", schema=None) as batch_op:
        # 恢复唯一约束和普通索引
        if _index_exists("sys_api_key", "ix_sys_api_key_api_key"):
            batch_op.drop_index("ix_sys_api_key_api_key")
        batch_op.create_index("ix_sys_api_key_api_key", ["api_key"], unique=False)
        if not _constraint_exists("sys_api_key", "sys_api_key_api_key_key"):
            batch_op.create_unique_constraint("sys_api_key_api_key_key", ["api_key"])

    # ### end Alembic commands ###
