"""merge branches fix

Revision ID: merge_branches_fix
Revises: create_ai_assistant_report_user_read_table, 2a15da5d7955
Create Date: 2025-09-03 10:00:00.000000

"""

# revision identifiers, used by Alembic.
revision = "f1e2d3c4b5a6"
down_revision = ("a1b2c3d4e5f6", "2a15da5d7955")
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This is a merge migration, no changes needed
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This is a merge migration, no changes needed
    pass
    # ### end Alembic commands ###
