"""make_content_nullable_in_ai_chat_message

Revision ID: 2c1ed6337309
Revises: bfbe1aac0618
Create Date: 2025-08-20 18:41:38.874474

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2c1ed6337309"
down_revision = "bfbe1aac0618"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create index if it doesn't exist
    op.execute("CREATE INDEX IF NOT EXISTS ix_ai_chat_file_chat_message_id ON ai_chat_file (chat_message_id)")
    # Drop foreign key constraint if it exists
    op.execute("ALTER TABLE ai_chat_file DROP CONSTRAINT IF EXISTS ai_chat_file_chat_message_id_fkey")
    op.alter_column("ai_chat_message", "content", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("ai_chat_message", "is_interrupted", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ai_chat_message", "is_interrupted", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("ai_chat_message", "content", existing_type=sa.TEXT(), nullable=False)
    op.create_foreign_key(
        op.f("ai_chat_file_chat_message_id_fkey"), "ai_chat_file", "ai_chat_message", ["chat_message_id"], ["id"]
    )
    op.drop_index(op.f("ix_ai_chat_file_chat_message_id"), table_name="ai_chat_file")
    # ### end Alembic commands ###
