"""update_subscription_and_task_fields

Revision ID: 829a9bd6f5a9
Revises: b148ba90f0bc
Create Date: 2025-09-08 16:57:00.981994

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "829a9bd6f5a9"
down_revision = "b148ba90f0bc"
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """检查约束是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 检查外键约束
    fks = [fk["name"] for fk in inspector.get_foreign_keys(table_name) if fk["name"]]
    if constraint_name in fks:
        return True

    # 检查唯一约束
    uqs = [uq["name"] for uq in inspector.get_unique_constraints(table_name) if uq["name"]]
    if constraint_name in uqs:
        return True

    # 检查检查约束
    checks = [ck["name"] for ck in inspector.get_check_constraints(table_name) if ck["name"]]
    return constraint_name in checks


def _table_exists(table_name: str) -> bool:
    """检查表是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    if not _table_exists(table_name):
        return False
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_subscription", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.BIGINT(), nullable=False, existing_comment="创建用户ID")

    with op.batch_alter_table("ai_subscription_notifications", schema=None) as batch_op:
        batch_op.alter_column(
            "send_status",
            existing_type=sa.VARCHAR(length=20),
            server_default=None,
            existing_comment="发送状态: pending-待发送, sending-发送中, sent-已发送, failed-发送失败",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "retry_count",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_comment="重试次数",
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_subscription_notifications", schema=None) as batch_op:
        batch_op.alter_column(
            "retry_count",
            existing_type=sa.INTEGER(),
            server_default=sa.text("0"),
            existing_comment="重试次数",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "send_status",
            existing_type=sa.VARCHAR(length=20),
            server_default=sa.text("'pending'::character varying"),
            existing_comment="发送状态: pending-待发送, sending-发送中, sent-已发送, failed-发送失败",
            existing_nullable=False,
        )

    with op.batch_alter_table("ai_subscription", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.BIGINT(), nullable=True, existing_comment="创建用户ID")

    # ### end Alembic commands ###
