"""删除废弃的表和索引

Revision ID: 20956ef6a65a
Revises: 8b11f645798b
Create Date: 2025-08-15 16:03:36.764406

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "20956ef6a65a"
down_revision = "8b11f645798b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 跳过有问题的字段修改，因为主键不能为NULL
    # op.alter_column('risk_report_log', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            existing_comment='报告ID',
    #            autoincrement=True)

    # 创建索引
    op.create_index(op.f("ix_risk_tag_category_id"), "risk_tag", ["category_id"], unique=False)
    op.create_index(op.f("ix_risk_tag_name"), "risk_tag", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_risk_tag_name"), table_name="risk_tag")
    op.drop_index(op.f("ix_risk_tag_category_id"), table_name="risk_tag")
    op.alter_column(
        "risk_report_log",
        "id",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="报告ID",
        autoincrement=True,
    )
    # ### end Alembic commands ###
