"""add_setting_field_to_risk_assistant

Revision ID: bd129e4cf3d8
Revises: d5622ed1887f
Create Date: 2025-08-17 10:00:00.000000

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "bd129e4cf3d8"
down_revision = "d5622ed1887f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("risk_assistant", sa.Column("setting", sa.JSON(), nullable=True, comment="设置，JSON格式存储"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("risk_assistant", "setting")
    # ### end Alembic commands ###
