"""Auto-generated migration

Revision ID: 085797683a64
Revises: ee7251615179
Create Date: 2025-08-26 11:13:09.867360

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "085797683a64"
down_revision = "ee7251615179"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 首先修改ai_subscription表结构
    op.add_column("ai_subscription", sa.Column("assistant_id", sa.String(length=50), nullable=False, comment="助手ID"))

    # 删除外键约束以便进行类型转换
    op.drop_constraint(
        "ai_subscription_notifications_subscription_id_fkey", "ai_subscription_notifications", type_="foreignkey"
    )

    # 使用原生SQL来处理类型转换，因为PostgreSQL需要USING子句
    op.execute("ALTER TABLE ai_subscription ALTER COLUMN id TYPE INTEGER USING id::integer")
    op.execute("COMMENT ON COLUMN ai_subscription.id IS '订阅ID'")
    op.execute(
        "ALTER TABLE ai_subscription_notifications ALTER COLUMN subscription_id TYPE INTEGER USING subscription_id::integer"
    )

    # 重新创建外键约束
    op.create_foreign_key(
        "ai_subscription_notifications_subscription_id_fkey",
        "ai_subscription_notifications",
        "ai_subscription",
        ["subscription_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_ai_subscription_notifications_subscription_id"),
        "ai_subscription_notifications",
        ["subscription_id"],
        unique=False,
    )

    # 然后创建新表（现在可以正确引用已转换类型的ai_subscription表）
    op.create_table(
        "task_scheduler_execution",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"),
        sa.Column("scheduler_id", sa.Integer(), nullable=False, comment="任务调度ID"),
        sa.Column("celery_task_id", sa.String(length=155), nullable=False, comment="Celery任务ID"),
        sa.Column("execution_time", sa.DateTime(timezone=True), nullable=True, comment="执行时间"),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True, comment="任务开始执行时间"),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True, comment="任务结束执行时间"),
        sa.Column("user_id", sa.Integer(), nullable=True, comment="执行用户ID"),
        sa.Column("subscription_id", sa.Integer(), nullable=True, comment="订阅ID"),
        sa.Column("duration_seconds", sa.Float(), nullable=True, comment="执行时长（秒）"),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False, comment="创建时间"),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(["scheduler_id"], ["task_scheduler.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["subscription_id"], ["ai_subscription.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["sys_user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_start_end_time", "task_scheduler_execution", ["start_time", "end_time"], unique=False)
    op.create_index(
        "idx_subscription_scheduler", "task_scheduler_execution", ["subscription_id", "scheduler_id"], unique=False
    )
    op.create_index("idx_user_execution_time", "task_scheduler_execution", ["user_id", "execution_time"], unique=False)
    op.create_index("idx_user_scheduler", "task_scheduler_execution", ["user_id", "scheduler_id"], unique=False)
    op.create_index(
        op.f("ix_task_scheduler_execution_celery_task_id"), "task_scheduler_execution", ["celery_task_id"], unique=True
    )
    op.create_index(op.f("ix_task_scheduler_execution_id"), "task_scheduler_execution", ["id"], unique=False)
    op.add_column("task_scheduler", sa.Column("user_id", sa.Integer(), nullable=True, comment="用户ID"))
    op.add_column("task_scheduler", sa.Column("subscription_id", sa.Integer(), nullable=True, comment="订阅ID"))
    op.add_column(
        "task_scheduler",
        sa.Column(
            "priority",
            sa.Integer(),
            nullable=False,
            server_default="5",
            comment="任务优先级（1-10，数字越小优先级越高）",
        ),
    )
    op.add_column(
        "task_scheduler",
        sa.Column("max_retries", sa.Integer(), nullable=False, server_default="3", comment="最大重试次数"),
    )

    # 移除默认值，因为只在添加列时需要
    op.alter_column("task_scheduler", "priority", server_default=None)
    op.alter_column("task_scheduler", "max_retries", server_default=None)
    op.create_foreign_key(None, "task_scheduler", "ai_subscription", ["subscription_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "task_scheduler", "sys_user", ["user_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task_scheduler", type_="foreignkey")
    op.drop_constraint(None, "task_scheduler", type_="foreignkey")
    op.drop_column("task_scheduler", "max_retries")
    op.drop_column("task_scheduler", "priority")
    op.drop_column("task_scheduler", "subscription_id")
    op.drop_column("task_scheduler", "user_id")
    op.drop_index(op.f("ix_ai_subscription_notifications_subscription_id"), table_name="ai_subscription_notifications")
    op.alter_column(
        "ai_subscription_notifications",
        "subscription_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=50),
        existing_comment="订阅ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "ai_subscription",
        "id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=50),
        comment="助手ID",
        existing_comment="订阅ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("ai_subscription", "assistant_id")
    op.drop_index(op.f("ix_task_scheduler_execution_id"), table_name="task_scheduler_execution")
    op.drop_index(op.f("ix_task_scheduler_execution_celery_task_id"), table_name="task_scheduler_execution")
    op.drop_index("idx_user_scheduler", table_name="task_scheduler_execution")
    op.drop_index("idx_user_execution_time", table_name="task_scheduler_execution")
    op.drop_index("idx_subscription_scheduler", table_name="task_scheduler_execution")
    op.drop_index("idx_start_end_time", table_name="task_scheduler_execution")
    op.drop_table("task_scheduler_execution")
    # ### end Alembic commands ###
