"""ensure_subscription_id_index_non_unique

Revision ID: 2351485a6e6c
Revises: b7d9f1ea9e3a
Create Date: 2025-09-06 09:59:25.358559

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2351485a6e6c"
down_revision = "b7d9f1ea9e3a"
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """检查约束是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 检查外键约束
    fks = [fk["name"] for fk in inspector.get_foreign_keys(table_name) if fk["name"]]
    if constraint_name in fks:
        return True

    # 检查唯一约束
    uqs = [uq["name"] for uq in inspector.get_unique_constraints(table_name) if uq["name"]]
    if constraint_name in uqs:
        return True

    # 检查检查约束
    checks = [ck["name"] for ck in inspector.get_check_constraints(table_name) if ck["name"]]
    return constraint_name in checks


def _table_exists(table_name: str) -> bool:
    """检查表是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    if not _table_exists(table_name):
        return False
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 确保 subscription_id 索引是非唯一的，因为一个订阅可以关联多个通知方式
    with op.batch_alter_table("ai_subscription_notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_subscription_notifications_subscription_id"))
        batch_op.create_index(
            batch_op.f("ix_ai_subscription_notifications_subscription_id"), ["subscription_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 回滚：将索引改回唯一（虽然这是错误的设计）
    with op.batch_alter_table("ai_subscription_notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_subscription_notifications_subscription_id"))
        batch_op.create_index(
            batch_op.f("ix_ai_subscription_notifications_subscription_id"), ["subscription_id"], unique=True
        )

    # ### end Alembic commands ###
