"""add_incremental_analysis_fields_to_risk_report_log

Revision ID: 497de9d282c2
Revises: 9ccb88c3e652
Create Date: 2025-09-10 16:03:10.141148

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "497de9d282c2"
down_revision = "9ccb88c3e652"
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """检查约束是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 检查外键约束
    fks = [fk["name"] for fk in inspector.get_foreign_keys(table_name) if fk["name"]]
    if constraint_name in fks:
        return True

    # 检查唯一约束
    uqs = [uq["name"] for uq in inspector.get_unique_constraints(table_name) if uq["name"]]
    if constraint_name in uqs:
        return True

    # 检查检查约束
    checks = [ck["name"] for ck in inspector.get_check_constraints(table_name) if ck["name"]]
    return constraint_name in checks


def _table_exists(table_name: str) -> bool:
    """检查表是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    if not _table_exists(table_name):
        return False
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("risk_report_log", schema=None) as batch_op:
        if not _column_exists("risk_report_log", "analysis_type"):
            batch_op.add_column(
                sa.Column(
                    "analysis_type",
                    sa.String(length=20),
                    nullable=True,
                    comment="分析类型：STOCK=存量，INCREMENTAL=增量，TRIGGERED=触发",
                )
            )
        if not _column_exists("risk_report_log", "trigger_sources"):
            batch_op.add_column(
                sa.Column(
                    "trigger_sources",
                    sa.Text(),
                    nullable=True,
                    comment="触发原因：new_register,new_login,new_transfer等，多个用逗号分隔",
                )
            )
        if not _column_exists("risk_report_log", "detection_window_info"):
            batch_op.add_column(
                sa.Column(
                    "detection_window_info", sa.JSON(), nullable=True, comment="检测窗口信息：时间范围、窗口大小等"
                )
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("risk_report_log", schema=None) as batch_op:
        batch_op.drop_column("detection_window_info")
        batch_op.drop_column("trigger_sources")
        batch_op.drop_column("analysis_type")

    # ### end Alembic commands ###
