"""仅更新字段注释，不改变字段类型

Revision ID: d5622ed1887f
Revises: 9e38c70d32d6
Create Date: 2025-08-15 17:29:34.670475

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d5622ed1887f"
down_revision = "9e38c70d32d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 注意：有问题的数据已经备份到backup_problematic_data表，并已清空原字段

    # 1. 删除并重新创建ai_assistant_report_log表字段
    op.drop_column("ai_assistant_report_log", "sql_data")
    op.add_column(
        "ai_assistant_report_log", sa.Column("sql_data", sa.JSON(), nullable=True, comment="SQL查询数据，JSON格式")
    )

    op.drop_column("ai_assistant_report_log", "prompt_data")
    op.add_column(
        "ai_assistant_report_log", sa.Column("prompt_data", sa.JSON(), nullable=True, comment="提示词数据，JSON格式")
    )

    op.drop_column("ai_assistant_report_log", "report_table")
    op.add_column(
        "ai_assistant_report_log", sa.Column("report_table", sa.JSON(), nullable=True, comment="报告表格数据，JSON格式")
    )

    # 2. 更新ai_assistants表注释
    op.alter_column(
        "ai_assistants",
        "output_data",
        existing_type=sa.TEXT(),
        comment="输出数据：table格式时存储JSON字符串，document格式时存储Markdown文本，both格式时存储混合内容",
        existing_comment="输出数据：table格式时存储JSON字符串，document格式时存储Markdown文本",
        existing_nullable=True,
    )

    # 3. 删除并重新创建risk_assistant表字段
    op.drop_column("risk_assistant", "variable_config")
    op.add_column(
        "risk_assistant", sa.Column("variable_config", sa.JSON(), nullable=True, comment="变量配置，JSON格式存储")
    )

    op.drop_column("risk_assistant", "report_config")
    op.add_column(
        "risk_assistant", sa.Column("report_config", sa.JSON(), nullable=True, comment="报告配置，JSON格式存储")
    )

    # 4. 删除并重新创建risk_report_log表字段
    op.drop_column("risk_report_log", "sql_data")
    op.add_column("risk_report_log", sa.Column("sql_data", sa.JSON(), nullable=True, comment="SQL查询数据，JSON格式"))

    op.drop_column("risk_report_log", "prompt_data")
    op.add_column("risk_report_log", sa.Column("prompt_data", sa.JSON(), nullable=True, comment="提示词数据，JSON格式"))

    op.drop_column("risk_report_log", "report_table")
    op.add_column(
        "risk_report_log", sa.Column("report_table", sa.JSON(), nullable=True, comment="报告表格数据，JSON格式")
    )
    # ### end Alembic commands ###


def downgrade():
    pass
