"""清理废弃的表和索引

Revision ID: 9e38c70d32d6
Revises: 1dd37692aa40
Create Date: 2025-08-15 16:20:17.051531

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "9e38c70d32d6"
down_revision = "1dd37692aa40"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 跳过主键列的nullable修改，因为主键不能为NULL
    # op.alter_column('risk_report_log', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            existing_comment='报告ID',
    #            autoincrement=True)
    op.create_index(op.f("ix_risk_tag_category_id"), "risk_tag_category", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_risk_tag_category_id"), table_name="risk_tag_category")
    # 跳过主键列的nullable修改，因为主键不能为NULL
    # op.alter_column('risk_report_log', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            existing_comment='报告ID',
    #            autoincrement=True)
    # ### end Alembic commands ###
