"""Add is_interrupted field to ai_chat_message

Revision ID: 163f08062417
Revises: 7e1a5600c498
Create Date: 2025-08-20 14:40:32.991701

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "163f08062417"
down_revision = "7e1a5600c498"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ai_chat_file",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_chat_file",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="更新时间",
        existing_nullable=True,
    )
    # Drop indexes if they exist
    op.execute("DROP INDEX IF EXISTS ix_ai_chat_file_data_source")
    op.execute("DROP INDEX IF EXISTS ix_ai_chat_file_task_id")
    # Drop foreign key constraint if it exists
    op.execute("ALTER TABLE ai_chat_file DROP CONSTRAINT IF EXISTS ai_chat_file_chat_message_id_fkey")
    op.create_foreign_key(None, "ai_chat_file", "ai_chat_message", ["chat_message_id"], ["id"])

    # 先添加可空字段
    op.add_column("ai_chat_message", sa.Column("is_interrupted", sa.Boolean(), nullable=True))

    # 设置默认值
    op.execute("UPDATE ai_chat_message SET is_interrupted = false WHERE is_interrupted IS NULL")

    # 设置为不可空
    op.alter_column("ai_chat_message", "is_interrupted", nullable=True)
    op.drop_column("ai_chat_message", "query_data")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_chat_message", "is_interrupted")
    op.add_column("ai_chat_message", sa.Column("query_data", sa.JSON(), nullable=True))
    op.drop_constraint(None, "ai_chat_file", type_="foreignkey")
    op.create_foreign_key(
        op.f("ai_chat_file_chat_message_id_fkey"),
        "ai_chat_file",
        "ai_chat_message",
        ["chat_message_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(op.f("ix_ai_chat_file_task_id"), "ai_chat_file", ["task_id"], unique=False)
    op.create_index(op.f("ix_ai_chat_file_data_source"), "ai_chat_file", ["data_source"], unique=False)
    op.alter_column(
        "ai_chat_file",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "ai_chat_file",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="创建时间",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
