"""Remove unnecessary SQLAlchemy relationships from AiAssistantReportUserRead

Revision ID: 0f47a71f5d97
Revises: f1e2d3c4b5a6
Create Date: 2025-09-04 10:21:08.957349

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0f47a71f5d97"
down_revision = "f1e2d3c4b5a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 安全删除索引：先检查索引是否存在再删除
    connection = op.get_bind()

    # 检查并删除 ai_assistant_report_user_read 表的索引
    indexes_to_check = [
        ("ix_ai_assistant_report_user_read_created_time", "ai_assistant_report_user_read"),
        ("ix_ai_assistant_report_user_read_is_read", "ai_assistant_report_user_read"),
        ("ix_ai_assistant_report_user_read_report_id", "ai_assistant_report_user_read"),
        ("ix_ai_assistant_report_user_read_user_id", "ai_assistant_report_user_read"),
        ("ix_ai_chat_user_id_created_time", "ai_chat"),
        ("ix_ai_chat_message_chat_id_created_time", "ai_chat_message"),
    ]

    for index_name, table_name in indexes_to_check:
        # 检查索引是否存在
        result = connection.execute(
            sa.text("SELECT 1 FROM pg_indexes WHERE indexname = :index_name AND tablename = :table_name"),
            {"index_name": index_name, "table_name": table_name},
        ).fetchone()

        if result:
            op.drop_index(op.f(index_name), table_name=table_name)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 安全创建索引：先检查索引是否不存在再创建
    connection = op.get_bind()

    # 定义需要创建的索引
    indexes_to_create = [
        ("ix_ai_assistant_report_user_read_created_time", "ai_assistant_report_user_read", ["created_time"]),
        ("ix_ai_assistant_report_user_read_is_read", "ai_assistant_report_user_read", ["is_read"]),
        ("ix_ai_assistant_report_user_read_report_id", "ai_assistant_report_user_read", ["report_id"]),
        ("ix_ai_assistant_report_user_read_user_id", "ai_assistant_report_user_read", ["user_id"]),
        ("ix_ai_chat_user_id_created_time", "ai_chat", ["user_id", sa.literal_column("created_time DESC")]),
        ("ix_ai_chat_message_chat_id_created_time", "ai_chat_message", ["chat_id", "created_time"]),
    ]

    for index_name, table_name, columns in indexes_to_create:
        # 检查索引是否不存在
        result = connection.execute(
            sa.text("SELECT 1 FROM pg_indexes WHERE indexname = :index_name AND tablename = :table_name"),
            {"index_name": index_name, "table_name": table_name},
        ).fetchone()

        if not result:
            op.create_index(op.f(index_name), table_name, columns, unique=False)
    # ### end Alembic commands ###
