"""同步数据库模型变更

Revision ID: 8b11f645798b
Revises: 1a39f6e9212d
Create Date: 2025-08-15 16:02:08.689985

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8b11f645798b"
down_revision = "1a39f6e9212d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_scheduler")
    op.alter_column(
        "ai_assistant_personnel",
        "username",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_comment="用户名",
    )
    op.alter_column(
        "ai_assistant_personnel", "email", existing_type=sa.VARCHAR(length=100), nullable=False, existing_comment="邮箱"
    )
    op.create_foreign_key(None, "ai_assistant_personnel", "ai_assistants", ["assistant_id"], ["id"], ondelete="CASCADE")
    op.alter_column(
        "ai_assistant_report_log",
        "report_status",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_comment="报告状态",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_assistant_report_log",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=None,
        existing_comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_assistant_report_log",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=None,
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_ai_assistant_report_log_member_id"), table_name="ai_assistant_report_log")
    op.create_index(
        op.f("ix_ai_assistant_report_log_member_ids"), "ai_assistant_report_log", ["member_ids"], unique=False
    )
    op.create_index(op.f("ix_ai_assistant_report_log_model_id"), "ai_assistant_report_log", ["model_id"], unique=False)
    op.create_foreign_key(None, "ai_assistant_report_log", "ai_assistants", ["assistant_id"], ["id"])
    op.alter_column(
        "ai_assistants",
        "ai_model_id",
        existing_type=sa.VARCHAR(length=50),
        comment="AI模型ID",
        existing_comment="模型类型",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_assistants",
        "data_permission",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_comment="数据权限",
    )
    op.alter_column(
        "ai_assistants",
        "data_permission_values",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_comment="数据权限具体值",
        existing_nullable=True,
    )
    op.alter_column(
        "ai_assistants",
        "data_time_range_type",
        existing_type=postgresql.ENUM("day", "month", "quarter", "year", name="data_time_range_enum"),
        server_default=None,
        existing_comment="数据时间范围类型",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_assistants",
        "data_time_value",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_comment="数据时间范围值",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_assistants", "ai_analysis_count", existing_type=sa.INTEGER(), nullable=False, existing_comment="AI分析次数"
    )
    op.alter_column(
        "ai_assistants",
        "last_analysis_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        type_=sa.DateTime(),
        existing_comment="最后一次分析时间",
        existing_nullable=True,
    )
    op.drop_column("ai_chat", "updated_at")
    op.drop_column("ai_chat", "created_at")
    op.alter_column(
        "ai_chat_message",
        "created_time",
        existing_type=postgresql.TIMESTAMP(precision=6),
        type_=sa.DateTime(timezone=True),
        nullable=False,
        comment="创建时间",
    )
    op.alter_column(
        "ai_chat_message",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(precision=6),
        type_=sa.DateTime(timezone=True),
        comment="更新时间",
        existing_nullable=True,
    )
    op.create_index(op.f("ix_ai_chat_message_chat_id"), "ai_chat_message", ["chat_id"], unique=False)
    op.create_foreign_key(None, "ai_chat_message", "ai_chat", ["chat_id"], ["id"])
    op.create_table_comment(
        "ai_chat_message",
        "AI Chat Message model for storing individual messages in a chat session",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "ai_models",
        "model",
        existing_type=sa.VARCHAR(length=100),
        comment="模型名称/标识符，如gpt-4-turbo",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_models",
        "temperature",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=None,
        comment="温度参数，值范围0-1",
        existing_nullable=False,
    )
    op.alter_column(
        "client_user", "id", existing_type=sa.INTEGER(), comment="主键 ID", existing_nullable=False, autoincrement=True
    )
    op.alter_column(
        "client_user",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "client_user",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        comment="更新时间",
        existing_nullable=True,
    )
    op.create_index(op.f("ix_client_user_email"), "client_user", ["email"], unique=True)
    op.create_index(op.f("ix_client_user_id"), "client_user", ["id"], unique=False)
    op.create_index(op.f("ix_client_user_username"), "client_user", ["username"], unique=True)
    op.create_table_comment("client_user", "客户端用户模型", existing_comment=None, schema=None)
    op.drop_column("client_user", "updated_at")
    op.drop_column("client_user", "created_at")
    op.alter_column("mcp_query", "status", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "mcp_query",
        "created_time",
        existing_type=postgresql.TIMESTAMP(precision=6),
        type_=sa.DateTime(timezone=True),
        nullable=False,
        comment="创建时间",
    )
    op.alter_column(
        "mcp_query",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        comment="更新时间",
        existing_nullable=True,
    )
    op.create_index(op.f("ix_mcp_query_chat_message_id"), "mcp_query", ["chat_message_id"], unique=False)
    op.create_table_comment(
        "mcp_query",
        "MCP Query model for tracking data queries made through the MCP service",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "risk_assistant", "risk_type", existing_type=sa.VARCHAR(length=100), nullable=True, existing_comment="风险类型"
    )
    op.alter_column(
        "risk_assistant",
        "ai_analysis_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        nullable=False,
        existing_comment="AI分析次数",
    )
    op.alter_column(
        "risk_assistant",
        "last_analysis_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        type_=sa.DateTime(),
        existing_comment="最后一次分析时间",
        existing_nullable=True,
    )
    # 跳过主键字段的nullable修改，因为主键不能为NULL
    # op.alter_column('risk_report_log', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            existing_comment='报告ID',
    #            autoincrement=True)
    op.alter_column(
        "risk_report_log",
        "handle_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        type_=sa.DateTime(),
        existing_comment="处理时间",
        existing_nullable=True,
    )
    op.alter_column(
        "risk_report_log",
        "member_name",
        existing_type=sa.VARCHAR(length=50),
        comment="用户名称",
        existing_comment="用户名",
        existing_nullable=True,
    )
    op.alter_column(
        "risk_report_log",
        "report_status",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_comment="报告状态",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_report_log",
        "is_processed",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_comment="是否需要处理",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_report_log",
        "ai_response",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
        existing_comment="AI响应",
    )
    op.alter_column(
        "risk_report_log",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=None,
        existing_comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_report_log",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=None,
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.create_index(op.f("ix_risk_report_log_model_id"), "risk_report_log", ["model_id"], unique=False)
    op.create_foreign_key(None, "risk_report_log", "risk_assistant", ["assistant_id"], ["id"])
    op.alter_column(
        "risk_tag", "id", existing_type=sa.VARCHAR(length=36), comment="标签ID，使用UUID", existing_nullable=False
    )
    op.alter_column(
        "risk_tag", "category_id", existing_type=sa.VARCHAR(length=36), comment="标签分类ID", existing_nullable=False
    )
    op.alter_column(
        "risk_tag", "name", existing_type=sa.VARCHAR(length=100), comment="标签名称", existing_nullable=False
    )
    op.alter_column("risk_tag", "description", existing_type=sa.TEXT(), comment="标签描述", existing_nullable=True)
    op.alter_column(
        "risk_tag",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=None,
        comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_tag",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        comment="更新时间",
        existing_nullable=True,
    )
    # 跳过索引创建，因为可能已经存在
    # op.create_index(op.f('ix_risk_tag_category_id'), 'risk_tag', ['category_id'], unique=False)
    # op.create_index(op.f('ix_risk_tag_name'), 'risk_tag', ['name'], unique=False)
    op.create_table_comment("risk_tag", "风控标签表", existing_comment=None, schema=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("risk_tag", existing_comment="风控标签表", schema=None)
    op.drop_index(op.f("ix_risk_tag_name"), table_name="risk_tag")
    op.drop_index(op.f("ix_risk_tag_category_id"), table_name="risk_tag")
    op.alter_column(
        "risk_tag",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        comment=None,
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "risk_tag",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=sa.text("now()"),
        comment=None,
        existing_comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_tag",
        "description",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="标签描述",
        existing_nullable=True,
    )
    op.alter_column(
        "risk_tag",
        "name",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="标签名称",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_tag",
        "category_id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="标签分类ID",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_tag",
        "id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="标签ID，使用UUID",
        existing_nullable=False,
    )
    op.drop_constraint(None, "risk_report_log", type_="foreignkey")
    op.drop_index(op.f("ix_risk_report_log_model_id"), table_name="risk_report_log")
    op.alter_column(
        "risk_report_log",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=sa.text("now()"),
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "risk_report_log",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=sa.text("NULL::timestamp with time zone"),
        existing_comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_report_log",
        "ai_response",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
        existing_comment="AI响应",
    )
    op.alter_column(
        "risk_report_log",
        "is_processed",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_comment="是否需要处理",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_report_log",
        "report_status",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_comment="报告状态",
        existing_nullable=False,
    )
    op.alter_column(
        "risk_report_log",
        "member_name",
        existing_type=sa.VARCHAR(length=50),
        comment="用户名",
        existing_comment="用户名称",
        existing_nullable=True,
    )
    op.alter_column(
        "risk_report_log",
        "handle_time",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True, precision=6),
        existing_comment="处理时间",
        existing_nullable=True,
    )
    op.alter_column(
        "risk_report_log",
        "id",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="报告ID",
        autoincrement=True,
    )
    op.alter_column(
        "risk_assistant",
        "last_analysis_time",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True, precision=6),
        existing_comment="最后一次分析时间",
        existing_nullable=True,
    )
    op.alter_column(
        "risk_assistant",
        "ai_analysis_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=True,
        existing_comment="AI分析次数",
    )
    op.alter_column(
        "risk_assistant", "risk_type", existing_type=sa.VARCHAR(length=100), nullable=False, existing_comment="风险类型"
    )
    op.drop_table_comment(
        "mcp_query",
        existing_comment="MCP Query model for tracking data queries made through the MCP service",
        schema=None,
    )
    op.drop_index(op.f("ix_mcp_query_chat_message_id"), table_name="mcp_query")
    op.alter_column(
        "mcp_query",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        comment=None,
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "mcp_query",
        "created_time",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(precision=6),
        nullable=True,
        comment=None,
        existing_comment="创建时间",
    )
    op.alter_column("mcp_query", "status", existing_type=sa.BOOLEAN(), nullable=True)
    op.add_column(
        "client_user", sa.Column("created_at", postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True)
    )
    op.add_column(
        "client_user", sa.Column("updated_at", postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True)
    )
    op.drop_table_comment("client_user", existing_comment="客户端用户模型", schema=None)
    op.drop_index(op.f("ix_client_user_username"), table_name="client_user")
    op.drop_index(op.f("ix_client_user_id"), table_name="client_user")
    op.drop_index(op.f("ix_client_user_email"), table_name="client_user")
    op.alter_column(
        "client_user",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        comment=None,
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "client_user",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        comment=None,
        existing_comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "client_user",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="主键 ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "ai_models",
        "temperature",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text("'0.75'::double precision"),
        comment=None,
        existing_comment="温度参数，值范围0-1",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_models",
        "model",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="模型名称/标识符，如gpt-4-turbo",
        existing_nullable=False,
    )
    op.drop_table_comment(
        "ai_chat_message",
        existing_comment="AI Chat Message model for storing individual messages in a chat session",
        schema=None,
    )
    op.drop_constraint(None, "ai_chat_message", type_="foreignkey")
    op.drop_index(op.f("ix_ai_chat_message_chat_id"), table_name="ai_chat_message")
    op.alter_column(
        "ai_chat_message",
        "updated_time",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(precision=6),
        comment=None,
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "ai_chat_message",
        "created_time",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(precision=6),
        nullable=True,
        comment=None,
        existing_comment="创建时间",
    )
    op.add_column(
        "ai_chat", sa.Column("created_at", postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True)
    )
    op.add_column(
        "ai_chat", sa.Column("updated_at", postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True)
    )
    op.alter_column(
        "ai_assistants",
        "last_analysis_time",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True, precision=6),
        existing_comment="最后一次分析时间",
        existing_nullable=True,
    )
    op.alter_column(
        "ai_assistants", "ai_analysis_count", existing_type=sa.INTEGER(), nullable=True, existing_comment="AI分析次数"
    )
    op.alter_column(
        "ai_assistants",
        "data_time_value",
        existing_type=sa.INTEGER(),
        server_default=sa.text("1"),
        existing_comment="数据时间范围值",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_assistants",
        "data_time_range_type",
        existing_type=postgresql.ENUM("day", "month", "quarter", "year", name="data_time_range_enum"),
        server_default=sa.text("'month'::data_time_range_enum"),
        existing_comment="数据时间范围类型",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_assistants",
        "data_permission_values",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_comment="数据权限具体值",
        existing_nullable=True,
    )
    op.alter_column(
        "ai_assistants",
        "data_permission",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_comment="数据权限",
    )
    op.alter_column(
        "ai_assistants",
        "ai_model_id",
        existing_type=sa.VARCHAR(length=50),
        comment="模型类型",
        existing_comment="AI模型ID",
        existing_nullable=False,
    )
    op.drop_constraint(None, "ai_assistant_report_log", type_="foreignkey")
    op.drop_index(op.f("ix_ai_assistant_report_log_model_id"), table_name="ai_assistant_report_log")
    op.drop_index(op.f("ix_ai_assistant_report_log_member_ids"), table_name="ai_assistant_report_log")
    op.create_index(
        op.f("ix_ai_assistant_report_log_member_id"), "ai_assistant_report_log", ["member_ids"], unique=False
    )
    op.alter_column(
        "ai_assistant_report_log",
        "updated_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=sa.text("now()"),
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "ai_assistant_report_log",
        "created_time",
        existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
        server_default=sa.text("now()"),
        existing_comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "ai_assistant_report_log",
        "report_status",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_comment="报告状态",
        existing_nullable=False,
    )
    op.drop_constraint(None, "ai_assistant_personnel", type_="foreignkey")
    op.alter_column(
        "ai_assistant_personnel", "email", existing_type=sa.VARCHAR(length=100), nullable=True, existing_comment="邮箱"
    )
    op.alter_column(
        "ai_assistant_personnel",
        "username",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_comment="用户名",
    )
    op.create_table(
        "task_scheduler",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment="任务名称"),
        sa.Column("task", sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment="要运行的 Celery 任务"),
        sa.Column(
            "args",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
            comment="任务可接收的位置参数",
        ),
        sa.Column(
            "kwargs",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
            comment="任务可接收的关键字参数",
        ),
        sa.Column(
            "queue",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="CELERY_TASK_QUEUES 中定义的队列",
        ),
        sa.Column(
            "exchange", sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment="低级别 AMQP 路由的交换机"
        ),
        sa.Column(
            "routing_key",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="低级别 AMQP 路由的路由密钥",
        ),
        sa.Column(
            "start_time",
            postgresql.TIMESTAMP(timezone=True, precision=6),
            autoincrement=False,
            nullable=True,
            comment="任务开始触发的时间",
        ),
        sa.Column(
            "expire_time",
            postgresql.TIMESTAMP(timezone=True, precision=6),
            autoincrement=False,
            nullable=True,
            comment="任务不再触发的截止时间",
        ),
        sa.Column(
            "expire_seconds", sa.INTEGER(), autoincrement=False, nullable=True, comment="任务不再触发的秒数时间差"
        ),
        sa.Column("type", sa.INTEGER(), autoincrement=False, nullable=False, comment="调度类型（0间隔 1定时）"),
        sa.Column(
            "interval_every", sa.INTEGER(), autoincrement=False, nullable=True, comment="任务再次运行前的间隔周期数"
        ),
        sa.Column(
            "interval_period",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="任务运行之间的周期类型",
        ),
        sa.Column(
            "crontab",
            sa.VARCHAR(length=50),
            server_default=sa.text("'* * * * *'::character varying"),
            autoincrement=False,
            nullable=True,
            comment="任务运行的 Crontab 计划",
        ),
        sa.Column(
            "one_off",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
            comment="是否仅运行一次",
        ),
        sa.Column(
            "enabled",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=True,
            comment="是否启用任务",
        ),
        sa.Column(
            "total_run_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
            comment="任务触发的总次数",
        ),
        sa.Column(
            "last_run_time",
            postgresql.TIMESTAMP(timezone=True, precision=6),
            autoincrement=False,
            nullable=True,
            comment="任务最后触发的时间",
        ),
        sa.Column("remark", sa.TEXT(), autoincrement=False, nullable=True, comment="备注"),
        sa.Column(
            "created_time",
            postgresql.TIMESTAMP(timezone=True, precision=6),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_time",
            postgresql.TIMESTAMP(timezone=True, precision=6),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("task_scheduler_pkey")),
        sa.UniqueConstraint(
            "name", name=op.f("task_scheduler_name_key"), postgresql_include=[], postgresql_nulls_not_distinct=False
        ),
        comment="任务调度表",
    )
    # ### end Alembic commands ###
