"""Change report_tags field type from Text to JSON

Revision ID: fa8afcb8b883
Revises: e0d982c6e77e
Create Date: 2025-08-27 12:52:04.906615

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fa8afcb8b883"
down_revision = "e0d982c6e77e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL 需要使用 USING 语句来转换 TEXT 到 JSON 类型
    op.execute("ALTER TABLE risk_report_log ALTER COLUMN report_tags TYPE JSON USING report_tags::json")
    op.execute("COMMENT ON COLUMN risk_report_log.report_tags IS '报告标签，JSON数组'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "risk_report_log",
        "report_tags",
        existing_type=sa.JSON(),
        type_=sa.TEXT(),
        comment="报告标签，JSON格式字符串",
        existing_comment="报告标签，JSON数组",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
