"""update table comments and indexes

Revision ID: ddc9d7dbe100
Revises: f5daf82786b4
Create Date: 2025-10-20 14:31:30.812959

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ddc9d7dbe100"
down_revision = "f5daf82786b4"
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """检查约束是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 检查外键约束
    fks = [fk["name"] for fk in inspector.get_foreign_keys(table_name) if fk["name"]]
    if constraint_name in fks:
        return True

    # 检查唯一约束
    uqs = [uq["name"] for uq in inspector.get_unique_constraints(table_name) if uq["name"]]
    if constraint_name in uqs:
        return True

    # 检查检查约束
    checks = [ck["name"] for ck in inspector.get_check_constraints(table_name) if ck["name"]]
    return constraint_name in checks


def _table_exists(table_name: str) -> bool:
    """检查表是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    if not _table_exists(table_name):
        return False
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("risk_tag", schema=None) as batch_op:
        batch_op.create_table_comment("风控标签表", existing_comment=None)

    with op.batch_alter_table("sys_notice_log", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            comment="主键 ID",
            existing_comment="主键ID",
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.drop_index(batch_op.f("ix_sys_notice_log_created_time"))
        batch_op.drop_index(batch_op.f("ix_sys_notice_log_is_success"))
        batch_op.drop_index(batch_op.f("ix_sys_notice_log_notification_type"))
        batch_op.drop_index(batch_op.f("ix_sys_notice_log_id"))
        batch_op.create_index(batch_op.f("ix_sys_notice_log_id"), ["id"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sys_notice_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_notice_log_id"))
        batch_op.create_index(batch_op.f("ix_sys_notice_log_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_sys_notice_log_notification_type"), ["notification_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_sys_notice_log_is_success"), ["is_success"], unique=False)
        batch_op.create_index(batch_op.f("ix_sys_notice_log_created_time"), ["created_time"], unique=False)
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            comment="主键ID",
            existing_comment="主键 ID",
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("risk_tag", schema=None) as batch_op:
        batch_op.drop_table_comment(existing_comment="风控标签表")

    # ### end Alembic commands ###
