"""remove unique constraint from ai_subscription_notifications

Revision ID: fd631660049e
Revises: f68a04c4752d
Create Date: 2025-09-06 17:47:50.415157

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fd631660049e"
down_revision = "f68a04c4752d"
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """检查约束是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 检查外键约束
    fks = [fk["name"] for fk in inspector.get_foreign_keys(table_name) if fk["name"]]
    if constraint_name in fks:
        return True

    # 检查唯一约束
    uqs = [uq["name"] for uq in inspector.get_unique_constraints(table_name) if uq["name"]]
    if constraint_name in uqs:
        return True

    # 检查检查约束
    checks = [ck["name"] for ck in inspector.get_check_constraints(table_name) if ck["name"]]
    return constraint_name in checks


def _table_exists(table_name: str) -> bool:
    """检查表是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    if not _table_exists(table_name):
        return False
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_subscription_notifications", schema=None) as batch_op:
        # 移除唯一约束
        if _constraint_exists("ai_subscription_notifications", "uk_subscription_notification"):
            batch_op.drop_constraint("uk_subscription_notification", type_="unique")

        # 确保索引是非唯一的
        if _index_exists("ai_subscription_notifications", "ix_ai_subscription_notifications_subscription_id"):
            batch_op.drop_index("ix_ai_subscription_notifications_subscription_id")
        batch_op.create_index("ix_ai_subscription_notifications_subscription_id", ["subscription_id"], unique=False)

        # 添加表注释
        batch_op.create_table_comment("助手-通知方式关联表", existing_comment=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_subscription_notifications", schema=None) as batch_op:
        # 移除表注释
        batch_op.drop_table_comment(existing_comment="助手-通知方式关联表")

        # 重新创建唯一约束
        batch_op.create_unique_constraint("uk_subscription_notification", ["subscription_id", "notification_id"])

        # 保持索引为非唯一（因为有唯一约束了）
        if _index_exists("ai_subscription_notifications", "ix_ai_subscription_notifications_subscription_id"):
            batch_op.drop_index("ix_ai_subscription_notifications_subscription_id")
        batch_op.create_index("ix_ai_subscription_notifications_subscription_id", ["subscription_id"], unique=False)

    # ### end Alembic commands ###
