"""check

Revision ID: 5172e3e7211d
Revises: 212b26bfde7a
Create Date: 2025-09-15 14:33:47.727473

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5172e3e7211d"
down_revision = "212b26bfde7a"
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """检查约束是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 检查外键约束
    fks = [fk["name"] for fk in inspector.get_foreign_keys(table_name) if fk["name"]]
    if constraint_name in fks:
        return True

    # 检查唯一约束
    uqs = [uq["name"] for uq in inspector.get_unique_constraints(table_name) if uq["name"]]
    if constraint_name in uqs:
        return True

    # 检查检查约束
    checks = [ck["name"] for ck in inspector.get_check_constraints(table_name) if ck["name"]]
    return constraint_name in checks


def _table_exists(table_name: str) -> bool:
    """检查表是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    if not _table_exists(table_name):
        return False
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_scheduler", schema=None) as batch_op:
        batch_op.alter_column(
            "priority",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_comment="任务优先级（1-10，数字越小优先级越高）",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "max_retries",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_comment="最大重试次数",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "enabled",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_comment="是否启用任务",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "total_run_count",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_comment="任务触发的总次数",
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_scheduler", schema=None) as batch_op:
        batch_op.alter_column(
            "total_run_count",
            existing_type=sa.INTEGER(),
            server_default=sa.text("0"),
            existing_comment="任务触发的总次数",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "enabled",
            existing_type=sa.INTEGER(),
            server_default=sa.text("1"),
            existing_comment="是否启用任务",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "max_retries",
            existing_type=sa.INTEGER(),
            server_default=sa.text("3"),
            existing_comment="最大重试次数",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "priority",
            existing_type=sa.INTEGER(),
            server_default=sa.text("5"),
            existing_comment="任务优先级（1-10，数字越小优先级越高）",
            existing_nullable=False,
        )

    # ### end Alembic commands ###
