"""Add report_pdf_url to risk_report_log

Revision ID: 291f4bc06a93
Revises: 2025110500001
Create Date: 2025-11-05 20:06:07.463128

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "291f4bc06a93"
down_revision = "2025110500001"
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """检查约束是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 检查外键约束
    fks = [fk["name"] for fk in inspector.get_foreign_keys(table_name) if fk["name"]]
    if constraint_name in fks:
        return True

    # 检查唯一约束
    uqs = [uq["name"] for uq in inspector.get_unique_constraints(table_name) if uq["name"]]
    if constraint_name in uqs:
        return True

    # 检查检查约束
    checks = [ck["name"] for ck in inspector.get_check_constraints(table_name) if ck["name"]]
    return constraint_name in checks


def _table_exists(table_name: str) -> bool:
    """检查表是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    if not _table_exists(table_name):
        return False
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查并添加 report_pdf_url 列
    if not _column_exists("risk_report_log", "report_pdf_url"):
        with op.batch_alter_table("risk_report_log", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column("report_pdf_url", sa.String(length=500), nullable=True, comment="报告PDF文件URL")
            )

    # 修改 sys_api_key 表的列
    with op.batch_alter_table("sys_api_key", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_comment="状态(0停用 1启用)",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "usage_count",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_comment="使用次数",
            existing_nullable=False,
        )

    # 检查索引是否存在，如果不存在才创建（在 batch_alter_table 外部使用 op.create_index）
    if not _index_exists("sys_api_key", "ix_sys_api_key_id"):
        op.create_index("ix_sys_api_key_id", "sys_api_key", ["id"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查索引是否存在，如果存在才删除（在 batch_alter_table 外部使用 op.drop_index）
    if _index_exists("sys_api_key", "ix_sys_api_key_id"):
        op.drop_index("ix_sys_api_key_id", table_name="sys_api_key")

    with op.batch_alter_table("sys_api_key", schema=None) as batch_op:
        batch_op.alter_column(
            "usage_count",
            existing_type=sa.INTEGER(),
            server_default=sa.text("0"),
            existing_comment="使用次数",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.INTEGER(),
            server_default=sa.text("1"),
            existing_comment="状态(0停用 1启用)",
            existing_nullable=False,
        )

    # 检查列是否存在，如果存在才删除
    if _column_exists("risk_report_log", "report_pdf_url"):
        with op.batch_alter_table("risk_report_log", schema=None) as batch_op:
            batch_op.drop_column("report_pdf_url")

    # ### end Alembic commands ###
