"""add responsible_persons field to ai_subscription

Revision ID: 5ba3ec2c0950
Revises: 86e4b0c0d814
Create Date: 2025-09-05 20:49:52.395128

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5ba3ec2c0950"
down_revision = "86e4b0c0d814"
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """检查约束是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 检查外键约束
    fks = [fk["name"] for fk in inspector.get_foreign_keys(table_name) if fk["name"]]
    if constraint_name in fks:
        return True

    # 检查唯一约束
    uqs = [uq["name"] for uq in inspector.get_unique_constraints(table_name) if uq["name"]]
    if constraint_name in uqs:
        return True

    # 检查检查约束
    checks = [ck["name"] for ck in inspector.get_check_constraints(table_name) if ck["name"]]
    return constraint_name in checks


def _table_exists(table_name: str) -> bool:
    """检查表是否存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    if not _table_exists(table_name):
        return False
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_subscription", schema=None) as batch_op:
        batch_op.add_column(sa.Column("responsible_persons", sa.JSON(), nullable=True, comment="指定人员列表"))
        batch_op.alter_column(
            "scheduler_id",
            existing_type=sa.BIGINT(),
            type_=sa.Integer(),
            comment="关联的调度任务ID（应用层维护）",
            existing_comment="关联的调度任务ID",
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_subscription", schema=None) as batch_op:
        batch_op.alter_column(
            "scheduler_id",
            existing_type=sa.Integer(),
            type_=sa.BIGINT(),
            comment="关联的调度任务ID",
            existing_comment="关联的调度任务ID（应用层维护）",
            existing_nullable=True,
        )
        batch_op.drop_column("responsible_persons")

    # ### end Alembic commands ###
