"""检查模型与数据库差异

Revision ID: 1dd37692aa40
Revises: 20956ef6a65a
Create Date: 2025-08-15 16:12:35.616568

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "1dd37692aa40"
down_revision = "20956ef6a65a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 跳过主键列的nullable修改，因为主键不能为NULL
    # op.alter_column('risk_report_log', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            existing_comment='报告ID',
    #            autoincrement=True)
    op.create_index(op.f("ix_risk_tag_category_id"), "risk_tag", ["category_id"], unique=False)
    op.create_index(op.f("ix_risk_tag_name"), "risk_tag", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_risk_tag_name"), table_name="risk_tag")
    op.drop_index(op.f("ix_risk_tag_category_id"), table_name="risk_tag")
    # 跳过主键列的nullable修改，因为主键不能为NULL
    # op.alter_column('risk_report_log', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            existing_comment='报告ID',
    #            autoincrement=True)
    # ### end Alembic commands ###
