"""Change report_tags field type from JSON to JSONB

Revision ID: 3dd145ba5ca2
Revises: fa8afcb8b883
Create Date: 2025-08-27 13:04:36.236656

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3dd145ba5ca2"
down_revision = "fa8afcb8b883"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "risk_report_log",
        "report_tags",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        comment="报告标签，JSONB数组",
        existing_comment="报告标签，JSON数组",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "risk_report_log",
        "report_tags",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        comment="报告标签，JSON数组",
        existing_comment="报告标签，JSONB数组",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
